-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    base_offset : IN STD_LOGIC_VECTOR (15 downto 0);
    add_ln388_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    tmp_s : IN STD_LOGIC_VECTOR (8 downto 0);
    sext_ln417 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln291 : IN STD_LOGIC_VECTOR (15 downto 0);
    learn_weight_ready : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln291 : IN STD_LOGIC_VECTOR (0 downto 0);
    pre_id : IN STD_LOGIC_VECTOR (7 downto 0);
    src_group : IN STD_LOGIC_VECTOR (1 downto 0);
    post_traces_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    post_traces_ce0 : OUT STD_LOGIC;
    post_traces_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    weight_memory_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    weight_memory_ce0 : OUT STD_LOGIC;
    weight_memory_we0 : OUT STD_LOGIC;
    weight_memory_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    weight_memory_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    weight_memory_ce1 : OUT STD_LOGIC;
    weight_memory_q1 : IN STD_LOGIC_VECTOR (3 downto 0);
    learn_bridge_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_valid_o_ap_vld : OUT STD_LOGIC;
    learn_bridge_group : OUT STD_LOGIC_VECTOR (1 downto 0);
    learn_bridge_group_ap_vld : OUT STD_LOGIC;
    learn_bridge_src : OUT STD_LOGIC_VECTOR (7 downto 0);
    learn_bridge_src_ap_vld : OUT STD_LOGIC;
    learn_bridge_dst : OUT STD_LOGIC_VECTOR (5 downto 0);
    learn_bridge_dst_ap_vld : OUT STD_LOGIC;
    learn_bridge_data : OUT STD_LOGIC_VECTOR (3 downto 0);
    learn_bridge_data_ap_vld : OUT STD_LOGIC;
    learn_bridge_exc : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_exc_ap_vld : OUT STD_LOGIC;
    learn_bridge_is_inter : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_is_inter_ap_vld : OUT STD_LOGIC;
    learn_bridge_dst_group : OUT STD_LOGIC_VECTOR (1 downto 0);
    learn_bridge_dst_group_ap_vld : OUT STD_LOGIC );
end;


architecture behav of snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv16_FFF8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln388_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln417_cast_fu_242_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln417_cast_reg_606 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln291_cast_fu_246_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln291_cast_reg_611 : STD_LOGIC_VECTOR (27 downto 0);
    signal widx_1_reg_616 : STD_LOGIC_VECTOR (15 downto 0);
    signal post_id_fu_282_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal post_id_reg_625 : STD_LOGIC_VECTOR (8 downto 0);
    signal post_trace_val_reg_636 : STD_LOGIC_VECTOR (7 downto 0);
    signal post_trace_val_reg_636_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal post_trace_val_reg_636_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln399_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln399_reg_641_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal weight_memory_addr_reg_645 : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal weight_memory_addr_reg_645_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln286_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln286_reg_651_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal current_w_reg_655 : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal current_w_reg_655_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal updated_fu_526_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal updated_reg_680 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln395_fu_292_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln388_fu_313_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln301_fu_350_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal jj_fu_150 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln388_fu_272_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_jj_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal widx_fu_154 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln432_fu_297_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_widx_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal post_traces_ce0_local : STD_LOGIC;
    signal weight_memory_ce1_local : STD_LOGIC;
    signal weight_memory_we0_local : STD_LOGIC;
    signal weight_memory_ce0_local : STD_LOGIC;
    signal zext_ln388_1_fu_278_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln395_fu_288_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln286_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln286_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_129_fu_343_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal bit_sel_fu_400_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal bit_sel_fu_400_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln405_fu_414_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal xor_ln405_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln405_fu_414_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal distance_fu_418_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_433_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_433_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_433_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_443_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_443_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_443_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal trunc_ln_fu_448_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_462_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_462_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln405_fu_467_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln1_fu_470_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_fu_480_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_486_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln254_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln255_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln254_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln254_fu_512_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln256_fu_508_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_130_fu_534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal mag_1_fu_547_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_433_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_433_p10 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_443_p00 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_mul_4ns_8ns_12_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component snn_top_hls_mul_12ns_16s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component snn_top_hls_mul_12s_16s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_4ns_8ns_12_3_1_U589 : component snn_top_hls_mul_4ns_8ns_12_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 4,
        din1_WIDTH => 8,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_433_p0,
        din1 => grp_fu_433_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_433_p2);

    mul_12ns_16s_28_4_1_U590 : component snn_top_hls_mul_12ns_16s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_443_p0,
        din1 => grp_fu_443_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_443_p2);

    mul_12s_16s_28_4_1_U591 : component snn_top_hls_mul_12s_16s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln_fu_448_p4,
        din1 => grp_fu_462_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_462_p2);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    jj_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln388_fu_266_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    jj_fu_150 <= add_ln388_fu_272_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    jj_fu_150 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    widx_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln388_fu_266_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    widx_fu_154 <= add_ln432_fu_297_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    widx_fu_154 <= base_offset;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                current_w_reg_655_pp0_iter10_reg <= current_w_reg_655_pp0_iter9_reg;
                current_w_reg_655_pp0_iter11_reg <= current_w_reg_655_pp0_iter10_reg;
                current_w_reg_655_pp0_iter5_reg <= current_w_reg_655;
                current_w_reg_655_pp0_iter6_reg <= current_w_reg_655_pp0_iter5_reg;
                current_w_reg_655_pp0_iter7_reg <= current_w_reg_655_pp0_iter6_reg;
                current_w_reg_655_pp0_iter8_reg <= current_w_reg_655_pp0_iter7_reg;
                current_w_reg_655_pp0_iter9_reg <= current_w_reg_655_pp0_iter8_reg;
                icmp_ln399_reg_641_pp0_iter10_reg <= icmp_ln399_reg_641_pp0_iter9_reg;
                icmp_ln399_reg_641_pp0_iter11_reg <= icmp_ln399_reg_641_pp0_iter10_reg;
                icmp_ln399_reg_641_pp0_iter12_reg <= icmp_ln399_reg_641_pp0_iter11_reg;
                icmp_ln399_reg_641_pp0_iter2_reg <= icmp_ln399_reg_641;
                icmp_ln399_reg_641_pp0_iter3_reg <= icmp_ln399_reg_641_pp0_iter2_reg;
                icmp_ln399_reg_641_pp0_iter4_reg <= icmp_ln399_reg_641_pp0_iter3_reg;
                icmp_ln399_reg_641_pp0_iter5_reg <= icmp_ln399_reg_641_pp0_iter4_reg;
                icmp_ln399_reg_641_pp0_iter6_reg <= icmp_ln399_reg_641_pp0_iter5_reg;
                icmp_ln399_reg_641_pp0_iter7_reg <= icmp_ln399_reg_641_pp0_iter6_reg;
                icmp_ln399_reg_641_pp0_iter8_reg <= icmp_ln399_reg_641_pp0_iter7_reg;
                icmp_ln399_reg_641_pp0_iter9_reg <= icmp_ln399_reg_641_pp0_iter8_reg;
                or_ln286_reg_651_pp0_iter10_reg <= or_ln286_reg_651_pp0_iter9_reg;
                or_ln286_reg_651_pp0_iter11_reg <= or_ln286_reg_651_pp0_iter10_reg;
                or_ln286_reg_651_pp0_iter12_reg <= or_ln286_reg_651_pp0_iter11_reg;
                or_ln286_reg_651_pp0_iter2_reg <= or_ln286_reg_651;
                or_ln286_reg_651_pp0_iter3_reg <= or_ln286_reg_651_pp0_iter2_reg;
                or_ln286_reg_651_pp0_iter4_reg <= or_ln286_reg_651_pp0_iter3_reg;
                or_ln286_reg_651_pp0_iter5_reg <= or_ln286_reg_651_pp0_iter4_reg;
                or_ln286_reg_651_pp0_iter6_reg <= or_ln286_reg_651_pp0_iter5_reg;
                or_ln286_reg_651_pp0_iter7_reg <= or_ln286_reg_651_pp0_iter6_reg;
                or_ln286_reg_651_pp0_iter8_reg <= or_ln286_reg_651_pp0_iter7_reg;
                or_ln286_reg_651_pp0_iter9_reg <= or_ln286_reg_651_pp0_iter8_reg;
                post_trace_val_reg_636_pp0_iter2_reg <= post_trace_val_reg_636;
                post_trace_val_reg_636_pp0_iter3_reg <= post_trace_val_reg_636_pp0_iter2_reg;
                updated_reg_680 <= updated_fu_526_p3;
                weight_memory_addr_reg_645_pp0_iter10_reg <= weight_memory_addr_reg_645_pp0_iter9_reg;
                weight_memory_addr_reg_645_pp0_iter11_reg <= weight_memory_addr_reg_645_pp0_iter10_reg;
                weight_memory_addr_reg_645_pp0_iter12_reg <= weight_memory_addr_reg_645_pp0_iter11_reg;
                weight_memory_addr_reg_645_pp0_iter2_reg <= weight_memory_addr_reg_645;
                weight_memory_addr_reg_645_pp0_iter3_reg <= weight_memory_addr_reg_645_pp0_iter2_reg;
                weight_memory_addr_reg_645_pp0_iter4_reg <= weight_memory_addr_reg_645_pp0_iter3_reg;
                weight_memory_addr_reg_645_pp0_iter5_reg <= weight_memory_addr_reg_645_pp0_iter4_reg;
                weight_memory_addr_reg_645_pp0_iter6_reg <= weight_memory_addr_reg_645_pp0_iter5_reg;
                weight_memory_addr_reg_645_pp0_iter7_reg <= weight_memory_addr_reg_645_pp0_iter6_reg;
                weight_memory_addr_reg_645_pp0_iter8_reg <= weight_memory_addr_reg_645_pp0_iter7_reg;
                weight_memory_addr_reg_645_pp0_iter9_reg <= weight_memory_addr_reg_645_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln399_reg_641 <= icmp_ln399_fu_317_p2;
                or_ln286_reg_651 <= or_ln286_fu_338_p2;
                post_id_reg_625 <= post_id_fu_282_p2;
                post_trace_val_reg_636 <= post_traces_q0;
                sext_ln291_cast_reg_611 <= sext_ln291_cast_fu_246_p1;
                sext_ln417_cast_reg_606 <= sext_ln417_cast_fu_242_p1;
                weight_memory_addr_reg_645 <= zext_ln388_fu_313_p1(14 - 1 downto 0);
                widx_1_reg_616 <= ap_sig_allocacmp_widx_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                current_w_reg_655 <= weight_memory_q1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln388_fu_272_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_jj_1) + unsigned(ap_const_lv5_1));
    add_ln432_fu_297_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_widx_1) + unsigned(ap_const_lv16_1));
    and_ln286_fu_332_p2 <= (xor_ln286_fu_327_p2 and learn_bridge_valid_i);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln388_fu_266_p2)
    begin
        if (((icmp_ln388_fu_266_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_jj_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, jj_fu_150, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_jj_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_jj_1 <= jj_fu_150;
        end if; 
    end process;


    ap_sig_allocacmp_widx_1_assign_proc : process(ap_CS_fsm_pp0_stage0, base_offset, ap_block_pp0_stage0, ap_loop_init, widx_fu_154)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_widx_1 <= base_offset;
        else 
            ap_sig_allocacmp_widx_1 <= widx_fu_154;
        end if; 
    end process;

    bit_sel_fu_400_p1 <= weight_memory_q1;
    bit_sel_fu_400_p3 <= bit_sel_fu_400_p1(3 downto 3);
    distance_fu_418_p3 <= (xor_ln405_fu_408_p2 & trunc_ln405_fu_414_p1);
    grp_fu_433_p0 <= grp_fu_433_p00(4 - 1 downto 0);
    grp_fu_433_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(distance_fu_418_p3),12));
    grp_fu_433_p1 <= grp_fu_433_p10(8 - 1 downto 0);
    grp_fu_433_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(post_trace_val_reg_636_pp0_iter3_reg),12));
    grp_fu_443_p0 <= grp_fu_443_p00(12 - 1 downto 0);
    grp_fu_443_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_433_p2),28));
    grp_fu_443_p1 <= sext_ln417_cast_reg_606(16 - 1 downto 0);
    grp_fu_462_p1 <= sext_ln291_cast_reg_611(16 - 1 downto 0);
    icmp_ln254_fu_496_p2 <= "1" when (signed(tmp_fu_486_p4) > signed(ap_const_lv13_0)) else "0";
    icmp_ln255_fu_502_p2 <= "1" when (signed(w_fu_480_p2) < signed(ap_const_lv16_FFF8)) else "0";
    icmp_ln388_fu_266_p2 <= "1" when (ap_sig_allocacmp_widx_1 = add_ln388_1) else "0";
    icmp_ln399_fu_317_p2 <= "1" when (post_traces_q0 = ap_const_lv8_0) else "0";
    learn_bridge_data <= 
        mag_1_fu_547_p2 when (tmp_130_fu_534_p3(0) = '1') else 
        updated_reg_680;

    learn_bridge_data_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, icmp_ln399_reg_641_pp0_iter12_reg, or_ln286_reg_651_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (or_ln286_reg_651_pp0_iter12_reg = ap_const_lv1_0) and (icmp_ln399_reg_641_pp0_iter12_reg = ap_const_lv1_0))) then 
            learn_bridge_data_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_data_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_dst <= post_id_reg_625(6 - 1 downto 0);

    learn_bridge_dst_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_dst_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_dst_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_dst_group <= select_ln301_fu_350_p3;

    learn_bridge_dst_group_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_dst_group_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_dst_group_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_exc <= (tmp_130_fu_534_p3 xor ap_const_lv1_1);

    learn_bridge_exc_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, icmp_ln399_reg_641_pp0_iter12_reg, or_ln286_reg_651_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (or_ln286_reg_651_pp0_iter12_reg = ap_const_lv1_0) and (icmp_ln399_reg_641_pp0_iter12_reg = ap_const_lv1_0))) then 
            learn_bridge_exc_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_exc_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_group <= src_group;

    learn_bridge_group_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_group_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_group_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_is_inter <= "0" when (src_group = select_ln301_fu_350_p3) else "1";

    learn_bridge_is_inter_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_is_inter_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_is_inter_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_src <= pre_id;

    learn_bridge_src_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_src_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_src_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    learn_bridge_valid_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, learn_bridge_valid_i, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_valid_o <= ap_const_lv1_1;
        else 
            learn_bridge_valid_o <= learn_bridge_valid_i;
        end if; 
    end process;


    learn_bridge_valid_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln399_fu_317_p2, or_ln286_fu_338_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln286_fu_338_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln399_fu_317_p2 = ap_const_lv1_0))) then 
            learn_bridge_valid_o_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mag_1_fu_547_p2 <= std_logic_vector(unsigned(ap_const_lv4_0) - unsigned(updated_reg_680));
    or_ln254_fu_520_p2 <= (icmp_ln255_fu_502_p2 or icmp_ln254_fu_496_p2);
    or_ln286_fu_338_p2 <= (icmp_ln291 or and_ln286_fu_332_p2);
    post_id_fu_282_p2 <= std_logic_vector(unsigned(zext_ln388_1_fu_278_p1) + unsigned(tmp_s));
    post_traces_address0 <= zext_ln395_fu_292_p1(10 - 1 downto 0);
    post_traces_ce0 <= post_traces_ce0_local;

    post_traces_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            post_traces_ce0_local <= ap_const_logic_1;
        else 
            post_traces_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln254_fu_512_p3 <= 
        ap_const_lv4_7 when (icmp_ln254_fu_496_p2(0) = '1') else 
        ap_const_lv4_8;
    select_ln301_fu_350_p3 <= 
        ap_const_lv2_3 when (tmp_129_fu_343_p3(0) = '1') else 
        ap_const_lv2_0;
        sext_ln291_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln291),28));

        sext_ln395_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(post_id_fu_282_p2),10));

        sext_ln405_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_reg_655_pp0_iter11_reg),16));

        sext_ln417_cast_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln417),28));

    tmp_129_fu_343_p3 <= post_id_reg_625(8 downto 8);
    tmp_130_fu_534_p3 <= updated_reg_680(3 downto 3);
    tmp_fu_486_p4 <= w_fu_480_p2(15 downto 3);
    trunc_ln1_fu_470_p4 <= grp_fu_462_p2(23 downto 8);
    trunc_ln256_fu_508_p1 <= w_fu_480_p2(4 - 1 downto 0);
    trunc_ln405_fu_414_p0 <= weight_memory_q1;
    trunc_ln405_fu_414_p1 <= trunc_ln405_fu_414_p0(3 - 1 downto 0);
    trunc_ln_fu_448_p4 <= grp_fu_443_p2(27 downto 16);
    updated_fu_526_p3 <= 
        select_ln254_fu_512_p3 when (or_ln254_fu_520_p2(0) = '1') else 
        trunc_ln256_fu_508_p1;
    w_fu_480_p2 <= std_logic_vector(signed(sext_ln405_fu_467_p1) - signed(trunc_ln1_fu_470_p4));
    weight_memory_address0 <= weight_memory_addr_reg_645_pp0_iter12_reg;
    weight_memory_address1 <= zext_ln388_fu_313_p1(14 - 1 downto 0);
    weight_memory_ce0 <= weight_memory_ce0_local;

    weight_memory_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1)))) then 
            weight_memory_ce0_local <= ap_const_logic_1;
        else 
            weight_memory_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weight_memory_ce1 <= weight_memory_ce1_local;

    weight_memory_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            weight_memory_ce1_local <= ap_const_logic_1;
        else 
            weight_memory_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weight_memory_d0 <= updated_reg_680;
    weight_memory_we0 <= weight_memory_we0_local;

    weight_memory_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, icmp_ln399_reg_641_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (icmp_ln399_reg_641_pp0_iter12_reg = ap_const_lv1_0))) then 
            weight_memory_we0_local <= ap_const_logic_1;
        else 
            weight_memory_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln286_fu_327_p2 <= (learn_weight_ready xor ap_const_lv1_1);
    xor_ln405_fu_408_p2 <= (bit_sel_fu_400_p3 xor ap_const_lv1_1);
    zext_ln388_1_fu_278_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_jj_1),9));
    zext_ln388_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widx_1_reg_616),64));
    zext_ln395_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln395_fu_288_p1),64));
end behav;
