

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "26", "28", "30", "32", "34", "36", "51", "53", "62", "71", "77", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118"],
		"CDFG" : "snn_top_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "36", "EstimateLatencyMax" : "4577686899",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "1",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctrl_reg", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_reg", "Type" : "None", "Direction" : "I"},
			{"Name" : "mode_reg", "Type" : "None", "Direction" : "I"},
			{"Name" : "time_steps_reg", "Type" : "None", "Direction" : "I"},
			{"Name" : "learning_params", "Type" : "None", "Direction" : "I"},
			{"Name" : "encoder_config", "Type" : "None", "Direction" : "I"},
			{"Name" : "status_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "spike_count_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "weight_sum_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "version_reg", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s_axis_spikes_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes",
				"BlockSignal" : [
					{"Name" : "s_axis_spikes_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_spikes_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_spikes_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_spikes_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_spikes_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_spikes_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_spikes_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_spikes"},
			{"Name" : "s_axis_data_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_data_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_keep_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_strb_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_user_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_last_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_id_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_data_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "s_axis_data_V_dest_V", "Inst_start_state" : "5", "Inst_end_state" : "6"}]},
			{"Name" : "s_axis_weights_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights",
				"BlockSignal" : [
					{"Name" : "s_axis_weights_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_weights_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "s_axis_weights_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "s_axis_weights_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "s_axis_weights_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "s_axis_weights_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "s_axis_weights_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_weights"},
			{"Name" : "m_axis_spikes_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes",
				"BlockSignal" : [
					{"Name" : "m_axis_spikes_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "m_axis_spikes_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_spikes_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_spikes_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_spikes_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_spikes_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_spikes_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_spikes"},
			{"Name" : "m_axis_weights_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights",
				"BlockSignal" : [
					{"Name" : "m_axis_weights_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "m_axis_weights_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "m_axis_weights_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "m_axis_weights_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "m_axis_weights_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "m_axis_weights_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "m_axis_weights_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_weights"},
			{"Name" : "reward_signal", "Type" : "None", "Direction" : "I"},
			{"Name" : "spike_in_valid", "Type" : "None", "Direction" : "O"},
			{"Name" : "spike_in_neuron_id", "Type" : "None", "Direction" : "O"},
			{"Name" : "spike_in_weight", "Type" : "None", "Direction" : "O"},
			{"Name" : "spike_in_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "spike_out_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "spike_out_neuron_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "spike_out_weight", "Type" : "None", "Direction" : "I"},
			{"Name" : "spike_out_ready", "Type" : "None", "Direction" : "O"},
			{"Name" : "snn_enable", "Type" : "None", "Direction" : "O"},
			{"Name" : "snn_reset", "Type" : "None", "Direction" : "O"},
			{"Name" : "threshold_out", "Type" : "None", "Direction" : "O"},
			{"Name" : "leak_rate_out", "Type" : "None", "Direction" : "O"},
			{"Name" : "snn_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "snn_busy", "Type" : "None", "Direction" : "I"},
			{"Name" : "initialized", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "last_mode", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "timestamp", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "spike_counter", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "encoder_spike_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "encoder_spike_counter", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "checkpoint_col", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "encoder_frame_loaded", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "encoder_frame_loaded", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL22encoder_temporal_fired_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_encoder_reset_temporal_state_fu_1012", "Port" : "p_ZL22encoder_temporal_fired_0", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL22encoder_temporal_fired_0", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL22encoder_temporal_start_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_encoder_reset_temporal_state_fu_1012", "Port" : "p_ZL22encoder_temporal_start_0", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL22encoder_temporal_start_0", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL22encoder_temporal_fired_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_encoder_reset_temporal_state_fu_1012", "Port" : "p_ZL22encoder_temporal_fired_1", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL22encoder_temporal_fired_1", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL22encoder_temporal_start_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "24", "SubInstance" : "grp_encoder_reset_temporal_state_fu_1012", "Port" : "p_ZL22encoder_temporal_start_1", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL22encoder_temporal_start_1", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL15pre_eligibility_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "26", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026", "Port" : "p_ZL15pre_eligibility_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL15pre_eligibility_0", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "77", "SubInstance" : "grp_decay_eligibility_traces_fu_1218", "Port" : "p_ZL15pre_eligibility_0", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "26", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026", "Port" : "p_ZL16post_eligibility_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL16post_eligibility_0", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "77", "SubInstance" : "grp_decay_eligibility_traces_fu_1218", "Port" : "p_ZL16post_eligibility_0", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "p_ZL15pre_eligibility_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "26", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026", "Port" : "p_ZL15pre_eligibility_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL15pre_eligibility_1", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "77", "SubInstance" : "grp_decay_eligibility_traces_fu_1218", "Port" : "p_ZL15pre_eligibility_1", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "26", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026", "Port" : "p_ZL16post_eligibility_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL16post_eligibility_1", "Inst_start_state" : "17", "Inst_end_state" : "18"},
					{"ID" : "77", "SubInstance" : "grp_decay_eligibility_traces_fu_1218", "Port" : "p_ZL16post_eligibility_1", "Inst_start_state" : "19", "Inst_end_state" : "20"}]},
			{"Name" : "pre_traces_trace_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "pre_traces_trace_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "pre_traces_trace_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "pre_traces_trace_0", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "pre_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "pre_traces_last_spike_time_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "pre_traces_last_spike_time_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "pre_traces_last_spike_time_0", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "post_traces_trace_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "post_traces_trace_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "post_traces_trace_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "post_traces_trace_0", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "post_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "post_traces_last_spike_time_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "post_traces_last_spike_time_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "post_traces_last_spike_time_0", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "pre_traces_trace_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "pre_traces_trace_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "pre_traces_trace_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "pre_traces_trace_1", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "pre_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "pre_traces_last_spike_time_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "pre_traces_last_spike_time_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "pre_traces_last_spike_time_1", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "post_traces_trace_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "post_traces_trace_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "post_traces_trace_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "post_traces_trace_1", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "post_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "28", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Port" : "post_traces_last_spike_time_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "post_traces_last_spike_time_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "post_traces_last_spike_time_1", "Inst_start_state" : "14", "Inst_end_state" : "15"}]},
			{"Name" : "p_ZL17encoder_phase_acc_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ENCODER_fu_1058", "Port" : "p_ZL17encoder_phase_acc_0", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL17encoder_phase_acc_0", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL17encoder_phase_acc_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "30", "SubInstance" : "grp_snn_top_hls_Pipeline_RESET_ENCODER_fu_1058", "Port" : "p_ZL17encoder_phase_acc_1", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL17encoder_phase_acc_1", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "latency_window_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "latency_window_counter", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "grp_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER_fu_1066", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "51", "SubInstance" : "grp_snn_top_hls_Pipeline_WEIGHT_SUM_fu_1135", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "8", "Inst_end_state" : "23"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "32", "SubInstance" : "grp_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER_fu_1066", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "51", "SubInstance" : "grp_snn_top_hls_Pipeline_WEIGHT_SUM_fu_1135", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "8", "Inst_end_state" : "23"},
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "71", "SubInstance" : "grp_apply_rstdp_reward_fu_1200", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "17", "Inst_end_state" : "18"}]},
			{"Name" : "p_ZL13encoder_frame_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "p_ZL13encoder_frame_0", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL13encoder_frame_0", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "p_ZL13encoder_frame_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "34", "SubInstance" : "grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Port" : "p_ZL13encoder_frame_1", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "p_ZL13encoder_frame_1", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "lfsr", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "36", "SubInstance" : "grp_run_encoder_once_fu_1096", "Port" : "lfsr", "Inst_start_state" : "8", "Inst_end_state" : "9"}]},
			{"Name" : "EXP_DECAY_LUT", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "53", "SubInstance" : "grp_process_pre_spike_aer_fu_1144", "Port" : "EXP_DECAY_LUT", "Inst_start_state" : "11", "Inst_end_state" : "12"},
					{"ID" : "62", "SubInstance" : "grp_process_post_spike_aer_fu_1172", "Port" : "EXP_DECAY_LUT", "Inst_start_state" : "14", "Inst_end_state" : "15"}]}],
		"Loop" : [
			{"Name" : "TIME_LOOP", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "35", "FirstState" : "ap_ST_fsm_state8", "LastState" : ["ap_ST_fsm_state22"], "QuitState" : ["ap_ST_fsm_state8"], "PreState" : ["ap_ST_fsm_state7"], "PostState" : ["ap_ST_fsm_state23"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL22encoder_temporal_fired_0_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL22encoder_temporal_start_0_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL22encoder_temporal_fired_1_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL22encoder_temporal_start_1_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL15pre_eligibility_0_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL16post_eligibility_0_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL15pre_eligibility_1_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL16post_eligibility_1_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pre_traces_trace_0_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pre_traces_last_spike_time_0_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.post_traces_trace_0_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.post_traces_last_spike_time_0_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pre_traces_trace_1_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.pre_traces_last_spike_time_1_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.post_traces_trace_1_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.post_traces_last_spike_time_1_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL17encoder_phase_acc_0_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL17encoder_phase_acc_1_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL13weight_memory_0_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL13weight_memory_1_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL13encoder_frame_0_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.p_ZL13encoder_frame_1_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.EXP_DECAY_LUT_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_encoder_reset_temporal_state_fu_1012", "Parent" : "0", "Child" : ["25"],
		"CDFG" : "encoder_reset_temporal_state",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "786", "EstimateLatencyMax" : "786",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "now_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZL22encoder_temporal_fired_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL22encoder_temporal_start_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL22encoder_temporal_fired_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL22encoder_temporal_start_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_48_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_encoder_reset_temporal_state_fu_1012.flow_control_loop_pipe_sequential_init_U", "Parent" : "24"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026", "Parent" : "0", "Child" : ["27"],
		"CDFG" : "snn_top_hls_Pipeline_RESET_ELIG",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "258", "EstimateLatencyMax" : "258",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL15pre_eligibility_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL15pre_eligibility_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "RESET_ELIG", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_ELIG_fu_1026.flow_control_loop_pipe_sequential_init_U", "Parent" : "26"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038", "Parent" : "0", "Child" : ["29"],
		"CDFG" : "snn_top_hls_Pipeline_RESET_TRACES",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "258", "EstimateLatencyMax" : "258",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pre_traces_trace_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "pre_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "post_traces_trace_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "post_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "pre_traces_trace_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "pre_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "post_traces_trace_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "post_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "RESET_TRACES", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_TRACES_fu_1038.flow_control_loop_pipe_sequential_init_U", "Parent" : "28"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_ENCODER_fu_1058", "Parent" : "0", "Child" : ["31"],
		"CDFG" : "snn_top_hls_Pipeline_RESET_ENCODER",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "786", "EstimateLatencyMax" : "786",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL17encoder_phase_acc_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL17encoder_phase_acc_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "RESET_ENCODER", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_RESET_ENCODER_fu_1058.flow_control_loop_pipe_sequential_init_U", "Parent" : "30"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER_fu_1066", "Parent" : "0", "Child" : ["33"],
		"CDFG" : "snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65538", "EstimateLatencyMax" : "65538",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_INIT_WEIGHT_OUTER_INIT_WEIGHT_INNER_fu_1066.flow_control_loop_pipe_sequential_init_U", "Parent" : "32"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074", "Parent" : "0", "Child" : ["35"],
		"CDFG" : "snn_top_hls_Pipeline_LOAD_FRAME",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2", "EstimateLatencyMax" : "198",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "1",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_data_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data",
				"BlockSignal" : [
					{"Name" : "s_axis_data_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_data_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "s_axis_data_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "s_axis_data_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "s_axis_data_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "s_axis_data_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "s_axis_data_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_data"},
			{"Name" : "p_ZL13encoder_frame_0", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_ZL13encoder_frame_1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "LOAD_FRAME", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_LOAD_FRAME_fu_1074.flow_control_loop_pipe_sequential_init_U", "Parent" : "34"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096", "Parent" : "0", "Child" : ["37"],
		"CDFG" : "run_encoder_once",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1576",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "config_encoding_type_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_two_neuron_enable_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_baseline_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_rate_scale_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_latency_window_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_delta_threshold_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_delta_decay_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_num_channels_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_default_weight_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "time_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "encoder_spikes", "Type" : "Fifo", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "encoder_spikes", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "encoder_frame_loaded", "Type" : "None", "Direction" : "I"},
			{"Name" : "latency_window_counter", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZL13encoder_frame_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL13encoder_frame_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "lfsr", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "lfsr", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "encoder_spike_counter", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "encoder_spike_counter", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL22encoder_temporal_fired_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL22encoder_temporal_fired_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL22encoder_temporal_fired_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL22encoder_temporal_fired_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL22encoder_temporal_start_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL22encoder_temporal_start_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL22encoder_temporal_start_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL22encoder_temporal_start_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL17encoder_phase_acc_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL17encoder_phase_acc_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL17encoder_phase_acc_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL17encoder_phase_acc_0", "Inst_start_state" : "2", "Inst_end_state" : "3"}]},
			{"Name" : "p_ZL13encoder_frame_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "37", "SubInstance" : "grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Port" : "p_ZL13encoder_frame_1", "Inst_start_state" : "2", "Inst_end_state" : "3"}]}]},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158", "Parent" : "36", "Child" : ["38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50"],
		"CDFG" : "run_encoder_once_Pipeline_ENCODER_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1574", "EstimateLatencyMax" : "1574",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "1",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "time_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_num_channels_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_baseline_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_encoding_type_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_two_neuron_enable_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln108", "Type" : "None", "Direction" : "I"},
			{"Name" : "encoder_spikes", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "encoder_spikes_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "config_default_weight_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "latency_window_reset_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "zext_ln137_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_delta_decay_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "config_delta_threshold_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZL13encoder_frame_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "lfsr", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "encoder_spike_counter", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "p_ZL22encoder_temporal_fired_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL22encoder_temporal_fired_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL22encoder_temporal_start_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL22encoder_temporal_start_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL17encoder_phase_acc_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL17encoder_phase_acc_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL13encoder_frame_1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "ENCODER_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U31", "Parent" : "37"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U32", "Parent" : "37"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U33", "Parent" : "37"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U34", "Parent" : "37"},
	{"ID" : "42", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U35", "Parent" : "37"},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U36", "Parent" : "37"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U37", "Parent" : "37"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U38", "Parent" : "37"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U39", "Parent" : "37"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_16ns_8ns_24_1_1_U40", "Parent" : "37"},
	{"ID" : "48", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U41", "Parent" : "37"},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.mul_8ns_16ns_24_1_1_U42", "Parent" : "37"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_run_encoder_once_fu_1096.grp_run_encoder_once_Pipeline_ENCODER_LOOP_fu_158.flow_control_loop_pipe_sequential_init_U", "Parent" : "37"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_WEIGHT_SUM_fu_1135", "Parent" : "0", "Child" : ["52"],
		"CDFG" : "snn_top_hls_Pipeline_WEIGHT_SUM",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "19", "EstimateLatencyMax" : "19",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "weight_sum_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "WEIGHT_SUM", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage1", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage1_subdone", "QuitState" : "ap_ST_fsm_pp0_stage1", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage1_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_snn_top_hls_Pipeline_WEIGHT_SUM_fu_1135.flow_control_loop_pipe_sequential_init_U", "Parent" : "51"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144", "Parent" : "0", "Child" : ["54", "61"],
		"CDFG" : "process_pre_spike_aer",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "271", "EstimateLatencyMax" : "271",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "pre_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "current_time", "Type" : "None", "Direction" : "I"},
			{"Name" : "pre_traces_trace_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "pre_traces_trace_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "pre_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "pre_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "EXP_DECAY_LUT", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "EXP_DECAY_LUT", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "post_traces_trace_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "post_traces_trace_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "post_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "post_traces_last_spike_time_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "post_traces_trace_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "post_traces_trace_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "post_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "post_traces_last_spike_time_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "54", "SubInstance" : "grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]}]},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161", "Parent" : "53", "Child" : ["55", "56", "57", "58", "59", "60"],
		"CDFG" : "process_pre_spike_aer_Pipeline_LTD_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "264", "EstimateLatencyMax" : "264",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "current_time", "Type" : "None", "Direction" : "I"},
			{"Name" : "pre_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "post_traces_trace_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "post_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "EXP_DECAY_LUT", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "post_traces_trace_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "post_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "LTD_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.EXP_DECAY_LUT_U", "Parent" : "54"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.mul_8ns_8ns_16_1_1_U88", "Parent" : "54"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.mul_8ns_8ns_16_1_1_U89", "Parent" : "54"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.mul_8ns_8ns_16_1_1_U90", "Parent" : "54"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.mul_8ns_8ns_16_1_1_U91", "Parent" : "54"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161.flow_control_loop_pipe_sequential_init_U", "Parent" : "54"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_process_pre_spike_aer_fu_1144.mul_8ns_8ns_16_1_1_U102", "Parent" : "53"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172", "Parent" : "0", "Child" : ["63", "70"],
		"CDFG" : "process_post_spike_aer",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "271", "EstimateLatencyMax" : "271",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "post_id", "Type" : "None", "Direction" : "I"},
			{"Name" : "current_time", "Type" : "None", "Direction" : "I"},
			{"Name" : "post_traces_trace_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "post_traces_trace_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "post_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "post_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "EXP_DECAY_LUT", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "EXP_DECAY_LUT", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "pre_traces_trace_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "pre_traces_trace_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "pre_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "pre_traces_last_spike_time_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "pre_traces_trace_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "pre_traces_trace_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "pre_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "pre_traces_last_spike_time_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "7", "Inst_end_state" : "8"}]}]},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161", "Parent" : "62", "Child" : ["64", "65", "66", "67", "68", "69"],
		"CDFG" : "process_post_spike_aer_Pipeline_LTP_LOOP",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "264", "EstimateLatencyMax" : "264",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "lshr_ln", "Type" : "None", "Direction" : "I"},
			{"Name" : "current_time", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "pre_traces_trace_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "pre_traces_last_spike_time_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "EXP_DECAY_LUT", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "pre_traces_trace_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "pre_traces_last_spike_time_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "LTP_LOOP", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "2", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.EXP_DECAY_LUT_U", "Parent" : "63"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.mul_8ns_8ns_16_1_1_U116", "Parent" : "63"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.mul_8ns_8ns_16_1_1_U117", "Parent" : "63"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.mul_8ns_8ns_16_1_1_U118", "Parent" : "63"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.mul_8ns_8ns_16_1_1_U119", "Parent" : "63"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.grp_process_post_spike_aer_Pipeline_LTP_LOOP_fu_161.flow_control_loop_pipe_sequential_init_U", "Parent" : "63"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_process_post_spike_aer_fu_1172.mul_8ns_8ns_16_1_1_U129", "Parent" : "62"},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200", "Parent" : "0", "Child" : ["72", "76"],
		"CDFG" : "apply_rstdp_reward",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "67585",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "reward_signal", "Type" : "None", "Direction" : "I"},
			{"Name" : "params_rstdp_enable_val", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZL15pre_eligibility_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL15pre_eligibility_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132", "Port" : "p_ZL16post_eligibility_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132", "Port" : "p_ZL16post_eligibility_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132", "Port" : "p_ZL13weight_memory_0", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "72", "SubInstance" : "grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132", "Port" : "p_ZL13weight_memory_1", "Inst_start_state" : "3", "Inst_end_state" : "4"}]}],
		"Loop" : [
			{"Name" : "RSTDP_OUTER", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "4", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state4"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200.grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132", "Parent" : "71", "Child" : ["73", "74", "75"],
		"CDFG" : "apply_rstdp_reward_Pipeline_RSTDP_INNER",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "261", "EstimateLatencyMax" : "261",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "i", "Type" : "None", "Direction" : "I"},
			{"Name" : "sext_ln486", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_sel", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_ZL13weight_memory_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL13weight_memory_1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "RSTDP_INNER", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200.grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132.mul_8s_8s_16_1_1_U143", "Parent" : "72"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200.grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132.sparsemux_9_3_7_1_1_U144", "Parent" : "72"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200.grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132.flow_control_loop_pipe_sequential_init_U", "Parent" : "72"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_apply_rstdp_reward_fu_1200.sparsemux_7_2_2_1_1_U155", "Parent" : "71"},
	{"ID" : "77", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_decay_eligibility_traces_fu_1218", "Parent" : "0", "Child" : ["78", "80"],
		"CDFG" : "decay_eligibility_traces",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "132", "EstimateLatencyMax" : "132",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL15pre_eligibility_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "78", "SubInstance" : "grp_decay_eligibility_traces_Pipeline_DECAY_PRE_fu_22", "Port" : "p_ZL15pre_eligibility_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "p_ZL15pre_eligibility_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "78", "SubInstance" : "grp_decay_eligibility_traces_Pipeline_DECAY_PRE_fu_22", "Port" : "p_ZL15pre_eligibility_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "80", "SubInstance" : "grp_decay_eligibility_traces_Pipeline_DECAY_POST_fu_30", "Port" : "p_ZL16post_eligibility_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "80", "SubInstance" : "grp_decay_eligibility_traces_Pipeline_DECAY_POST_fu_30", "Port" : "p_ZL16post_eligibility_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_decay_eligibility_traces_fu_1218.grp_decay_eligibility_traces_Pipeline_DECAY_PRE_fu_22", "Parent" : "77", "Child" : ["79"],
		"CDFG" : "decay_eligibility_traces_Pipeline_DECAY_PRE",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "131", "EstimateLatencyMax" : "131",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL15pre_eligibility_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL15pre_eligibility_1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "DECAY_PRE", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_decay_eligibility_traces_fu_1218.grp_decay_eligibility_traces_Pipeline_DECAY_PRE_fu_22.flow_control_loop_pipe_sequential_init_U", "Parent" : "78"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_decay_eligibility_traces_fu_1218.grp_decay_eligibility_traces_Pipeline_DECAY_POST_fu_30", "Parent" : "77", "Child" : ["81"],
		"CDFG" : "decay_eligibility_traces_Pipeline_DECAY_POST",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "131", "EstimateLatencyMax" : "131",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_ZL16post_eligibility_0", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "p_ZL16post_eligibility_1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "DECAY_POST", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.grp_decay_eligibility_traces_fu_1218.grp_decay_eligibility_traces_Pipeline_DECAY_POST_fu_30.flow_control_loop_pipe_sequential_init_U", "Parent" : "80"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.ctrl_s_axi_U", "Parent" : "0"},
	{"ID" : "83", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.encoder_spikes_fifo_U", "Parent" : "0"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_data_V_U", "Parent" : "0"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_keep_V_U", "Parent" : "0"},
	{"ID" : "86", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_strb_V_U", "Parent" : "0"},
	{"ID" : "87", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_user_V_U", "Parent" : "0"},
	{"ID" : "88", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_last_V_U", "Parent" : "0"},
	{"ID" : "89", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_id_V_U", "Parent" : "0"},
	{"ID" : "90", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_spikes_V_dest_V_U", "Parent" : "0"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_data_V_U", "Parent" : "0"},
	{"ID" : "92", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_keep_V_U", "Parent" : "0"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_strb_V_U", "Parent" : "0"},
	{"ID" : "94", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_user_V_U", "Parent" : "0"},
	{"ID" : "95", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_last_V_U", "Parent" : "0"},
	{"ID" : "96", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_id_V_U", "Parent" : "0"},
	{"ID" : "97", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_data_V_dest_V_U", "Parent" : "0"},
	{"ID" : "98", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_data_V_U", "Parent" : "0"},
	{"ID" : "99", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_keep_V_U", "Parent" : "0"},
	{"ID" : "100", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_strb_V_U", "Parent" : "0"},
	{"ID" : "101", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_user_V_U", "Parent" : "0"},
	{"ID" : "102", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_last_V_U", "Parent" : "0"},
	{"ID" : "103", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_id_V_U", "Parent" : "0"},
	{"ID" : "104", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_weights_V_dest_V_U", "Parent" : "0"},
	{"ID" : "105", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_data_V_U", "Parent" : "0"},
	{"ID" : "106", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_keep_V_U", "Parent" : "0"},
	{"ID" : "107", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_strb_V_U", "Parent" : "0"},
	{"ID" : "108", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_user_V_U", "Parent" : "0"},
	{"ID" : "109", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_last_V_U", "Parent" : "0"},
	{"ID" : "110", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_id_V_U", "Parent" : "0"},
	{"ID" : "111", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_spikes_V_dest_V_U", "Parent" : "0"},
	{"ID" : "112", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_data_V_U", "Parent" : "0"},
	{"ID" : "113", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_keep_V_U", "Parent" : "0"},
	{"ID" : "114", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_strb_V_U", "Parent" : "0"},
	{"ID" : "115", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_user_V_U", "Parent" : "0"},
	{"ID" : "116", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_last_V_U", "Parent" : "0"},
	{"ID" : "117", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_id_V_U", "Parent" : "0"},
	{"ID" : "118", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_weights_V_dest_V_U", "Parent" : "0"}]}
