-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    lshr_ln : IN STD_LOGIC_VECTOR (6 downto 0);
    current_time : IN STD_LOGIC_VECTOR (15 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    pre_traces_trace_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pre_traces_trace_1_ce0 : OUT STD_LOGIC;
    pre_traces_trace_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    pre_traces_last_spike_time_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pre_traces_last_spike_time_1_ce0 : OUT STD_LOGIC;
    pre_traces_last_spike_time_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    pre_traces_trace_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pre_traces_trace_0_ce0 : OUT STD_LOGIC;
    pre_traces_trace_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    pre_traces_last_spike_time_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    pre_traces_last_spike_time_0_ce0 : OUT STD_LOGIC;
    pre_traces_last_spike_time_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZL13weight_memory_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal tmp_58_reg_634 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal EXP_DECAY_LUT_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_57_reg_616 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_58_fu_249_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_reg_634_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_reg_634_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln418_fu_257_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln418_reg_638 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln418_reg_638_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal lshr_ln1_fu_261_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln1_reg_643 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln1_reg_643_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln1_reg_643_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln418_fu_271_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln418_reg_648 : STD_LOGIC_VECTOR (63 downto 0);
    signal pre_t_trace_1_reg_668 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal dt_fu_289_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal dt_reg_674 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln321_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_reg_679 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_reg_679_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal dt_2_fu_310_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal dt_2_reg_684 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln321_2_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_2_reg_689 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln321_2_reg_689_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_fu_335_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_reg_704 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln325_fu_347_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln325_reg_709 : STD_LOGIC_VECTOR (15 downto 0);
    signal pre_t_trace_reg_714 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_addr_reg_725 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_addr_reg_725_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_addr_reg_731 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_addr_reg_731_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal pre_trace_val_1_fu_382_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pre_trace_val_1_reg_737 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln427_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln427_reg_742 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln427_reg_742_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_2_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln315_2_reg_746 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln325_2_fu_408_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln325_2_reg_751 : STD_LOGIC_VECTOR (15 downto 0);
    signal current_w_fu_414_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_reg_756 : STD_LOGIC_VECTOR (7 downto 0);
    signal distance_fu_421_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal distance_reg_762 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_addr_4_reg_767 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_addr_4_reg_773 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal pre_trace_val_3_fu_454_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pre_trace_val_3_reg_779 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln427_1_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln427_1_reg_784 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln427_1_reg_784_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln438_fu_497_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln438_reg_788 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_60_reg_793 : STD_LOGIC_VECTOR (2 downto 0);
    signal current_w_2_fu_518_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_2_reg_798 : STD_LOGIC_VECTOR (7 downto 0);
    signal distance_2_fu_525_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal distance_2_reg_804 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln438_2_fu_574_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln438_2_reg_809 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_62_reg_814 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln325_6_fu_331_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln325_9_fu_353_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal zext_ln430_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln430_1_fu_435_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_96 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln418_fu_278_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (8 downto 0);
    signal pre_traces_trace_0_ce0_local : STD_LOGIC;
    signal pre_traces_last_spike_time_0_ce0_local : STD_LOGIC;
    signal pre_traces_last_spike_time_1_ce0_local : STD_LOGIC;
    signal EXP_DECAY_LUT_ce0_local : STD_LOGIC;
    signal EXP_DECAY_LUT_address0_local : STD_LOGIC_VECTOR (3 downto 0);
    signal pre_traces_trace_1_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln335_fu_536_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_address1_local : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln335_2_fu_600_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_1_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_address0_local : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_d1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_1_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_address1_local : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_59_fu_294_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_61_fu_315_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln325_fu_347_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln325_fu_347_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_357_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln321_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pre_trace_val_fu_369_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln325_2_fu_408_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln325_2_fu_408_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_427_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln321_2_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pre_trace_val_2_fu_441_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln435_fu_477_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln435_fu_477_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln435_fu_477_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_483_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln435_4_fu_493_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln434_fu_468_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal w_fu_502_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln335_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal mul_ln435_1_fu_554_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln435_1_fu_554_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln435_1_fu_554_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_37_fu_560_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln435_5_fu_570_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln434_1_fu_545_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal w_2_fu_579_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln335_1_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter3_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln325_2_fu_408_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln325_2_fu_408_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln325_fu_347_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln325_fu_347_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln435_1_fu_554_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln435_1_fu_554_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln435_fu_477_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln435_fu_477_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP_EXP_DECAY_LUT_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    EXP_DECAY_LUT_U : component snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP_EXP_DECAY_LUT_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => EXP_DECAY_LUT_address0_local,
        ce0 => EXP_DECAY_LUT_ce0_local,
        q0 => EXP_DECAY_LUT_q0);

    mul_8ns_8ns_16_1_1_U116 : component snn_top_hls_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln325_fu_347_p0,
        din1 => mul_ln325_fu_347_p1,
        dout => mul_ln325_fu_347_p2);

    mul_8ns_8ns_16_1_1_U117 : component snn_top_hls_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln325_2_fu_408_p0,
        din1 => mul_ln325_2_fu_408_p1,
        dout => mul_ln325_2_fu_408_p2);

    mul_8ns_8ns_16_1_1_U118 : component snn_top_hls_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln435_fu_477_p0,
        din1 => mul_ln435_fu_477_p1,
        dout => mul_ln435_fu_477_p2);

    mul_8ns_8ns_16_1_1_U119 : component snn_top_hls_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln435_1_fu_554_p0,
        din1 => mul_ln435_1_fu_554_p1,
        dout => mul_ln435_1_fu_554_p2);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    i_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (tmp_58_fu_249_p3 = ap_const_lv1_0))) then 
                    i_fu_96 <= add_ln418_fu_278_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_96 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln438_2_reg_809 <= add_ln438_2_fu_574_p2;
                current_w_reg_756 <= current_w_fu_414_p3;
                distance_reg_762 <= distance_fu_421_p2;
                dt_2_reg_684 <= dt_2_fu_310_p2;
                dt_reg_674 <= dt_fu_289_p2;
                icmp_ln315_reg_704 <= icmp_ln315_fu_335_p2;
                icmp_ln321_2_reg_689 <= icmp_ln321_2_fu_325_p2;
                icmp_ln321_2_reg_689_pp0_iter1_reg <= icmp_ln321_2_reg_689;
                icmp_ln321_reg_679 <= icmp_ln321_fu_304_p2;
                icmp_ln321_reg_679_pp0_iter1_reg <= icmp_ln321_reg_679;
                icmp_ln427_1_reg_784 <= icmp_ln427_1_fu_462_p2;
                icmp_ln427_1_reg_784_pp0_iter3_reg <= icmp_ln427_1_reg_784;
                mul_ln325_reg_709 <= mul_ln325_fu_347_p2;
                    p_ZL13weight_memory_0_addr_4_reg_767(6 downto 0) <= zext_ln430_1_fu_435_p1(15 - 1 downto 0)(6 downto 0);    p_ZL13weight_memory_0_addr_4_reg_767(14 downto 8) <= zext_ln430_1_fu_435_p1(15 - 1 downto 0)(14 downto 8);
                    p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg(6 downto 0) <= p_ZL13weight_memory_0_addr_4_reg_767(6 downto 0);    p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg(14 downto 8) <= p_ZL13weight_memory_0_addr_4_reg_767(14 downto 8);
                    p_ZL13weight_memory_1_addr_4_reg_773(6 downto 0) <= zext_ln430_1_fu_435_p1(15 - 1 downto 0)(6 downto 0);    p_ZL13weight_memory_1_addr_4_reg_773(14 downto 8) <= zext_ln430_1_fu_435_p1(15 - 1 downto 0)(14 downto 8);
                    p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg(6 downto 0) <= p_ZL13weight_memory_1_addr_4_reg_773(6 downto 0);    p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg(14 downto 8) <= p_ZL13weight_memory_1_addr_4_reg_773(14 downto 8);
                pre_t_trace_1_reg_668 <= pre_traces_trace_0_q0;
                pre_t_trace_reg_714 <= pre_traces_trace_1_q0;
                pre_trace_val_3_reg_779 <= pre_trace_val_3_fu_454_p3;
                tmp_62_reg_814 <= w_2_fu_579_p2(9 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln438_reg_788 <= add_ln438_fu_497_p2;
                current_w_2_reg_798 <= current_w_2_fu_518_p3;
                distance_2_reg_804 <= distance_2_fu_525_p2;
                icmp_ln315_2_reg_746 <= icmp_ln315_2_fu_396_p2;
                icmp_ln427_reg_742 <= icmp_ln427_fu_390_p2;
                icmp_ln427_reg_742_pp0_iter3_reg <= icmp_ln427_reg_742;
                lshr_ln1_reg_643 <= ap_sig_allocacmp_i_5(7 downto 1);
                lshr_ln1_reg_643_pp0_iter1_reg <= lshr_ln1_reg_643;
                lshr_ln1_reg_643_pp0_iter2_reg <= lshr_ln1_reg_643_pp0_iter1_reg;
                mul_ln325_2_reg_751 <= mul_ln325_2_fu_408_p2;
                p_ZL13weight_memory_0_addr_reg_725 <= zext_ln430_fu_363_p1(15 - 1 downto 0);
                p_ZL13weight_memory_0_addr_reg_725_pp0_iter3_reg <= p_ZL13weight_memory_0_addr_reg_725;
                p_ZL13weight_memory_1_addr_reg_731 <= zext_ln430_fu_363_p1(15 - 1 downto 0);
                p_ZL13weight_memory_1_addr_reg_731_pp0_iter3_reg <= p_ZL13weight_memory_1_addr_reg_731;
                pre_trace_val_1_reg_737 <= pre_trace_val_1_fu_382_p3;
                tmp_58_reg_634 <= ap_sig_allocacmp_i_5(8 downto 8);
                tmp_58_reg_634_pp0_iter1_reg <= tmp_58_reg_634;
                tmp_58_reg_634_pp0_iter2_reg <= tmp_58_reg_634_pp0_iter1_reg;
                tmp_60_reg_793 <= w_fu_502_p2(9 downto 7);
                trunc_ln418_reg_638 <= trunc_ln418_fu_257_p1;
                trunc_ln418_reg_638_pp0_iter1_reg <= trunc_ln418_reg_638;
                    zext_ln418_reg_648(6 downto 0) <= zext_ln418_fu_271_p1(6 downto 0);
            end if;
        end if;
    end process;
    zext_ln418_reg_648(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";
    p_ZL13weight_memory_0_addr_4_reg_767(7) <= '1';
    p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg(7) <= '1';
    p_ZL13weight_memory_1_addr_4_reg_773(7) <= '1';
    p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg(7) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter3_stage0, ap_idle_pp0_0to2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to2 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter3_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    EXP_DECAY_LUT_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, zext_ln325_6_fu_331_p1, zext_ln325_9_fu_353_p1, ap_block_pp0_stage1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                EXP_DECAY_LUT_address0_local <= zext_ln325_9_fu_353_p1(4 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                EXP_DECAY_LUT_address0_local <= zext_ln325_6_fu_331_p1(4 - 1 downto 0);
            else 
                EXP_DECAY_LUT_address0_local <= "XXXX";
            end if;
        else 
            EXP_DECAY_LUT_address0_local <= "XXXX";
        end if; 
    end process;


    EXP_DECAY_LUT_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            EXP_DECAY_LUT_ce0_local <= ap_const_logic_1;
        else 
            EXP_DECAY_LUT_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln418_fu_278_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv9_2));
    add_ln438_2_fu_574_p2 <= std_logic_vector(unsigned(tmp_37_fu_560_p4) + unsigned(current_w_2_reg_798));
    add_ln438_fu_497_p2 <= std_logic_vector(unsigned(tmp_s_fu_483_p4) + unsigned(current_w_reg_756));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, tmp_58_reg_634)
    begin
        if (((tmp_58_reg_634 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter3_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, tmp_58_reg_634_pp0_iter2_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_58_reg_634_pp0_iter2_reg = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter3_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_96, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_96;
        end if; 
    end process;

    current_w_2_fu_518_p3 <= 
        p_ZL13weight_memory_1_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_q0;
    current_w_fu_414_p3 <= 
        p_ZL13weight_memory_1_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_q0;
    distance_2_fu_525_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(current_w_2_fu_518_p3));
    distance_fu_421_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(current_w_fu_414_p3));
    dt_2_fu_310_p2 <= std_logic_vector(unsigned(current_time) - unsigned(pre_traces_last_spike_time_1_q0));
    dt_fu_289_p2 <= std_logic_vector(unsigned(current_time) - unsigned(pre_traces_last_spike_time_0_q0));
    icmp_ln315_2_fu_396_p2 <= "1" when (pre_t_trace_reg_714 = ap_const_lv8_0) else "0";
    icmp_ln315_fu_335_p2 <= "1" when (pre_t_trace_1_reg_668 = ap_const_lv8_0) else "0";
    icmp_ln321_2_fu_325_p2 <= "0" when (tmp_61_fu_315_p4 = ap_const_lv12_0) else "1";
    icmp_ln321_fu_304_p2 <= "0" when (tmp_59_fu_294_p4 = ap_const_lv12_0) else "1";
    icmp_ln335_1_fu_595_p2 <= "1" when (signed(tmp_62_reg_814) > signed(ap_const_lv3_0)) else "0";
    icmp_ln335_fu_531_p2 <= "1" when (signed(tmp_60_reg_793) > signed(ap_const_lv3_0)) else "0";
    icmp_ln427_1_fu_462_p2 <= "1" when (pre_trace_val_3_fu_454_p3 = ap_const_lv8_0) else "0";
    icmp_ln427_fu_390_p2 <= "1" when (pre_trace_val_1_fu_382_p3 = ap_const_lv8_0) else "0";
    lshr_ln1_fu_261_p4 <= ap_sig_allocacmp_i_5(7 downto 1);
    mul_ln325_2_fu_408_p0 <= mul_ln325_2_fu_408_p00(8 - 1 downto 0);
    mul_ln325_2_fu_408_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(EXP_DECAY_LUT_q0),16));
    mul_ln325_2_fu_408_p1 <= mul_ln325_2_fu_408_p10(8 - 1 downto 0);
    mul_ln325_2_fu_408_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_t_trace_reg_714),16));
    mul_ln325_fu_347_p0 <= mul_ln325_fu_347_p00(8 - 1 downto 0);
    mul_ln325_fu_347_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(EXP_DECAY_LUT_q0),16));
    mul_ln325_fu_347_p1 <= mul_ln325_fu_347_p10(8 - 1 downto 0);
    mul_ln325_fu_347_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_t_trace_1_reg_668),16));
    mul_ln435_1_fu_554_p0 <= mul_ln435_1_fu_554_p00(8 - 1 downto 0);
    mul_ln435_1_fu_554_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(distance_2_reg_804),16));
    mul_ln435_1_fu_554_p1 <= mul_ln435_1_fu_554_p10(8 - 1 downto 0);
    mul_ln435_1_fu_554_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_trace_val_3_reg_779),16));
    mul_ln435_fu_477_p0 <= mul_ln435_fu_477_p00(8 - 1 downto 0);
    mul_ln435_fu_477_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(distance_reg_762),16));
    mul_ln435_fu_477_p1 <= mul_ln435_fu_477_p10(8 - 1 downto 0);
    mul_ln435_fu_477_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_trace_val_1_reg_737),16));
    or_ln321_2_fu_450_p2 <= (icmp_ln321_2_reg_689_pp0_iter1_reg or icmp_ln315_2_reg_746);
    or_ln321_fu_378_p2 <= (icmp_ln321_reg_679_pp0_iter1_reg or icmp_ln315_reg_704);
    p_ZL13weight_memory_0_address0 <= p_ZL13weight_memory_0_address0_local;

    p_ZL13weight_memory_0_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln430_fu_363_p1, zext_ln430_1_fu_435_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_ZL13weight_memory_0_address0_local <= zext_ln430_1_fu_435_p1(15 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_ZL13weight_memory_0_address0_local <= zext_ln430_fu_363_p1(15 - 1 downto 0);
            else 
                p_ZL13weight_memory_0_address0_local <= "XXXXXXXXXXXXXXX";
            end if;
        else 
            p_ZL13weight_memory_0_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_0_address1 <= p_ZL13weight_memory_0_address1_local;

    p_ZL13weight_memory_0_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, p_ZL13weight_memory_0_addr_reg_725_pp0_iter3_reg, p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL13weight_memory_0_address1_local <= p_ZL13weight_memory_0_addr_4_reg_767_pp0_iter3_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL13weight_memory_0_address1_local <= p_ZL13weight_memory_0_addr_reg_725_pp0_iter3_reg;
        else 
            p_ZL13weight_memory_0_address1_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_0_ce0 <= p_ZL13weight_memory_0_ce0_local;

    p_ZL13weight_memory_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL13weight_memory_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_ce1 <= p_ZL13weight_memory_0_ce1_local;

    p_ZL13weight_memory_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_d1 <= p_ZL13weight_memory_0_d1_local;

    p_ZL13weight_memory_0_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, select_ln335_fu_536_p3, select_ln335_2_fu_600_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL13weight_memory_0_d1_local <= select_ln335_2_fu_600_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL13weight_memory_0_d1_local <= select_ln335_fu_536_p3;
        else 
            p_ZL13weight_memory_0_d1_local <= "XXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_0_we1 <= p_ZL13weight_memory_0_we1_local;

    p_ZL13weight_memory_0_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, tmp_57_reg_616, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, icmp_ln427_reg_742_pp0_iter3_reg, icmp_ln427_1_reg_784_pp0_iter3_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln427_reg_742_pp0_iter3_reg = ap_const_lv1_0) and (tmp_57_reg_616 = ap_const_lv1_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln427_1_reg_784_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_57_reg_616 = ap_const_lv1_0)))) then 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_address0 <= p_ZL13weight_memory_1_address0_local;

    p_ZL13weight_memory_1_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln430_fu_363_p1, zext_ln430_1_fu_435_p1)
    begin
        if ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                p_ZL13weight_memory_1_address0_local <= zext_ln430_1_fu_435_p1(15 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                p_ZL13weight_memory_1_address0_local <= zext_ln430_fu_363_p1(15 - 1 downto 0);
            else 
                p_ZL13weight_memory_1_address0_local <= "XXXXXXXXXXXXXXX";
            end if;
        else 
            p_ZL13weight_memory_1_address0_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_1_address1 <= p_ZL13weight_memory_1_address1_local;

    p_ZL13weight_memory_1_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, p_ZL13weight_memory_1_addr_reg_731_pp0_iter3_reg, p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg, ap_block_pp0_stage0, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL13weight_memory_1_address1_local <= p_ZL13weight_memory_1_addr_4_reg_773_pp0_iter3_reg;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL13weight_memory_1_address1_local <= p_ZL13weight_memory_1_addr_reg_731_pp0_iter3_reg;
        else 
            p_ZL13weight_memory_1_address1_local <= "XXXXXXXXXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_1_ce0 <= p_ZL13weight_memory_1_ce0_local;

    p_ZL13weight_memory_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL13weight_memory_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_ce1 <= p_ZL13weight_memory_1_ce1_local;

    p_ZL13weight_memory_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_d1 <= p_ZL13weight_memory_1_d1_local;

    p_ZL13weight_memory_1_d1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0, ap_block_pp0_stage1, select_ln335_fu_536_p3, select_ln335_2_fu_600_p3)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL13weight_memory_1_d1_local <= select_ln335_2_fu_600_p3;
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            p_ZL13weight_memory_1_d1_local <= select_ln335_fu_536_p3;
        else 
            p_ZL13weight_memory_1_d1_local <= "XXXXXXXX";
        end if; 
    end process;

    p_ZL13weight_memory_1_we1 <= p_ZL13weight_memory_1_we1_local;

    p_ZL13weight_memory_1_we1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage1, tmp_57_reg_616, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, icmp_ln427_reg_742_pp0_iter3_reg, icmp_ln427_1_reg_784_pp0_iter3_reg)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln427_reg_742_pp0_iter3_reg = ap_const_lv1_0) and (tmp_57_reg_616 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln427_1_reg_784_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_57_reg_616 = ap_const_lv1_1)))) then 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pre_trace_val_1_fu_382_p3 <= 
        ap_const_lv8_0 when (or_ln321_fu_378_p2(0) = '1') else 
        pre_trace_val_fu_369_p4;
    pre_trace_val_2_fu_441_p4 <= mul_ln325_2_reg_751(15 downto 8);
    pre_trace_val_3_fu_454_p3 <= 
        ap_const_lv8_0 when (or_ln321_2_fu_450_p2(0) = '1') else 
        pre_trace_val_2_fu_441_p4;
    pre_trace_val_fu_369_p4 <= mul_ln325_reg_709(15 downto 8);
    pre_traces_last_spike_time_0_address0 <= zext_ln418_fu_271_p1(7 - 1 downto 0);
    pre_traces_last_spike_time_0_ce0 <= pre_traces_last_spike_time_0_ce0_local;

    pre_traces_last_spike_time_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pre_traces_last_spike_time_0_ce0_local <= ap_const_logic_1;
        else 
            pre_traces_last_spike_time_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pre_traces_last_spike_time_1_address0 <= zext_ln418_fu_271_p1(7 - 1 downto 0);
    pre_traces_last_spike_time_1_ce0 <= pre_traces_last_spike_time_1_ce0_local;

    pre_traces_last_spike_time_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pre_traces_last_spike_time_1_ce0_local <= ap_const_logic_1;
        else 
            pre_traces_last_spike_time_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pre_traces_trace_0_address0 <= zext_ln418_fu_271_p1(7 - 1 downto 0);
    pre_traces_trace_0_ce0 <= pre_traces_trace_0_ce0_local;

    pre_traces_trace_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pre_traces_trace_0_ce0_local <= ap_const_logic_1;
        else 
            pre_traces_trace_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pre_traces_trace_1_address0 <= zext_ln418_reg_648(7 - 1 downto 0);
    pre_traces_trace_1_ce0 <= pre_traces_trace_1_ce0_local;

    pre_traces_trace_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pre_traces_trace_1_ce0_local <= ap_const_logic_1;
        else 
            pre_traces_trace_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln335_2_fu_600_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_1_fu_595_p2(0) = '1') else 
        add_ln438_2_reg_809;
    select_ln335_fu_536_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_fu_531_p2(0) = '1') else 
        add_ln438_reg_788;
        sext_ln434_1_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_2_reg_798),10));

        sext_ln434_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_reg_756),10));

    tmp_36_fu_427_p4 <= ((lshr_ln1_reg_643_pp0_iter2_reg & ap_const_lv1_1) & lshr_ln);
    tmp_37_fu_560_p4 <= mul_ln435_1_fu_554_p2(15 downto 8);
    tmp_57_reg_616 <= empty;
    tmp_58_fu_249_p3 <= ap_sig_allocacmp_i_5(8 downto 8);
    tmp_59_fu_294_p4 <= dt_fu_289_p2(15 downto 4);
    tmp_61_fu_315_p4 <= dt_2_fu_310_p2(15 downto 4);
    tmp_fu_357_p3 <= (trunc_ln418_reg_638_pp0_iter1_reg & lshr_ln);
    tmp_s_fu_483_p4 <= mul_ln435_fu_477_p2(15 downto 8);
    trunc_ln418_fu_257_p1 <= ap_sig_allocacmp_i_5(8 - 1 downto 0);
    w_2_fu_579_p2 <= std_logic_vector(unsigned(zext_ln435_5_fu_570_p1) + unsigned(sext_ln434_1_fu_545_p1));
    w_fu_502_p2 <= std_logic_vector(unsigned(zext_ln435_4_fu_493_p1) + unsigned(sext_ln434_fu_468_p1));
    zext_ln325_6_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dt_reg_674),64));
    zext_ln325_9_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(dt_2_reg_684),64));
    zext_ln418_fu_271_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_261_p4),64));
    zext_ln430_1_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_427_p4),64));
    zext_ln430_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_357_p3),64));
    zext_ln435_4_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_483_p4),10));
    zext_ln435_5_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_560_p4),10));
end behav;
