#!/usr/bin/env python3
"""
prepare_cnn3_deployment.py
==========================
Prepares deployment payload for 3-layer Convolutional SNN (CNN3) on PYNQ-Z2 FPGA.
Supports dynamic threshold calibration, automatic normalization detection,
automatic bias detection, and hardware-faithful event-driven emulation.

Model Architecture:
  - Layer 1 (CPU Host): Conv2d(1->8, 3x3) -> LIF (v_th=1.0) -> AvgPool2d(2x2) [Float32]
  - Layer 2 (FPGA Grp 1): Conv2d(8->16, 3x3) -> LIF -> AvgPool2d(2x2)          [Int8]
  - Layer 3 (FPGA Grp 2): Linear(784->10) -> LIF                               [Int8]
"""

import os
import sys
import argparse
import numpy as np
import torch
import torch.nn as nn

def fuse_batchnorm_conv(w, b, bn_gamma, bn_beta, bn_mean, bn_var, eps=1e-5):
    """Fold 2D BatchNorm parameters into Conv2d weights and biases."""
    std = torch.sqrt(bn_var + eps)
    w_fused = w * (bn_gamma / std).view(-1, 1, 1, 1)
    if b is None:
        b = torch.zeros(w.size(0))
    if bn_beta is not None:
        b_fused = (b - bn_mean) * (bn_gamma / std) + bn_beta
    else:
        b_fused = (b - bn_mean) * (bn_gamma / std)
    return w_fused.numpy(), b_fused.numpy()


def export_hls_weights_header(w1_f, b1_f, q_conv2_int, header_path):
    """
    Auto-generate C++ header containing Conv1 float weights/biases and
    Conv2 int8 weights for HLS Streaming 2D Convolution Engine.
    """
    os.makedirs(os.path.dirname(os.path.abspath(header_path)), exist_ok=True)
    with open(header_path, 'w') as f:
        f.write("// Auto-generated CNN3 weights for HLS Streaming Engine\n")
        f.write("// Generated by tests/prepare_cnn3_deployment.py\n")
        f.write("#ifndef CNN3_WEIGHTS_H\n")
        f.write("#define CNN3_WEIGHTS_H\n\n")

        # CONV1_WEIGHTS [8][3][3]
        f.write(f"static const float CONV1_WEIGHTS[{w1_f.shape[0]}][{w1_f.shape[2]}][{w1_f.shape[3]}] = {{\n")
        for co in range(w1_f.shape[0]):
            f.write(f"    {{ // Channel {co}\n")
            for dy in range(w1_f.shape[2]):
                row = ", ".join([f"{w1_f[co, 0, dy, dx]:.6f}f" for dx in range(w1_f.shape[3])])
                f.write(f"        {{ {row} }},\n")
            f.write("    },\n")
        f.write("};\n\n")

        # CONV1_BIAS [8]
        f.write(f"static const float CONV1_BIAS[{b1_f.shape[0]}] = {{\n    ")
        f.write(", ".join([f"{b:.6f}f" for b in b1_f]))
        f.write("\n};\n\n")

        # CONV2_WEIGHTS [16][8][3][3]
        # Divide by 4 to account for AvgPool2d(2, 2) scale factor (0.25) in event-driven streaming
        q_conv2_div4 = np.clip(np.round(q_conv2_int.astype(np.float32) / 4.0), -127, 127).astype(np.int8)
        f.write(f"static const signed char CONV2_WEIGHTS[{q_conv2_int.shape[0]}][{q_conv2_int.shape[1]}][{q_conv2_int.shape[2]}][{q_conv2_int.shape[3]}] = {{\n")
        for co in range(q_conv2_int.shape[0]):
            f.write(f"    {{ // Out Channel {co}\n")
            for ci in range(q_conv2_int.shape[1]):
                f.write(f"        {{ // In Channel {ci}\n")
                for dy in range(q_conv2_int.shape[2]):
                    row = ", ".join([f"{q_conv2_div4[co, ci, dy, dx]:4d}" for dx in range(q_conv2_int.shape[3])])
                    f.write(f"            {{ {row} }},\n")
                f.write("        },\n")
            f.write("    },\n")
        f.write("};\n\n")

        f.write("#endif // CNN3_WEIGHTS_H\n")
    print(f"Auto-generated HLS C++ weights header: {header_path}")



def parse_args():
    parser = argparse.ArgumentParser(description="Prepare CNN3 SNN Deployment Payload for FPGA")
    parser.add_argument('--model', default='models/cnn3_T_4_clean_l2[0.000500].pth',
                        help='Path to PyTorch .pth model checkpoint')
    parser.add_argument('--output', default='data/cache/mnist_cnn3_deployment.npz',
                        help='Output deployment payload path')
    parser.add_argument('--hls-header', default='hardware/hls/include/cnn3_weights.h',
                        help='Path to output auto-generated HLS weights C++ header')
    parser.add_argument('--timesteps', type=int, default=4,
                        help='Number of SNN timesteps (default: 4)')
    parser.add_argument('--normalization', choices=['auto', 'zscore', 'raw'], default='auto',
                        help='Input normalization strategy (default: auto)')
    parser.add_argument('--samples', type=int, default=1000,
                        help='Number of validation images for threshold calibration (default: 1000)')
    return parser.parse_args()


def main():
    args = parse_args()
    MODEL_PATH = args.model
    OUTPUT_PATH = args.output
    TIMESTEPS = args.timesteps

    # ─────────────────────────────────────────────────────────────────
    # 1. Load Model Checkpoint & Extract Parameters
    # ─────────────────────────────────────────────────────────────────
    print(f"Loading PyTorch CNN3 model: {MODEL_PATH}")
    if not os.path.exists(MODEL_PATH):
        print(f"ERROR: Model file not found: {MODEL_PATH}")
        sys.exit(1)

    state_dict = torch.load(MODEL_PATH, map_location='cpu')

    # Layer 1 (Conv1): features.0
    if 'features.1.running_var' in state_dict and 'features.1.weight' in state_dict:
        print("  Layer 1: Fusing BatchNorm into Conv1...")
        w1_f, b1_f = fuse_batchnorm_conv(
            state_dict['features.0.weight'],
            state_dict.get('features.0.bias', None),
            state_dict['features.1.weight'],
            state_dict.get('features.1.bias', None),
            state_dict['features.1.running_mean'],
            state_dict['features.1.running_var']
        )
    else:
        w1_f = state_dict['features.0.weight'].numpy()
        b1_f = state_dict['features.0.bias'].numpy() if 'features.0.bias' in state_dict else np.zeros(w1_f.shape[0], dtype=np.float32)

    # Layer 2 (Conv2): features.3 (or features.2 if no pool)
    conv2_w_key = 'features.3.weight' if 'features.3.weight' in state_dict else 'features.2.weight'
    conv2_b_key = 'features.3.bias' if 'features.3.bias' in state_dict else 'features.2.bias'
    w2_f = state_dict[conv2_w_key].numpy()
    b2_f = state_dict[conv2_b_key].numpy() if conv2_b_key in state_dict else np.zeros(w2_f.shape[0], dtype=np.float32)

    # Layer 3 (Classifier): classifier
    w3_f = state_dict['classifier.weight'].numpy()
    b3_f = state_dict['classifier.bias'].numpy() if 'classifier.bias' in state_dict else np.zeros(w3_f.shape[0], dtype=np.float32)

    has_biases = not (np.all(b1_f == 0) and np.all(b2_f == 0) and np.all(b3_f == 0))
    print(f"Model Biases Detected: {'Yes (fused/explicit)' if has_biases else 'No (bias=False / zero bias)'}")
    print(f"  Layer 1 (Conv1) shape: {w1_f.shape} (Input 1 -> {w1_f.shape[0]} Output Channels, 3x3)")
    print(f"  Layer 2 (Conv2) shape: {w2_f.shape} (Channels {w2_f.shape[1]} -> {w2_f.shape[0]}, 3x3)")
    print(f"  Layer 3 (Linear) shape: {w3_f.shape} (Flattened {w3_f.shape[1]} -> {w3_f.shape[0]} Classes)")

    # ─────────────────────────────────────────────────────────────────
    # 2. Dataset Loading & Auto-Detection of Normalization
    # ─────────────────────────────────────────────────────────────────
    try:
        from torchvision import datasets, transforms
    except ImportError:
        print("ERROR: torchvision is required to load MNIST dataset.")
        sys.exit(1)

    print("\nLoading MNIST Test Dataset...")
    raw_ds = datasets.MNIST('./data', train=False, download=True, transform=transforms.ToTensor())
    zscore_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])
    zscore_ds = datasets.MNIST('./data', train=False, download=False, transform=zscore_transform)

    # Auto-detect normalization via probe if requested
    if args.normalization == 'auto':
        probe_loader_z = torch.utils.data.DataLoader(zscore_ds, batch_size=100, shuffle=False)
        probe_loader_r = torch.utils.data.DataLoader(raw_ds, batch_size=100, shuffle=False)
        imgs_z, lbls_z = next(iter(probe_loader_z))
        imgs_r, lbls_r = next(iter(probe_loader_r))

        conv1_t = nn.Conv2d(1, w1_f.shape[0], 3, padding=1)
        conv1_t.weight.data = torch.from_numpy(w1_f)
        conv1_t.bias.data = torch.from_numpy(b1_f)
        pool1_t = nn.AvgPool2d(2, 2)
        conv2_t = nn.Conv2d(w2_f.shape[1], w2_f.shape[0], 3, padding=1)
        conv2_t.weight.data = torch.from_numpy(w2_f)
        conv2_t.bias.data = torch.from_numpy(b2_f)
        pool2_t = nn.AvgPool2d(2, 2)
        fc_t = nn.Linear(w3_f.shape[1], w3_f.shape[0])
        fc_t.weight.data = torch.from_numpy(w3_f)
        fc_t.bias.data = torch.from_numpy(b3_f)

        def eval_probe(imgs, lbls):
            v1 = torch.zeros(100, w1_f.shape[0], 28, 28)
            v2 = torch.zeros(100, w2_f.shape[0], 14, 14)
            out_v = torch.zeros(100, 10)
            cur1 = conv1_t(imgs)
            for t in range(TIMESTEPS):
                v1 += cur1
                s1 = (v1 >= 1.0).float()
                v1 -= s1 * 1.0
                p1 = pool1_t(s1)
                cur2 = conv2_t(p1)
                v2 += cur2
                s2 = (v2 >= 1.0).float()
                v2 -= s2 * 1.0
                p2 = pool2_t(s2)
                out_v += fc_t(p2.view(100, -1))
            return (out_v.argmax(dim=1) == lbls).float().mean().item()

        with torch.no_grad():
            acc_z = eval_probe(imgs_z, lbls_z)
            acc_r = eval_probe(imgs_r, lbls_r)

        if acc_z >= acc_r:
            selected_norm = 'zscore'
            print(f"Auto-Detected Normalization: Z-Score Normalized (Probe Acc: Z={acc_z*100:.1f}% vs Raw={acc_r*100:.1f}%)")
        else:
            selected_norm = 'raw'
            print(f"Auto-Detected Normalization: Raw [0, 1] Intensities (Probe Acc: Raw={acc_r*100:.1f}% vs Z={acc_z*100:.1f}%)")
    else:
        selected_norm = args.normalization
        print(f"Using Specified Normalization: {selected_norm}")

    active_ds = zscore_ds if selected_norm == 'zscore' else raw_ds
    test_imgs = np.stack([img.squeeze(0).numpy() for img, _ in active_ds])
    test_lbls = np.array([lbl for _, lbl in active_ds], dtype=np.int64)
    print(f"  Loaded {len(test_imgs)} MNIST test images, shape: {test_imgs.shape}")

    # ─────────────────────────────────────────────────────────────────
    # 3. Dynamic Weight Scaling for FPGA Layers (Layer 2 & Layer 3)
    # ─────────────────────────────────────────────────────────────────
    # Layer 1 stays Float32 on the CPU.
    # Conv2 is scaled to utilize the full signed Int8 dynamic range [-127, 127].
    max_abs_conv2 = np.max(np.abs(w2_f))
    max_abs_fc = np.max(np.abs(w3_f))
    SCALE2 = 127.0 / max_abs_conv2
    base_th = max(1, int(round(SCALE2)))
    print(f"\nFPGA Layer 2 Dynamic Weight Scale: {SCALE2:.2f} (Base Threshold = {base_th})")

    # ─────────────────────────────────────────────────────────────────
    # 4. Hardware-Faithful Sequential Calibration Sweep
    # ─────────────────────────────────────────────────────────────────
    # Calibrates both the shared FPGA hardware threshold and Layer 3 relative
    # scale so that both Layer 2 and Layer 3 operate with peak accuracy and
    # safe spike counts (< 250 spikes/img) to prevent DMA overflow.
    print(f"\nRunning Hardware-Faithful Sequential Calibration Sweep...")

    N_CHECK = min(args.samples, len(test_imgs))
    val_imgs_t = torch.from_numpy(test_imgs[:N_CHECK]).unsqueeze(1).float()
    val_lbls_t = torch.from_numpy(test_lbls[:N_CHECK]).long()

    # PyTorch modules for CPU Layer 1 evaluation
    conv1 = nn.Conv2d(1, w1_f.shape[0], 3, padding=1)
    conv1.weight.data = torch.from_numpy(w1_f)
    conv1.bias.data = torch.from_numpy(b1_f)
    pool1 = nn.AvgPool2d(2, 2)
    pool2 = nn.AvgPool2d(2, 2)

    # Precompute Layer 1 analog drive cur1
    with torch.no_grad():
        cur1_val = conv1(val_imgs_t)

    # Candidate multipliers for hardware threshold
    th_multipliers = [0.35, 0.45, 0.50, 0.55, 0.65, 0.75, 0.90]
    candidate_ths = sorted(list(set([max(1, int(round(base_th * m))) for m in th_multipliers])))
    # Candidate relative scale ratios for Layer 3 (Classifier)
    scale3_ratios = [0.08, 0.10, 0.12, 0.15, 0.18]

    best_acc = 0.0
    best_th = base_th
    best_scale3_ratio = 0.12

    q_conv2_t = torch.from_numpy(np.clip(np.round(w2_f * SCALE2), -127, 127).astype(np.float32))

    for test_th in candidate_ths:
        for s3_ratio in scale3_ratios:
            SCALE3_cand = s3_ratio * (127.0 / max_abs_fc)
            q_fc_cand_t = torch.from_numpy(np.clip(np.round(w3_f * SCALE3_cand), -127, 127).astype(np.float32))

            v1 = torch.zeros(N_CHECK, w1_f.shape[0], 28, 28)
            v2 = torch.zeros(N_CHECK, w2_f.shape[0], 14, 14)
            v3 = torch.zeros(N_CHECK, 10)
            spk3 = torch.zeros(N_CHECK, 10)

            with torch.no_grad():
                for t in range(TIMESTEPS):
                    # Layer 1 (CPU): Float32 LIF
                    v1 += cur1_val
                    s1 = (v1 >= 1.0).float()
                    v1 -= s1 * 1.0

                    p1 = pool1(s1)
                    # Layer 2 (FPGA): Conv2 Int8 + LIF hard reset
                    cur2 = nn.functional.conv2d(p1, q_conv2_t, padding=1)
                    v2 += cur2
                    s2 = (v2 >= test_th).float()
                    v2 -= s2 * test_th

                    # Layer 3 (FPGA): AvgPool2 + Linear Int8 + LIF hard reset
                    p2 = pool2(s2)
                    cur3 = nn.functional.linear(p2.view(N_CHECK, -1), q_fc_cand_t)
                    v3 += cur3
                    v3 = torch.clamp(v3, min=0)
                    s3 = (v3 >= test_th).float()
                    v3 = v3 * (1.0 - s3)
                    spk3 += s3

                pred = spk3.argmax(dim=1)
                no_spk = (spk3.sum(dim=1) == 0)
                pred[no_spk] = v3[no_spk].argmax(dim=1)
                acc = (pred == val_lbls_t).float().mean().item() * 100
                avg_spk = spk3.sum().item() / N_CHECK

            print(f"  TH={test_th:3d} (m={test_th/base_th:.2f}) | S3_Ratio={s3_ratio:.2f} | Acc: {acc:.2f}% | Avg Spk/Img: {avg_spk:.1f}")

            if avg_spk < 250 and acc > best_acc:
                best_acc = acc
                best_th = test_th
                best_scale3_ratio = s3_ratio

    print(f"\nOptimal Calibrated Hardware Parameters:")
    print(f"  Hardware Shared Threshold: {best_th}")
    print(f"  Layer 3 Relative Scale Ratio: {best_scale3_ratio:.2f} (Validation Acc: {best_acc:.2f}%)")

    # ─────────────────────────────────────────────────────────────────
    # 5. Full 10,000 Image Test Set Validation
    # ─────────────────────────────────────────────────────────────────
    print(f"\nValidating on full test set ({len(test_imgs)} images)...")
    final_scale3 = best_scale3_ratio * (127.0 / max_abs_fc)
    q_conv2_int = np.clip(np.round(w2_f * SCALE2), -127, 127).astype(np.int8)
    q_fc_int = np.clip(np.round(w3_f * final_scale3), -127, 127).astype(np.int8)

    q_conv2_final_t = torch.from_numpy(q_conv2_int.astype(np.float32))
    q_fc_final_t = torch.from_numpy(q_fc_int.astype(np.float32))

    eval_loader = torch.utils.data.DataLoader(active_ds, batch_size=500, shuffle=False)
    correct_full = 0
    total_spikes_full = 0
    total_samples = 0

    with torch.no_grad():
        for b_imgs, b_lbls in eval_loader:
            B = b_imgs.size(0)
            v1 = torch.zeros(B, w1_f.shape[0], 28, 28)
            v2 = torch.zeros(B, w2_f.shape[0], 14, 14)
            v3 = torch.zeros(B, 10)
            spk3 = torch.zeros(B, 10)

            cur1_b = conv1(b_imgs)
            for t in range(TIMESTEPS):
                v1 += cur1_b
                s1 = (v1 >= 1.0).float()
                v1 -= s1 * 1.0

                p1 = pool1(s1)
                cur2 = nn.functional.conv2d(p1, q_conv2_final_t, padding=1)
                v2 += cur2
                s2 = (v2 >= best_th).float()
                v2 -= s2 * best_th

                p2 = pool2(s2)
                cur3 = nn.functional.linear(p2.view(B, -1), q_fc_final_t)
                v3 += cur3
                v3 = torch.clamp(v3, min=0)
                s3 = (v3 >= best_th).float()
                v3 = v3 * (1.0 - s3)
                spk3 += s3

            pred = spk3.argmax(dim=1)
            no_spk = (spk3.sum(dim=1) == 0)
            pred[no_spk] = v3[no_spk].argmax(dim=1)
            correct_full += (pred == b_lbls).sum().item()
            total_samples += B
            total_spikes_full += spk3.sum().item()

    full_acc = correct_full / total_samples * 100
    avg_spikes = total_spikes_full / total_samples
    print(f"Full Test Set Accuracy: {full_acc:.2f}% ({correct_full}/{total_samples}) | Avg Spikes/Img: {avg_spikes:.1f}")

    # ─────────────────────────────────────────────────────────────────
    # 6. Save Deployment Payload
    # ─────────────────────────────────────────────────────────────────
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    np.savez_compressed(
        OUTPUT_PATH,
        # CPU Payload (Layer 1)
        w1_f=w1_f,
        b1_f=b1_f,
        # FPGA Quantized Payload (Layer 2 & Layer 3)
        q_conv2_w=np.clip(np.round(q_conv2_int.astype(np.float32) / 4.0), -127, 127).astype(np.int8),
        q_conv2_b=np.clip(np.round(b2_f * SCALE2), -127, 127).astype(np.int8),
        q_fc_w=q_fc_int,
        q_fc_b=np.clip(np.round(b3_f * final_scale3), -127, 127).astype(np.int8),
        # Test Data & Ground Truth
        test_imgs=test_imgs,
        test_lbls=test_lbls,
        # Hardware Parameters & Metadata
        hw_threshold=np.array(best_th, dtype=np.int32),
        scale2=np.array(SCALE2, dtype=np.float32),
        scale3=np.array(final_scale3, dtype=np.float32),
        normalization=np.array(selected_norm),
        timesteps=np.array(TIMESTEPS, dtype=np.int32)
    )
    print(f"\nSaved CNN3 Deployment Payload: {OUTPUT_PATH}")

    # ─────────────────────────────────────────────────────────────────
    # 7. Export HLS C++ Weights Header (for All-on-FPGA Layer 1 Engine)
    # ─────────────────────────────────────────────────────────────────
    export_hls_weights_header(w1_f, b1_f, q_conv2_int, args.hls_header)



if __name__ == '__main__':
    main()

