// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_RESET_ELIG (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL15pre_eligibility_0_address1,
        p_ZL15pre_eligibility_0_ce1,
        p_ZL15pre_eligibility_0_we1,
        p_ZL15pre_eligibility_0_d1,
        p_ZL16post_eligibility_0_address1,
        p_ZL16post_eligibility_0_ce1,
        p_ZL16post_eligibility_0_we1,
        p_ZL16post_eligibility_0_d1,
        p_ZL15pre_eligibility_1_address1,
        p_ZL15pre_eligibility_1_ce1,
        p_ZL15pre_eligibility_1_we1,
        p_ZL15pre_eligibility_1_d1,
        p_ZL16post_eligibility_1_address1,
        p_ZL16post_eligibility_1_ce1,
        p_ZL16post_eligibility_1_we1,
        p_ZL16post_eligibility_1_d1,
        p_ZL15pre_eligibility_2_address1,
        p_ZL15pre_eligibility_2_ce1,
        p_ZL15pre_eligibility_2_we1,
        p_ZL15pre_eligibility_2_d1,
        p_ZL16post_eligibility_2_address1,
        p_ZL16post_eligibility_2_ce1,
        p_ZL16post_eligibility_2_we1,
        p_ZL16post_eligibility_2_d1,
        p_ZL15pre_eligibility_3_address1,
        p_ZL15pre_eligibility_3_ce1,
        p_ZL15pre_eligibility_3_we1,
        p_ZL15pre_eligibility_3_d1,
        p_ZL16post_eligibility_3_address1,
        p_ZL16post_eligibility_3_ce1,
        p_ZL16post_eligibility_3_we1,
        p_ZL16post_eligibility_3_d1
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] p_ZL15pre_eligibility_0_address1;
output   p_ZL15pre_eligibility_0_ce1;
output   p_ZL15pre_eligibility_0_we1;
output  [7:0] p_ZL15pre_eligibility_0_d1;
output  [6:0] p_ZL16post_eligibility_0_address1;
output   p_ZL16post_eligibility_0_ce1;
output   p_ZL16post_eligibility_0_we1;
output  [7:0] p_ZL16post_eligibility_0_d1;
output  [6:0] p_ZL15pre_eligibility_1_address1;
output   p_ZL15pre_eligibility_1_ce1;
output   p_ZL15pre_eligibility_1_we1;
output  [7:0] p_ZL15pre_eligibility_1_d1;
output  [6:0] p_ZL16post_eligibility_1_address1;
output   p_ZL16post_eligibility_1_ce1;
output   p_ZL16post_eligibility_1_we1;
output  [7:0] p_ZL16post_eligibility_1_d1;
output  [6:0] p_ZL15pre_eligibility_2_address1;
output   p_ZL15pre_eligibility_2_ce1;
output   p_ZL15pre_eligibility_2_we1;
output  [7:0] p_ZL15pre_eligibility_2_d1;
output  [6:0] p_ZL16post_eligibility_2_address1;
output   p_ZL16post_eligibility_2_ce1;
output   p_ZL16post_eligibility_2_we1;
output  [7:0] p_ZL16post_eligibility_2_d1;
output  [6:0] p_ZL15pre_eligibility_3_address1;
output   p_ZL15pre_eligibility_3_ce1;
output   p_ZL15pre_eligibility_3_we1;
output  [7:0] p_ZL15pre_eligibility_3_d1;
output  [6:0] p_ZL16post_eligibility_3_address1;
output   p_ZL16post_eligibility_3_ce1;
output   p_ZL16post_eligibility_3_we1;
output  [7:0] p_ZL16post_eligibility_3_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln725_fu_222_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln727_fu_248_p1;
reg   [9:0] i_fu_66;
wire   [9:0] add_ln725_fu_228_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_3;
reg    p_ZL15pre_eligibility_2_we1_local;
wire   [1:0] trunc_ln725_fu_234_p1;
reg    p_ZL15pre_eligibility_2_ce1_local;
reg    p_ZL16post_eligibility_2_we1_local;
reg    p_ZL16post_eligibility_2_ce1_local;
reg    p_ZL15pre_eligibility_1_we1_local;
reg    p_ZL15pre_eligibility_1_ce1_local;
reg    p_ZL16post_eligibility_1_we1_local;
reg    p_ZL16post_eligibility_1_ce1_local;
reg    p_ZL15pre_eligibility_0_we1_local;
reg    p_ZL15pre_eligibility_0_ce1_local;
reg    p_ZL16post_eligibility_0_we1_local;
reg    p_ZL16post_eligibility_0_ce1_local;
reg    p_ZL15pre_eligibility_3_we1_local;
reg    p_ZL15pre_eligibility_3_ce1_local;
reg    p_ZL16post_eligibility_3_we1_local;
reg    p_ZL16post_eligibility_3_ce1_local;
wire   [6:0] lshr_ln_fu_238_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 i_fu_66 = 10'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln725_fu_222_p2 == 1'd0)) begin
            i_fu_66 <= add_ln725_fu_228_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 10'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_eligibility_0_ce1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd0))) begin
        p_ZL15pre_eligibility_0_we1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_eligibility_1_ce1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd1))) begin
        p_ZL15pre_eligibility_1_we1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_eligibility_2_ce1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd2))) begin
        p_ZL15pre_eligibility_2_we1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL15pre_eligibility_3_ce1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd3))) begin
        p_ZL15pre_eligibility_3_we1_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_eligibility_0_ce1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd0))) begin
        p_ZL16post_eligibility_0_we1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_eligibility_1_ce1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd1))) begin
        p_ZL16post_eligibility_1_we1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_eligibility_2_ce1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd2))) begin
        p_ZL16post_eligibility_2_we1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZL16post_eligibility_3_ce1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln725_fu_222_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (trunc_ln725_fu_234_p1 == 2'd3))) begin
        p_ZL16post_eligibility_3_we1_local = 1'b1;
    end else begin
        p_ZL16post_eligibility_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln725_fu_228_p2 = (ap_sig_allocacmp_i_3 + 10'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln725_fu_222_p2 = ((ap_sig_allocacmp_i_3 == 10'd512) ? 1'b1 : 1'b0);

assign lshr_ln_fu_238_p4 = {{ap_sig_allocacmp_i_3[8:2]}};

assign p_ZL15pre_eligibility_0_address1 = zext_ln727_fu_248_p1;

assign p_ZL15pre_eligibility_0_ce1 = p_ZL15pre_eligibility_0_ce1_local;

assign p_ZL15pre_eligibility_0_d1 = 8'd0;

assign p_ZL15pre_eligibility_0_we1 = p_ZL15pre_eligibility_0_we1_local;

assign p_ZL15pre_eligibility_1_address1 = zext_ln727_fu_248_p1;

assign p_ZL15pre_eligibility_1_ce1 = p_ZL15pre_eligibility_1_ce1_local;

assign p_ZL15pre_eligibility_1_d1 = 8'd0;

assign p_ZL15pre_eligibility_1_we1 = p_ZL15pre_eligibility_1_we1_local;

assign p_ZL15pre_eligibility_2_address1 = zext_ln727_fu_248_p1;

assign p_ZL15pre_eligibility_2_ce1 = p_ZL15pre_eligibility_2_ce1_local;

assign p_ZL15pre_eligibility_2_d1 = 8'd0;

assign p_ZL15pre_eligibility_2_we1 = p_ZL15pre_eligibility_2_we1_local;

assign p_ZL15pre_eligibility_3_address1 = zext_ln727_fu_248_p1;

assign p_ZL15pre_eligibility_3_ce1 = p_ZL15pre_eligibility_3_ce1_local;

assign p_ZL15pre_eligibility_3_d1 = 8'd0;

assign p_ZL15pre_eligibility_3_we1 = p_ZL15pre_eligibility_3_we1_local;

assign p_ZL16post_eligibility_0_address1 = zext_ln727_fu_248_p1;

assign p_ZL16post_eligibility_0_ce1 = p_ZL16post_eligibility_0_ce1_local;

assign p_ZL16post_eligibility_0_d1 = 8'd0;

assign p_ZL16post_eligibility_0_we1 = p_ZL16post_eligibility_0_we1_local;

assign p_ZL16post_eligibility_1_address1 = zext_ln727_fu_248_p1;

assign p_ZL16post_eligibility_1_ce1 = p_ZL16post_eligibility_1_ce1_local;

assign p_ZL16post_eligibility_1_d1 = 8'd0;

assign p_ZL16post_eligibility_1_we1 = p_ZL16post_eligibility_1_we1_local;

assign p_ZL16post_eligibility_2_address1 = zext_ln727_fu_248_p1;

assign p_ZL16post_eligibility_2_ce1 = p_ZL16post_eligibility_2_ce1_local;

assign p_ZL16post_eligibility_2_d1 = 8'd0;

assign p_ZL16post_eligibility_2_we1 = p_ZL16post_eligibility_2_we1_local;

assign p_ZL16post_eligibility_3_address1 = zext_ln727_fu_248_p1;

assign p_ZL16post_eligibility_3_ce1 = p_ZL16post_eligibility_3_ce1_local;

assign p_ZL16post_eligibility_3_d1 = 8'd0;

assign p_ZL16post_eligibility_3_we1 = p_ZL16post_eligibility_3_we1_local;

assign trunc_ln725_fu_234_p1 = ap_sig_allocacmp_i_3[1:0];

assign zext_ln727_fu_248_p1 = lshr_ln_fu_238_p4;

endmodule //snn_top_hls_snn_top_hls_Pipeline_RESET_ELIG
