// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_591 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        encoder_spikes_din,
        encoder_spikes_full_n,
        encoder_spikes_write,
        sext_ln137_1,
        px_2
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [40:0] encoder_spikes_din;
input   encoder_spikes_full_n;
output   encoder_spikes_write;
input  [4:0] sext_ln137_1;
input  [3:0] px_2;

reg ap_idle;
reg encoder_spikes_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
reg   [0:0] and_ln151_reg_468;
reg   [0:0] and_ln151_reg_468_pp0_iter3_reg;
reg   [0:0] icmp_ln154_reg_487;
wire   [0:0] tmp_s_nbwritereq_fu_104_p3;
reg    ap_predicate_op77_write_state5;
reg    ap_block_state5_pp0_stage0_iter4_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln147_fu_158_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] p_ZL13CONV2_WEIGHTS_11_5_address0;
wire   [6:0] p_ZL13CONV2_WEIGHTS_11_5_q0;
reg    encoder_spikes_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [4:0] px_2_cast_fu_132_p1;
reg   [4:0] px_2_cast_reg_413;
reg    ap_block_pp0_stage0_11001_grp1;
wire  signed [5:0] sext_ln137_1_cast_fu_136_p1;
reg  signed [5:0] sext_ln137_1_cast_reg_418;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln148_fu_181_p2;
reg   [0:0] icmp_ln148_reg_427;
wire   [2:0] add_ln153_fu_195_p2;
reg   [2:0] add_ln153_reg_432;
wire   [2:0] add_ln153_17_fu_201_p2;
reg   [2:0] add_ln153_17_reg_437;
wire   [1:0] trunc_ln149_fu_215_p1;
reg   [1:0] trunc_ln149_reg_442;
wire   [1:0] trunc_ln150_fu_219_p1;
reg   [1:0] trunc_ln150_reg_447;
wire   [2:0] add_ln148_fu_223_p2;
reg   [2:0] add_ln148_reg_452;
wire  signed [4:0] tmp_fu_252_p4;
reg  signed [4:0] tmp_reg_457;
wire   [3:0] trunc_ln150_s_fu_298_p4;
reg   [3:0] trunc_ln150_s_reg_463;
reg   [3:0] trunc_ln150_s_reg_463_pp0_iter3_reg;
wire   [0:0] and_ln151_fu_314_p2;
wire   [7:0] sub_ln152_fu_344_p2;
reg   [7:0] sub_ln152_reg_477;
reg  signed [6:0] wt_reg_482;
wire   [0:0] icmp_ln154_fu_350_p2;
wire   [63:0] zext_ln153_22_fu_329_p1;
reg   [2:0] dx2_fu_80;
wire    ap_loop_init;
reg   [2:0] dy2_fu_84;
wire   [2:0] select_ln147_18_fu_207_p3;
reg   [3:0] indvar_flatten650_fu_88;
wire   [3:0] add_ln147_fu_164_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten650_load;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
reg    p_ZL13CONV2_WEIGHTS_11_5_ce0_local;
wire   [2:0] select_ln147_fu_187_p3;
wire  signed [5:0] sext_ln149_fu_244_p1;
wire   [5:0] add_ln149_fu_247_p2;
wire   [2:0] select_ln147_17_fu_239_p3;
wire   [1:0] trunc_ln153_fu_262_p1;
wire   [3:0] tmp_9_fu_266_p3;
wire   [3:0] zext_ln153_fu_274_p1;
wire  signed [4:0] sext_ln150_fu_290_p1;
wire   [4:0] add_ln150_fu_293_p2;
wire   [0:0] icmp_ln151_9_fu_308_p2;
wire   [0:0] icmp_ln151_fu_284_p2;
wire   [3:0] sub_ln151_fu_278_p2;
wire   [3:0] zext_ln153_21_fu_320_p1;
wire   [3:0] add_ln153_18_fu_323_p2;
wire   [7:0] p_shl_fu_337_p3;
wire  signed [7:0] sext_ln152_fu_334_p1;
wire  signed [6:0] icmp_ln154_fu_350_p0;
wire   [7:0] zext_ln152_fu_356_p1;
wire   [7:0] add_ln156_fu_362_p2;
wire   [7:0] global_nid_fu_368_p2;
wire  signed [7:0] sext_ln153_fu_359_p1;
wire   [10:0] zext_ln156_fu_373_p1;
wire   [32:0] or_ln163_s_fu_377_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 dx2_fu_80 = 3'd0;
#0 dy2_fu_84 = 3'd0;
#0 indvar_flatten650_fu_88 = 4'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_591_p_ZL13CONV2_WEIGHTS_bEo #(
    .DataWidth( 7 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
p_ZL13CONV2_WEIGHTS_11_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL13CONV2_WEIGHTS_11_5_address0),
    .ce0(p_ZL13CONV2_WEIGHTS_11_5_ce0_local),
    .q0(p_ZL13CONV2_WEIGHTS_11_5_q0)
);

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            dx2_fu_80 <= 3'd7;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            dx2_fu_80 <= add_ln148_fu_223_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            dy2_fu_84 <= 3'd7;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            dy2_fu_84 <= select_ln147_18_fu_207_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln147_fu_158_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten650_fu_88 <= add_ln147_fu_164_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten650_fu_88 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln148_reg_452 <= add_ln148_fu_223_p2;
        add_ln153_17_reg_437 <= add_ln153_17_fu_201_p2;
        add_ln153_reg_432 <= add_ln153_fu_195_p2;
        icmp_ln148_reg_427 <= icmp_ln148_fu_181_p2;
        px_2_cast_reg_413[3 : 0] <= px_2_cast_fu_132_p1[3 : 0];
        sext_ln137_1_cast_reg_418 <= sext_ln137_1_cast_fu_136_p1;
        trunc_ln149_reg_442 <= trunc_ln149_fu_215_p1;
        trunc_ln150_reg_447 <= trunc_ln150_fu_219_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        and_ln151_reg_468 <= and_ln151_fu_314_p2;
        and_ln151_reg_468_pp0_iter3_reg <= and_ln151_reg_468;
        icmp_ln154_reg_487 <= icmp_ln154_fu_350_p2;
        sub_ln152_reg_477 <= sub_ln152_fu_344_p2;
        tmp_reg_457 <= {{add_ln149_fu_247_p2[5:1]}};
        trunc_ln150_s_reg_463 <= {{add_ln150_fu_293_p2[4:1]}};
        trunc_ln150_s_reg_463_pp0_iter3_reg <= trunc_ln150_s_reg_463;
        wt_reg_482 <= p_ZL13CONV2_WEIGHTS_11_5_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((icmp_ln147_fu_158_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten650_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten650_load = indvar_flatten650_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_predicate_op77_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        encoder_spikes_blk_n = encoder_spikes_full_n;
    end else begin
        encoder_spikes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_predicate_op77_write_state5 == 1'b1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        encoder_spikes_write = 1'b1;
    end else begin
        encoder_spikes_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL13CONV2_WEIGHTS_11_5_ce0_local = 1'b1;
    end else begin
        p_ZL13CONV2_WEIGHTS_11_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln147_fu_164_p2 = (ap_sig_allocacmp_indvar_flatten650_load + 4'd1);

assign add_ln148_fu_223_p2 = (select_ln147_fu_187_p3 + 3'd1);

assign add_ln149_fu_247_p2 = ($signed(sext_ln149_fu_244_p1) + $signed(sext_ln137_1_cast_reg_418));

assign add_ln150_fu_293_p2 = ($signed(sext_ln150_fu_290_p1) + $signed(px_2_cast_reg_413));

assign add_ln153_17_fu_201_p2 = (dy2_fu_84 + 3'd1);

assign add_ln153_18_fu_323_p2 = (sub_ln151_fu_278_p2 + zext_ln153_21_fu_320_p1);

assign add_ln153_fu_195_p2 = (dy2_fu_84 + 3'd2);

assign add_ln156_fu_362_p2 = ($signed(zext_ln152_fu_356_p1) + $signed(8'd147));

assign and_ln151_fu_314_p2 = (icmp_ln151_fu_284_p2 & icmp_ln151_9_fu_308_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage0_iter4_grp1));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4_grp1 = ((ap_predicate_op77_write_state5 == 1'b1) & (encoder_spikes_full_n == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

always @ (*) begin
    ap_predicate_op77_write_state5 = ((tmp_s_nbwritereq_fu_104_p3 == 1'd1) & (icmp_ln154_reg_487 == 1'd0) & (1'd1 == and_ln151_reg_468_pp0_iter3_reg));
end

assign ap_ready = ap_ready_sig;

assign encoder_spikes_din = $signed(or_ln163_s_fu_377_p4);

assign global_nid_fu_368_p2 = (add_ln156_fu_362_p2 + sub_ln152_reg_477);

assign icmp_ln147_fu_158_p2 = ((ap_sig_allocacmp_indvar_flatten650_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_181_p2 = ((dx2_fu_80 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln151_9_fu_308_p2 = ((trunc_ln150_s_fu_298_p4 < 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln151_fu_284_p2 = ((tmp_fu_252_p4 < 5'd7) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_350_p0 = p_ZL13CONV2_WEIGHTS_11_5_q0;

assign icmp_ln154_fu_350_p2 = ((icmp_ln154_fu_350_p0 == 7'd0) ? 1'b1 : 1'b0);

assign or_ln163_s_fu_377_p4 = {{{{14'd8192}, {sext_ln153_fu_359_p1}}}, {zext_ln156_fu_373_p1}};

assign p_ZL13CONV2_WEIGHTS_11_5_address0 = zext_ln153_22_fu_329_p1;

assign p_shl_fu_337_p3 = {{tmp_reg_457}, {3'd0}};

assign px_2_cast_fu_132_p1 = px_2;

assign select_ln147_17_fu_239_p3 = ((icmp_ln148_reg_427[0:0] == 1'b1) ? add_ln153_reg_432 : add_ln153_17_reg_437);

assign select_ln147_18_fu_207_p3 = ((icmp_ln148_fu_181_p2[0:0] == 1'b1) ? add_ln153_17_fu_201_p2 : dy2_fu_84);

assign select_ln147_fu_187_p3 = ((icmp_ln148_fu_181_p2[0:0] == 1'b1) ? 3'd7 : dx2_fu_80);

assign sext_ln137_1_cast_fu_136_p1 = $signed(sext_ln137_1);

assign sext_ln149_fu_244_p1 = $signed(trunc_ln149_reg_442);

assign sext_ln150_fu_290_p1 = $signed(trunc_ln150_reg_447);

assign sext_ln152_fu_334_p1 = tmp_reg_457;

assign sext_ln153_fu_359_p1 = wt_reg_482;

assign sub_ln151_fu_278_p2 = (tmp_9_fu_266_p3 - zext_ln153_fu_274_p1);

assign sub_ln152_fu_344_p2 = ($signed(p_shl_fu_337_p3) - $signed(sext_ln152_fu_334_p1));

assign tmp_9_fu_266_p3 = {{trunc_ln153_fu_262_p1}, {2'd0}};

assign tmp_fu_252_p4 = {{add_ln149_fu_247_p2[5:1]}};

assign tmp_s_nbwritereq_fu_104_p3 = encoder_spikes_full_n;

assign trunc_ln149_fu_215_p1 = select_ln147_18_fu_207_p3[1:0];

assign trunc_ln150_fu_219_p1 = select_ln147_fu_187_p3[1:0];

assign trunc_ln150_s_fu_298_p4 = {{add_ln150_fu_293_p2[4:1]}};

assign trunc_ln153_fu_262_p1 = select_ln147_17_fu_239_p3[1:0];

assign zext_ln152_fu_356_p1 = trunc_ln150_s_reg_463_pp0_iter3_reg;

assign zext_ln153_21_fu_320_p1 = add_ln148_reg_452;

assign zext_ln153_22_fu_329_p1 = add_ln153_18_fu_323_p2;

assign zext_ln153_fu_274_p1 = select_ln147_17_fu_239_p3;

assign zext_ln156_fu_373_p1 = global_nid_fu_368_p2;

always @ (posedge ap_clk) begin
    px_2_cast_reg_413[4] <= 1'b0;
end

endmodule //snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_591
