// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_apply_rstdp_reward (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reward_signal,
        params_rstdp_enable_val,
        p_ZL15pre_eligibility_0_address0,
        p_ZL15pre_eligibility_0_ce0,
        p_ZL15pre_eligibility_0_q0,
        p_ZL15pre_eligibility_1_address0,
        p_ZL15pre_eligibility_1_ce0,
        p_ZL15pre_eligibility_1_q0,
        p_ZL16post_eligibility_0_address0,
        p_ZL16post_eligibility_0_ce0,
        p_ZL16post_eligibility_0_q0,
        p_ZL16post_eligibility_1_address0,
        p_ZL16post_eligibility_1_ce0,
        p_ZL16post_eligibility_1_q0,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] reward_signal;
input  [0:0] params_rstdp_enable_val;
output  [6:0] p_ZL15pre_eligibility_0_address0;
output   p_ZL15pre_eligibility_0_ce0;
input  [7:0] p_ZL15pre_eligibility_0_q0;
output  [6:0] p_ZL15pre_eligibility_1_address0;
output   p_ZL15pre_eligibility_1_ce0;
input  [7:0] p_ZL15pre_eligibility_1_q0;
output  [6:0] p_ZL16post_eligibility_0_address0;
output   p_ZL16post_eligibility_0_ce0;
input  [7:0] p_ZL16post_eligibility_0_q0;
output  [6:0] p_ZL16post_eligibility_1_address0;
output   p_ZL16post_eligibility_1_ce0;
input  [7:0] p_ZL16post_eligibility_1_q0;
output  [14:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [14:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
output   p_ZL13weight_memory_0_we1;
output  [7:0] p_ZL13weight_memory_0_d1;
output  [14:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [14:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
output   p_ZL13weight_memory_1_we1;
output  [7:0] p_ZL13weight_memory_1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] and_ln458_fu_154_p2;
reg   [0:0] and_ln458_reg_340;
wire   [0:0] tmp_fu_160_p3;
reg   [0:0] tmp_reg_351;
wire   [1:0] shift_sel_fu_258_p9;
reg   [1:0] shift_sel_reg_356;
wire   [8:0] add_ln473_fu_292_p2;
reg   [8:0] add_ln473_reg_367;
wire    ap_CS_fsm_state2;
wire   [7:0] trunc_ln473_fu_314_p1;
reg   [7:0] trunc_ln473_reg_382;
wire    ap_CS_fsm_state3;
wire   [7:0] pre_elig_fu_321_p3;
reg   [7:0] pre_elig_reg_387;
wire   [0:0] icmp_ln477_fu_330_p2;
reg   [0:0] icmp_ln477_reg_392;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_done;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_idle;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_ready;
wire   [6:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_ce0;
wire   [6:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_ce0;
wire   [14:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce0;
wire   [14:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address1;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce1;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_we1;
wire   [7:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_d1;
wire   [14:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address0;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce0;
wire   [14:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address1;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce1;
wire    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_we1;
wire   [7:0] grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_d1;
reg    grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln473_fu_308_p1;
wire   [0:0] icmp_ln473_fu_286_p2;
reg   [8:0] i_fu_90;
reg    ap_block_state4_on_subcall_done;
reg    p_ZL15pre_eligibility_0_ce0_local;
reg    p_ZL15pre_eligibility_1_ce0_local;
wire   [0:0] icmp_ln458_fu_148_p2;
wire   [7:0] reward_mag_fu_168_p2;
wire   [7:0] reward_mag_1_fu_174_p3;
wire   [1:0] tmp_65_fu_182_p4;
wire   [2:0] tmp_66_fu_198_p4;
wire   [3:0] tmp_67_fu_214_p4;
wire   [0:0] icmp_ln467_fu_224_p2;
wire   [0:0] icmp_ln465_fu_192_p2;
wire   [0:0] icmp_ln466_fu_208_p2;
wire   [0:0] xor_ln465_fu_238_p2;
wire   [0:0] and_ln466_fu_244_p2;
wire   [1:0] shift_sel_fu_258_p6;
wire   [1:0] shift_sel_fu_258_p7;
wire   [1:0] shift_sel_fu_258_p8;
wire   [6:0] lshr_ln_fu_298_p4;
wire   [0:0] trunc_ln473_1_fu_318_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire  signed [1:0] shift_sel_fu_258_p1;
wire   [1:0] shift_sel_fu_258_p3;
wire   [1:0] shift_sel_fu_258_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg = 1'b0;
#0 i_fu_90 = 9'd0;
end

snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start),
    .ap_done(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_done),
    .ap_idle(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_idle),
    .ap_ready(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_ready),
    .i(trunc_ln473_reg_382),
    .sext_ln486(pre_elig_reg_387),
    .shift_sel(shift_sel_reg_356),
    .empty(tmp_reg_351),
    .p_ZL16post_eligibility_0_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_address0),
    .p_ZL16post_eligibility_0_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_ce0),
    .p_ZL16post_eligibility_0_q0(p_ZL16post_eligibility_0_q0),
    .p_ZL16post_eligibility_1_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_address0),
    .p_ZL16post_eligibility_1_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_ce0),
    .p_ZL16post_eligibility_1_q0(p_ZL16post_eligibility_1_q0),
    .p_ZL13weight_memory_0_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address0),
    .p_ZL13weight_memory_0_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce0),
    .p_ZL13weight_memory_0_q0(p_ZL13weight_memory_0_q0),
    .p_ZL13weight_memory_0_address1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address1),
    .p_ZL13weight_memory_0_ce1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce1),
    .p_ZL13weight_memory_0_we1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_we1),
    .p_ZL13weight_memory_0_d1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_d1),
    .p_ZL13weight_memory_1_address0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address0),
    .p_ZL13weight_memory_1_ce0(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce0),
    .p_ZL13weight_memory_1_q0(p_ZL13weight_memory_1_q0),
    .p_ZL13weight_memory_1_address1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address1),
    .p_ZL13weight_memory_1_ce1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce1),
    .p_ZL13weight_memory_1_we1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_we1),
    .p_ZL13weight_memory_1_d1(grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_d1)
);

(* dissolve_hierarchy = "yes" *) snn_top_hls_sparsemux_7_2_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 2 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 2 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 2 ),
    .def_WIDTH( 2 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
sparsemux_7_2_2_1_1_U155(
    .din0(2'd0),
    .din1(2'd1),
    .din2(shift_sel_fu_258_p6),
    .def(shift_sel_fu_258_p7),
    .sel(shift_sel_fu_258_p8),
    .dout(shift_sel_fu_258_p9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln477_fu_330_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg <= 1'b1;
        end else if ((grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_ready == 1'b1)) begin
            grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (1'd1 == and_ln458_fu_154_p2))) begin
        i_fu_90 <= 9'd0;
    end else if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
        i_fu_90 <= add_ln473_reg_367;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln473_reg_367 <= add_ln473_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln458_reg_340 <= and_ln458_fu_154_p2;
        shift_sel_reg_356 <= shift_sel_fu_258_p9;
        tmp_reg_351 <= reward_signal[32'd7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln477_reg_392 <= icmp_ln477_fu_330_p2;
        pre_elig_reg_387 <= pre_elig_fu_321_p3;
        trunc_ln473_reg_382 <= trunc_ln473_fu_314_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & ((icmp_ln473_fu_286_p2 == 1'd1) | (1'd0 == and_ln458_reg_340))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln473_fu_286_p2 == 1'd1) | (1'd0 == and_ln458_reg_340)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL15pre_eligibility_0_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_ZL15pre_eligibility_1_ce0_local = 1'b1;
    end else begin
        p_ZL15pre_eligibility_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln473_fu_286_p2 == 1'd1) | (1'd0 == and_ln458_reg_340)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln473_fu_292_p2 = (i_fu_90 + 9'd1);

assign and_ln458_fu_154_p2 = (params_rstdp_enable_val & icmp_ln458_fu_148_p2);

assign and_ln466_fu_244_p2 = (xor_ln465_fu_238_p2 & icmp_ln466_fu_208_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((icmp_ln477_reg_392 == 1'd0) & (grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_done == 1'b0));
end

assign grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_ap_start_reg;

assign icmp_ln458_fu_148_p2 = ((reward_signal != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln465_fu_192_p2 = ((tmp_65_fu_182_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln466_fu_208_p2 = ((tmp_66_fu_198_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln467_fu_224_p2 = ((tmp_67_fu_214_p4 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln473_fu_286_p2 = ((i_fu_90 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln477_fu_330_p2 = ((pre_elig_fu_321_p3 == 8'd0) ? 1'b1 : 1'b0);

assign lshr_ln_fu_298_p4 = {{i_fu_90[7:1]}};

assign p_ZL13weight_memory_0_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address0;

assign p_ZL13weight_memory_0_address1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_address1;

assign p_ZL13weight_memory_0_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce0;

assign p_ZL13weight_memory_0_ce1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_ce1;

assign p_ZL13weight_memory_0_d1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_d1;

assign p_ZL13weight_memory_0_we1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_0_we1;

assign p_ZL13weight_memory_1_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address0;

assign p_ZL13weight_memory_1_address1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_address1;

assign p_ZL13weight_memory_1_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce0;

assign p_ZL13weight_memory_1_ce1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_ce1;

assign p_ZL13weight_memory_1_d1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_d1;

assign p_ZL13weight_memory_1_we1 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL13weight_memory_1_we1;

assign p_ZL15pre_eligibility_0_address0 = zext_ln473_fu_308_p1;

assign p_ZL15pre_eligibility_0_ce0 = p_ZL15pre_eligibility_0_ce0_local;

assign p_ZL15pre_eligibility_1_address0 = zext_ln473_fu_308_p1;

assign p_ZL15pre_eligibility_1_ce0 = p_ZL15pre_eligibility_1_ce0_local;

assign p_ZL16post_eligibility_0_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_address0;

assign p_ZL16post_eligibility_0_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_0_ce0;

assign p_ZL16post_eligibility_1_address0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_address0;

assign p_ZL16post_eligibility_1_ce0 = grp_apply_rstdp_reward_Pipeline_RSTDP_INNER_fu_132_p_ZL16post_eligibility_1_ce0;

assign pre_elig_fu_321_p3 = ((trunc_ln473_1_fu_318_p1[0:0] == 1'b1) ? p_ZL15pre_eligibility_1_q0 : p_ZL15pre_eligibility_0_q0);

assign reward_mag_1_fu_174_p3 = ((tmp_fu_160_p3[0:0] == 1'b1) ? reward_mag_fu_168_p2 : reward_signal);

assign reward_mag_fu_168_p2 = (8'd0 - reward_signal);

assign shift_sel_fu_258_p6 = ((icmp_ln467_fu_224_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign shift_sel_fu_258_p7 = 'bx;

assign shift_sel_fu_258_p8 = {{icmp_ln465_fu_192_p2}, {and_ln466_fu_244_p2}};

assign tmp_65_fu_182_p4 = {{reward_mag_1_fu_174_p3[7:6]}};

assign tmp_66_fu_198_p4 = {{reward_mag_1_fu_174_p3[7:5]}};

assign tmp_67_fu_214_p4 = {{reward_mag_1_fu_174_p3[7:4]}};

assign tmp_fu_160_p3 = reward_signal[32'd7];

assign trunc_ln473_1_fu_318_p1 = i_fu_90[0:0];

assign trunc_ln473_fu_314_p1 = i_fu_90[7:0];

assign xor_ln465_fu_238_p2 = (icmp_ln465_fu_192_p2 ^ 1'd1);

assign zext_ln473_fu_308_p1 = lshr_ln_fu_298_p4;

endmodule //snn_top_hls_apply_rstdp_reward
