-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    widx : IN STD_LOGIC_VECTOR (13 downto 0);
    tmp_s : IN STD_LOGIC_VECTOR (6 downto 0);
    zext_ln473 : IN STD_LOGIC_VECTOR (4 downto 0);
    tmp_222 : IN STD_LOGIC_VECTOR (9 downto 0);
    sext_ln502 : IN STD_LOGIC_VECTOR (15 downto 0);
    sext_ln290 : IN STD_LOGIC_VECTOR (15 downto 0);
    learn_weight_ready : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln290 : IN STD_LOGIC_VECTOR (0 downto 0);
    post_id : IN STD_LOGIC_VECTOR (4 downto 0);
    dst_group : IN STD_LOGIC_VECTOR (1 downto 0);
    pre_traces_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pre_traces_ce0 : OUT STD_LOGIC;
    pre_traces_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    weight_memory_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    weight_memory_ce0 : OUT STD_LOGIC;
    weight_memory_we0 : OUT STD_LOGIC;
    weight_memory_d0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    weight_memory_q0 : IN STD_LOGIC_VECTOR (3 downto 0);
    learn_bridge_valid_i : IN STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_valid_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_valid_o_ap_vld : OUT STD_LOGIC;
    learn_bridge_group : OUT STD_LOGIC_VECTOR (1 downto 0);
    learn_bridge_group_ap_vld : OUT STD_LOGIC;
    learn_bridge_src : OUT STD_LOGIC_VECTOR (7 downto 0);
    learn_bridge_src_ap_vld : OUT STD_LOGIC;
    learn_bridge_dst : OUT STD_LOGIC_VECTOR (5 downto 0);
    learn_bridge_dst_ap_vld : OUT STD_LOGIC;
    learn_bridge_data : OUT STD_LOGIC_VECTOR (3 downto 0);
    learn_bridge_data_ap_vld : OUT STD_LOGIC;
    learn_bridge_exc : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_exc_ap_vld : OUT STD_LOGIC;
    learn_bridge_is_inter : OUT STD_LOGIC_VECTOR (0 downto 0);
    learn_bridge_is_inter_ap_vld : OUT STD_LOGIC;
    learn_bridge_dst_group : OUT STD_LOGIC_VECTOR (1 downto 0);
    learn_bridge_dst_group_ap_vld : OUT STD_LOGIC );
end;


architecture behav of snn_top_hls_process_post_spike_aer_Pipeline_LTP_LOOP is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_pp0_stage8 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_pp0_stage9 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_pp0_stage10 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_pp0_stage11 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv16_FFF8 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln473_reg_604 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage11 : signal is "none";
    signal ap_block_pp0_stage11_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal post_id_cast_fu_238_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal post_id_cast_reg_584 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln502_cast_fu_242_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln502_cast_reg_589 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln473_cast_fu_246_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln473_cast_reg_594 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln290_cast_fu_250_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal sext_ln290_cast_reg_599 : STD_LOGIC_VECTOR (27 downto 0);
    signal icmp_ln473_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal pre_id_fu_287_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal pre_id_reg_608 : STD_LOGIC_VECTOR (9 downto 0);
    signal pre_trace_val_reg_619 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln484_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_reg_624 : STD_LOGIC_VECTOR (0 downto 0);
    signal weight_memory_addr_reg_628 : STD_LOGIC_VECTOR (13 downto 0);
    signal or_ln284_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln284_reg_633 : STD_LOGIC_VECTOR (0 downto 0);
    signal current_w_reg_637 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage9 : signal is "none";
    signal ap_block_pp0_stage9_11001 : BOOLEAN;
    signal updated_fu_507_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal updated_reg_662 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln480_fu_293_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln473_1_fu_306_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal tmp_fu_337_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ii_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln473_fu_277_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_ii_1 : STD_LOGIC_VECTOR (7 downto 0);
    signal widx_2_fu_148 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln517_fu_391_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal pre_traces_ce0_local : STD_LOGIC;
    signal weight_memory_ce0_local : STD_LOGIC;
    signal weight_memory_address0_local : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal weight_memory_we0_local : STD_LOGIC;
    signal sext_ln470_fu_254_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln473_2_fu_283_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal xor_ln284_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln284_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal distance_fu_401_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal distance_fu_401_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_414_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_414_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_414_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal grp_fu_424_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_424_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_424_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_block_pp0_stage9 : BOOLEAN;
    signal trunc_ln_fu_429_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_443_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_443_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal delta_fu_451_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln490_fu_448_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal w_fu_461_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_217_fu_467_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln252_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln253_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln252_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln252_fu_493_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln254_fu_489_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_218_fu_516_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal mag_3_fu_529_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal ap_block_pp0_stage8_subdone : BOOLEAN;
    signal ap_block_pp0_stage9_subdone : BOOLEAN;
    signal ap_block_pp0_stage10_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_414_p00 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_414_p10 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_424_p00 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_mul_4ns_8ns_12_3_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component snn_top_hls_mul_12ns_16s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component snn_top_hls_mul_12s_16s_28_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (11 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_4ns_8ns_12_3_1_U641 : component snn_top_hls_mul_4ns_8ns_12_3_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 4,
        din1_WIDTH => 8,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_414_p0,
        din1 => grp_fu_414_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_414_p2);

    mul_12ns_16s_28_4_1_U642 : component snn_top_hls_mul_12ns_16s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_424_p0,
        din1 => grp_fu_424_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_424_p2);

    mul_12s_16s_28_4_1_U643 : component snn_top_hls_mul_12s_16s_28_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 12,
        din1_WIDTH => 16,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => trunc_ln_fu_429_p4,
        din1 => grp_fu_443_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_443_p2);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage11_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ii_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln473_fu_271_p2 = ap_const_lv1_0))) then 
                    ii_fu_144 <= add_ln473_fu_277_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ii_fu_144 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    widx_2_fu_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                widx_2_fu_148 <= widx;
            elsif (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                widx_2_fu_148 <= add_ln517_fu_391_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                current_w_reg_637 <= weight_memory_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln473_reg_604 <= icmp_ln473_fu_271_p2;
                    post_id_cast_reg_584(4 downto 0) <= post_id_cast_fu_238_p1(4 downto 0);
                pre_id_reg_608 <= pre_id_fu_287_p2;
                sext_ln290_cast_reg_599 <= sext_ln290_cast_fu_250_p1;
                sext_ln502_cast_reg_589 <= sext_ln502_cast_fu_242_p1;
                updated_reg_662 <= updated_fu_507_p3;
                    zext_ln473_cast_reg_594(4 downto 0) <= zext_ln473_cast_fu_246_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln484_reg_624 <= icmp_ln484_fu_311_p2;
                or_ln284_reg_633 <= or_ln284_fu_332_p2;
                pre_trace_val_reg_619 <= pre_traces_q0;
                weight_memory_addr_reg_628 <= zext_ln473_1_fu_306_p1(14 - 1 downto 0);
            end if;
        end if;
    end process;
    post_id_cast_reg_584(5) <= '0';
    zext_ln473_cast_reg_594(13 downto 5) <= "000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage11_subdone, ap_block_pp0_stage0_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_block_pp0_stage7_subdone, ap_block_pp0_stage8_subdone, ap_block_pp0_stage9_subdone, ap_block_pp0_stage10_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when ap_ST_fsm_pp0_stage8 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage8_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage8;
                end if;
            when ap_ST_fsm_pp0_stage9 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage9_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage9;
                end if;
            when ap_ST_fsm_pp0_stage10 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage10_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage10;
                end if;
            when ap_ST_fsm_pp0_stage11 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage11_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    add_ln473_fu_277_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ii_1) + unsigned(ap_const_lv8_1));
    add_ln517_fu_391_p2 <= std_logic_vector(unsigned(zext_ln473_cast_reg_594) + unsigned(widx_2_fu_148));
    and_ln284_fu_326_p2 <= (xor_ln284_fu_321_p2 and learn_bridge_valid_i);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage11 <= ap_CS_fsm(11);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage9 <= ap_CS_fsm(9);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage10_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage11_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage8_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage9_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage9_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage11, ap_block_pp0_stage11_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage11_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage11))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ii_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ii_fu_144, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ii_1 <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_ii_1 <= ii_fu_144;
        end if; 
    end process;

    delta_fu_451_p4 <= grp_fu_443_p2(23 downto 8);
    distance_fu_401_p1 <= weight_memory_q0;
    distance_fu_401_p2 <= std_logic_vector(unsigned(ap_const_lv4_7) - unsigned(distance_fu_401_p1));
    grp_fu_414_p0 <= grp_fu_414_p00(4 - 1 downto 0);
    grp_fu_414_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(distance_fu_401_p2),12));
    grp_fu_414_p1 <= grp_fu_414_p10(8 - 1 downto 0);
    grp_fu_414_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_trace_val_reg_619),12));
    grp_fu_424_p0 <= grp_fu_424_p00(12 - 1 downto 0);
    grp_fu_424_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_414_p2),28));
    grp_fu_424_p1 <= sext_ln502_cast_reg_589(16 - 1 downto 0);
    grp_fu_443_p1 <= sext_ln290_cast_reg_599(16 - 1 downto 0);
    icmp_ln252_fu_477_p2 <= "1" when (signed(tmp_217_fu_467_p4) > signed(ap_const_lv13_0)) else "0";
    icmp_ln253_fu_483_p2 <= "1" when (signed(w_fu_461_p2) < signed(ap_const_lv16_FFF8)) else "0";
    icmp_ln473_fu_271_p2 <= "1" when (ap_sig_allocacmp_ii_1 = sext_ln470_fu_254_p1) else "0";
    icmp_ln484_fu_311_p2 <= "1" when (pre_traces_q0 = ap_const_lv8_0) else "0";
    learn_bridge_data <= 
        mag_3_fu_529_p2 when (tmp_218_fu_516_p3(0) = '1') else 
        updated_reg_662;

    learn_bridge_data_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln484_reg_624, or_ln284_reg_633)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_reg_633 = ap_const_lv1_0) and (icmp_ln484_reg_624 = ap_const_lv1_0))) then 
            learn_bridge_data_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_data_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_dst <= post_id_cast_reg_584;

    learn_bridge_dst_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_dst_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_dst_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_dst_group <= dst_group;

    learn_bridge_dst_group_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_dst_group_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_dst_group_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_exc <= (tmp_218_fu_516_p3 xor ap_const_lv1_1);

    learn_bridge_exc_ap_vld_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, icmp_ln484_reg_624, or_ln284_reg_633)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_reg_633 = ap_const_lv1_0) and (icmp_ln484_reg_624 = ap_const_lv1_0))) then 
            learn_bridge_exc_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_exc_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_group <= pre_id_reg_608(9 downto 8);

    learn_bridge_group_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_group_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_group_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_is_inter <= "0" when (tmp_fu_337_p4 = dst_group) else "1";

    learn_bridge_is_inter_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_is_inter_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_is_inter_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    learn_bridge_src <= pre_id_reg_608(8 - 1 downto 0);

    learn_bridge_src_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_src_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_src_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    learn_bridge_valid_o_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, learn_bridge_valid_i, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2, ap_block_pp0_stage1)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_valid_o <= ap_const_lv1_1;
        else 
            learn_bridge_valid_o <= learn_bridge_valid_i;
        end if; 
    end process;


    learn_bridge_valid_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, icmp_ln473_reg_604, ap_block_pp0_stage1_11001, icmp_ln484_fu_311_p2, or_ln284_fu_332_p2)
    begin
        if (((icmp_ln473_reg_604 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (or_ln284_fu_332_p2 = ap_const_lv1_0) and (icmp_ln484_fu_311_p2 = ap_const_lv1_0))) then 
            learn_bridge_valid_o_ap_vld <= ap_const_logic_1;
        else 
            learn_bridge_valid_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mag_3_fu_529_p2 <= std_logic_vector(unsigned(ap_const_lv4_0) - unsigned(updated_reg_662));
    or_ln252_fu_501_p2 <= (icmp_ln253_fu_483_p2 or icmp_ln252_fu_477_p2);
    or_ln284_fu_332_p2 <= (icmp_ln290 or and_ln284_fu_326_p2);
    post_id_cast_fu_238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(post_id),6));
    pre_id_fu_287_p2 <= std_logic_vector(unsigned(zext_ln473_2_fu_283_p1) + unsigned(tmp_222));
    pre_traces_address0 <= zext_ln480_fu_293_p1(10 - 1 downto 0);
    pre_traces_ce0 <= pre_traces_ce0_local;

    pre_traces_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            pre_traces_ce0_local <= ap_const_logic_1;
        else 
            pre_traces_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln252_fu_493_p3 <= 
        ap_const_lv4_7 when (icmp_ln252_fu_477_p2(0) = '1') else 
        ap_const_lv4_8;
        sext_ln290_cast_fu_250_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln290),28));

        sext_ln470_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s),8));

        sext_ln490_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_reg_637),16));

        sext_ln502_cast_fu_242_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln502),28));

    tmp_217_fu_467_p4 <= w_fu_461_p2(15 downto 3);
    tmp_218_fu_516_p3 <= updated_reg_662(3 downto 3);
    tmp_fu_337_p4 <= pre_id_reg_608(9 downto 8);
    trunc_ln254_fu_489_p1 <= w_fu_461_p2(4 - 1 downto 0);
    trunc_ln_fu_429_p4 <= grp_fu_424_p2(27 downto 16);
    updated_fu_507_p3 <= 
        select_ln252_fu_493_p3 when (or_ln252_fu_501_p2(0) = '1') else 
        trunc_ln254_fu_489_p1;
    w_fu_461_p2 <= std_logic_vector(unsigned(delta_fu_451_p4) + unsigned(sext_ln490_fu_448_p1));
    weight_memory_address0 <= weight_memory_address0_local;

    weight_memory_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, weight_memory_addr_reg_628, ap_block_pp0_stage0, zext_ln473_1_fu_306_p1, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            weight_memory_address0_local <= weight_memory_addr_reg_628;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            weight_memory_address0_local <= zext_ln473_1_fu_306_p1(14 - 1 downto 0);
        else 
            weight_memory_address0_local <= "XXXXXXXXXXXXXX";
        end if; 
    end process;

    weight_memory_ce0 <= weight_memory_ce0_local;

    weight_memory_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
        if ((((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            weight_memory_ce0_local <= ap_const_logic_1;
        else 
            weight_memory_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weight_memory_d0 <= updated_fu_507_p3;
    weight_memory_we0 <= weight_memory_we0_local;

    weight_memory_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln484_reg_624)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln484_reg_624 = ap_const_lv1_0))) then 
            weight_memory_we0_local <= ap_const_logic_1;
        else 
            weight_memory_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln284_fu_321_p2 <= (learn_weight_ready xor ap_const_lv1_1);
    zext_ln473_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widx_2_fu_148),64));
    zext_ln473_2_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ii_1),10));
    zext_ln473_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln473),14));
    zext_ln480_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pre_id_fu_287_p2),64));
end behav;
