-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_586 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    encoder_spikes_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    encoder_spikes_full_n : IN STD_LOGIC;
    encoder_spikes_write : OUT STD_LOGIC;
    sext_ln137_1 : IN STD_LOGIC_VECTOR (4 downto 0);
    px_2 : IN STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_586 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_E : STD_LOGIC_VECTOR (5 downto 0) := "001110";
    constant ap_const_lv5_E : STD_LOGIC_VECTOR (4 downto 0) := "01110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_22 : STD_LOGIC_VECTOR (5 downto 0) := "100010";
    constant ap_const_lv17_10F0F : STD_LOGIC_VECTOR (16 downto 0) := "10000111100001111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal and_ln151_reg_467 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln151_reg_467_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln156_reg_491 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_nbwritereq_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op80_write_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln147_fu_162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL13CONV2_WEIGHTS_6_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_ZL13CONV2_WEIGHTS_6_5_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal encoder_spikes_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal px_2_cast_fu_136_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal px_2_cast_reg_430 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal sext_ln137_1_cast_fu_140_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln137_1_cast_reg_435 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln147_fu_213_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln147_reg_444 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln155_fu_217_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln155_reg_449 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln148_fu_223_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln148_reg_455 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_reg_461 : STD_LOGIC_VECTOR (4 downto 0);
    signal and_ln151_fu_297_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln153_s_reg_471 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln153_s_reg_471_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln154_fu_343_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln154_reg_481 : STD_LOGIC_VECTOR (7 downto 0);
    signal wt_reg_486 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln156_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln155_37_fu_328_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal dx2_fu_84 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln148_fu_227_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal dy2_fu_88 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln147_15_fu_205_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten615_fu_92 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln147_fu_168_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten615_load : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal p_ZL13CONV2_WEIGHTS_6_5_ce0_local : STD_LOGIC;
    signal icmp_ln148_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln147_14_fu_185_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln147_fu_197_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln152_fu_243_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln152_fu_246_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_264_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln155_fu_261_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln151_fu_283_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln151_fu_286_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln151_15_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln151_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln155_28_fu_313_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub_ln155_27_fu_271_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln155_36_fu_318_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln155_fu_322_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl12_fu_336_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln154_fu_333_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln155_35_fu_355_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln158_fu_358_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln158_fu_364_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln158_fu_368_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal global_nid_fu_372_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln158_8_fu_377_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_15_fu_381_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln165_fu_388_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln165_fu_392_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln165_173_cast_fu_396_p3 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_586_p_ZL13CONV2_WEIGHTS_bzo IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL13CONV2_WEIGHTS_6_5_U : component snn_top_hls_snn_top_hls_Pipeline_VITIS_LOOP_147_4_VITIS_LOOP_148_586_p_ZL13CONV2_WEIGHTS_bzo
    generic map (
        DataWidth => 5,
        AddressRange => 9,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL13CONV2_WEIGHTS_6_5_address0,
        ce0 => p_ZL13CONV2_WEIGHTS_6_5_ce0_local,
        q0 => p_ZL13CONV2_WEIGHTS_6_5_q0);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    dx2_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    dx2_fu_84 <= ap_const_lv3_7;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    dx2_fu_84 <= add_ln148_fu_227_p2;
                end if;
            end if; 
        end if;
    end process;

    dy2_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    dy2_fu_88 <= ap_const_lv3_7;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    dy2_fu_88 <= select_ln147_15_fu_205_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten615_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln147_fu_162_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten615_fu_92 <= add_ln147_fu_168_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten615_fu_92 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                and_ln151_reg_467 <= and_ln151_fu_297_p2;
                and_ln151_reg_467_pp0_iter3_reg <= and_ln151_reg_467;
                icmp_ln156_reg_491 <= icmp_ln156_fu_349_p2;
                lshr_ln153_s_reg_471 <= add_ln151_fu_286_p2(3 downto 1);
                lshr_ln153_s_reg_471_pp0_iter3_reg <= lshr_ln153_s_reg_471;
                sub_ln154_reg_481 <= sub_ln154_fu_343_p2;
                tmp_reg_461 <= add_ln152_fu_246_p2(5 downto 1);
                wt_reg_486 <= p_ZL13CONV2_WEIGHTS_6_5_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    px_2_cast_reg_430(3 downto 0) <= px_2_cast_fu_136_p1(3 downto 0);
                sext_ln137_1_cast_reg_435 <= sext_ln137_1_cast_fu_140_p1;
                sub_ln155_reg_449 <= sub_ln155_fu_217_p2;
                trunc_ln147_reg_444 <= trunc_ln147_fu_213_p1;
                trunc_ln148_reg_455 <= trunc_ln148_fu_223_p1;
            end if;
        end if;
    end process;
    px_2_cast_reg_430(4) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln147_14_fu_185_p2 <= std_logic_vector(unsigned(dy2_fu_88) + unsigned(ap_const_lv3_1));
    add_ln147_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten615_load) + unsigned(ap_const_lv4_1));
    add_ln148_fu_227_p2 <= std_logic_vector(unsigned(select_ln147_fu_197_p3) + unsigned(ap_const_lv3_1));
    add_ln151_fu_286_p2 <= std_logic_vector(signed(sext_ln151_fu_283_p1) + signed(px_2_cast_reg_430));
    add_ln152_fu_246_p2 <= std_logic_vector(signed(sext_ln152_fu_243_p1) + signed(sext_ln137_1_cast_reg_435));
    add_ln155_fu_322_p2 <= std_logic_vector(unsigned(sub_ln155_27_fu_271_p2) + unsigned(zext_ln155_36_fu_318_p1));
    add_ln158_fu_358_p2 <= std_logic_vector(unsigned(zext_ln155_35_fu_355_p1) + unsigned(ap_const_lv6_22));
    and_ln151_fu_297_p2 <= (icmp_ln151_fu_277_p2 and icmp_ln151_15_fu_291_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_state5_pp0_stage0_iter4_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state5_pp0_stage0_iter4_grp1));
    end process;


    ap_block_state5_pp0_stage0_iter4_grp1_assign_proc : process(encoder_spikes_full_n, ap_predicate_op80_write_state5)
    begin
                ap_block_state5_pp0_stage0_iter4_grp1 <= ((ap_predicate_op80_write_state5 = ap_const_boolean_1) and (encoder_spikes_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln147_fu_162_p2)
    begin
        if (((icmp_ln147_fu_162_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_predicate_op80_write_state5_assign_proc : process(and_ln151_reg_467_pp0_iter3_reg, icmp_ln156_reg_491, tmp_s_nbwritereq_fu_108_p3)
    begin
                ap_predicate_op80_write_state5 <= ((tmp_s_nbwritereq_fu_108_p3 = ap_const_lv1_1) and (icmp_ln156_reg_491 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln151_reg_467_pp0_iter3_reg));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten615_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, indvar_flatten615_fu_92, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten615_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten615_load <= indvar_flatten615_fu_92;
        end if; 
    end process;


    encoder_spikes_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, encoder_spikes_full_n, ap_predicate_op80_write_state5, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_predicate_op80_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            encoder_spikes_blk_n <= encoder_spikes_full_n;
        else 
            encoder_spikes_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    encoder_spikes_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln165_173_cast_fu_396_p3),64));

    encoder_spikes_write_assign_proc : process(ap_enable_reg_pp0_iter4, ap_predicate_op80_write_state5, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_predicate_op80_write_state5 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            encoder_spikes_write <= ap_const_logic_1;
        else 
            encoder_spikes_write <= ap_const_logic_0;
        end if; 
    end process;

    global_nid_fu_372_p2 <= std_logic_vector(unsigned(zext_ln158_fu_368_p1) + unsigned(sub_ln154_reg_481));
    icmp_ln147_fu_162_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten615_load = ap_const_lv4_9) else "0";
    icmp_ln148_fu_191_p2 <= "1" when (dx2_fu_84 = ap_const_lv3_2) else "0";
    icmp_ln151_15_fu_291_p2 <= "1" when (unsigned(add_ln151_fu_286_p2) < unsigned(ap_const_lv5_E)) else "0";
    icmp_ln151_fu_277_p2 <= "1" when (unsigned(add_ln152_fu_246_p2) < unsigned(ap_const_lv6_E)) else "0";
    icmp_ln156_fu_349_p2 <= "1" when (p_ZL13CONV2_WEIGHTS_6_5_q0 = ap_const_lv5_0) else "0";
    p_ZL13CONV2_WEIGHTS_6_5_address0 <= zext_ln155_37_fu_328_p1(4 - 1 downto 0);

    p_ZL13CONV2_WEIGHTS_6_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13CONV2_WEIGHTS_6_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13CONV2_WEIGHTS_6_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_shl12_fu_336_p3 <= (tmp_reg_461 & ap_const_lv3_0);
    p_shl_fu_264_p3 <= (sub_ln155_reg_449 & ap_const_lv2_0);
    px_2_cast_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(px_2),5));
    select_ln147_15_fu_205_p3 <= 
        add_ln147_14_fu_185_p2 when (icmp_ln148_fu_191_p2(0) = '1') else 
        dy2_fu_88;
    select_ln147_fu_197_p3 <= 
        ap_const_lv3_7 when (icmp_ln148_fu_191_p2(0) = '1') else 
        dx2_fu_84;
        sext_ln137_1_cast_fu_140_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln137_1),6));

        sext_ln151_fu_283_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln148_reg_455),5));

        sext_ln152_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln147_reg_444),6));

        sext_ln154_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_reg_461),8));

        sext_ln158_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln158_fu_358_p2),7));

        sext_ln165_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_381_p3),19));

    sub_ln154_fu_343_p2 <= std_logic_vector(unsigned(p_shl12_fu_336_p3) - unsigned(sext_ln154_fu_333_p1));
    sub_ln155_27_fu_271_p2 <= std_logic_vector(unsigned(p_shl_fu_264_p3) - unsigned(zext_ln155_fu_261_p1));
    sub_ln155_28_fu_313_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) - unsigned(trunc_ln148_reg_455));
    sub_ln155_fu_217_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) - unsigned(trunc_ln147_fu_213_p1));
    tmp_15_fu_381_p3 <= (wt_reg_486 & zext_ln158_8_fu_377_p1);
    tmp_s_nbwritereq_fu_108_p3 <= (0=>encoder_spikes_full_n, others=>'-');
    trunc_ln147_fu_213_p1 <= select_ln147_15_fu_205_p3(2 - 1 downto 0);
    trunc_ln148_fu_223_p1 <= select_ln147_fu_197_p3(2 - 1 downto 0);
    zext_ln155_35_fu_355_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln153_s_reg_471_pp0_iter3_reg),6));
    zext_ln155_36_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln155_28_fu_313_p2),4));
    zext_ln155_37_fu_328_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln155_fu_322_p2),64));
    zext_ln155_fu_261_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub_ln155_reg_449),4));
    zext_ln158_8_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(global_nid_fu_372_p2),11));
    zext_ln158_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln158_fu_364_p1),8));
    zext_ln165_173_cast_fu_396_p3 <= (ap_const_lv17_10F0F & zext_ln165_fu_392_p1);
    zext_ln165_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln165_fu_388_p1),32));
end behav;
