// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_process_pre_spike_aer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pre_id,
        current_time,
        pre_traces_trace_0_address0,
        pre_traces_trace_0_ce0,
        pre_traces_trace_0_q0,
        pre_traces_trace_0_address1,
        pre_traces_trace_0_ce1,
        pre_traces_trace_0_we1,
        pre_traces_trace_0_d1,
        pre_traces_trace_1_address0,
        pre_traces_trace_1_ce0,
        pre_traces_trace_1_q0,
        pre_traces_trace_1_address1,
        pre_traces_trace_1_ce1,
        pre_traces_trace_1_we1,
        pre_traces_trace_1_d1,
        pre_traces_last_spike_time_0_address0,
        pre_traces_last_spike_time_0_ce0,
        pre_traces_last_spike_time_0_q0,
        pre_traces_last_spike_time_0_address1,
        pre_traces_last_spike_time_0_ce1,
        pre_traces_last_spike_time_0_we1,
        pre_traces_last_spike_time_0_d1,
        pre_traces_last_spike_time_1_address0,
        pre_traces_last_spike_time_1_ce0,
        pre_traces_last_spike_time_1_q0,
        pre_traces_last_spike_time_1_address1,
        pre_traces_last_spike_time_1_ce1,
        pre_traces_last_spike_time_1_we1,
        pre_traces_last_spike_time_1_d1,
        EXP_DECAY_LUT_address0,
        EXP_DECAY_LUT_ce0,
        EXP_DECAY_LUT_q0,
        post_traces_trace_1_address0,
        post_traces_trace_1_ce0,
        post_traces_trace_1_q0,
        post_traces_last_spike_time_1_address0,
        post_traces_last_spike_time_1_ce0,
        post_traces_last_spike_time_1_q0,
        post_traces_trace_0_address0,
        post_traces_trace_0_ce0,
        post_traces_trace_0_q0,
        post_traces_last_spike_time_0_address0,
        post_traces_last_spike_time_0_ce0,
        post_traces_last_spike_time_0_q0,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_we1,
        p_ZL13weight_memory_0_d1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_we1,
        p_ZL13weight_memory_1_d1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] pre_id;
input  [15:0] current_time;
output  [6:0] pre_traces_trace_0_address0;
output   pre_traces_trace_0_ce0;
input  [7:0] pre_traces_trace_0_q0;
output  [6:0] pre_traces_trace_0_address1;
output   pre_traces_trace_0_ce1;
output   pre_traces_trace_0_we1;
output  [7:0] pre_traces_trace_0_d1;
output  [6:0] pre_traces_trace_1_address0;
output   pre_traces_trace_1_ce0;
input  [7:0] pre_traces_trace_1_q0;
output  [6:0] pre_traces_trace_1_address1;
output   pre_traces_trace_1_ce1;
output   pre_traces_trace_1_we1;
output  [7:0] pre_traces_trace_1_d1;
output  [6:0] pre_traces_last_spike_time_0_address0;
output   pre_traces_last_spike_time_0_ce0;
input  [15:0] pre_traces_last_spike_time_0_q0;
output  [6:0] pre_traces_last_spike_time_0_address1;
output   pre_traces_last_spike_time_0_ce1;
output   pre_traces_last_spike_time_0_we1;
output  [15:0] pre_traces_last_spike_time_0_d1;
output  [6:0] pre_traces_last_spike_time_1_address0;
output   pre_traces_last_spike_time_1_ce0;
input  [15:0] pre_traces_last_spike_time_1_q0;
output  [6:0] pre_traces_last_spike_time_1_address1;
output   pre_traces_last_spike_time_1_ce1;
output   pre_traces_last_spike_time_1_we1;
output  [15:0] pre_traces_last_spike_time_1_d1;
output  [3:0] EXP_DECAY_LUT_address0;
output   EXP_DECAY_LUT_ce0;
input  [7:0] EXP_DECAY_LUT_q0;
output  [6:0] post_traces_trace_1_address0;
output   post_traces_trace_1_ce0;
input  [7:0] post_traces_trace_1_q0;
output  [6:0] post_traces_last_spike_time_1_address0;
output   post_traces_last_spike_time_1_ce0;
input  [15:0] post_traces_last_spike_time_1_q0;
output  [6:0] post_traces_trace_0_address0;
output   post_traces_trace_0_ce0;
input  [7:0] post_traces_trace_0_q0;
output  [6:0] post_traces_last_spike_time_0_address0;
output   post_traces_last_spike_time_0_ce0;
input  [15:0] post_traces_last_spike_time_0_q0;
output  [14:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [14:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
output   p_ZL13weight_memory_0_we1;
output  [7:0] p_ZL13weight_memory_0_d1;
output  [14:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [14:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
output   p_ZL13weight_memory_1_we1;
output  [7:0] p_ZL13weight_memory_1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] trunc_ln356_fu_181_p1;
reg   [0:0] trunc_ln356_reg_318;
reg   [6:0] pre_traces_trace_0_addr_reg_324;
reg   [6:0] pre_traces_trace_1_addr_reg_330;
reg   [6:0] pre_traces_last_spike_time_0_addr_reg_336;
reg   [6:0] pre_traces_last_spike_time_1_addr_reg_342;
wire   [15:0] old_pre_last_spike_time_fu_203_p3;
reg   [15:0] old_pre_last_spike_time_reg_348;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln321_fu_225_p2;
reg   [0:0] icmp_ln321_reg_360;
wire   [7:0] old_pre_trace_fu_236_p3;
reg   [7:0] old_pre_trace_reg_370;
wire    ap_CS_fsm_state4;
reg   [7:0] EXP_DECAY_LUT_load_reg_376;
wire   [7:0] select_ln361_fu_305_p3;
reg   [7:0] select_ln361_reg_381;
wire    ap_CS_fsm_state5;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_idle;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_ready;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_ce0;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_ce0;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_ce0;
wire   [6:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_ce0;
wire   [14:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce0;
wire   [14:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address1;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce1;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_we1;
wire   [7:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_d1;
wire   [14:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address0;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce0;
wire   [14:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address1;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce1;
wire    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_we1;
wire   [7:0] grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_d1;
reg    grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [63:0] zext_ln356_fu_195_p1;
wire   [63:0] zext_ln325_1_fu_231_p1;
reg    pre_traces_last_spike_time_0_ce0_local;
reg    pre_traces_last_spike_time_0_we1_local;
reg    pre_traces_last_spike_time_0_ce1_local;
reg    pre_traces_last_spike_time_1_ce0_local;
reg    pre_traces_last_spike_time_1_we1_local;
reg    pre_traces_last_spike_time_1_ce1_local;
reg    pre_traces_trace_0_ce0_local;
reg    pre_traces_trace_0_we1_local;
wire    ap_CS_fsm_state6;
reg    pre_traces_trace_0_ce1_local;
reg    pre_traces_trace_1_ce0_local;
reg    pre_traces_trace_1_we1_local;
reg    pre_traces_trace_1_ce1_local;
reg    EXP_DECAY_LUT_ce0_local;
wire   [6:0] lshr_ln_fu_185_p4;
wire   [15:0] dt_fu_210_p2;
wire   [11:0] tmp_fu_215_p4;
wire   [7:0] mul_ln325_fu_254_p0;
wire   [7:0] mul_ln325_fu_254_p1;
wire   [15:0] mul_ln325_fu_254_p2;
wire   [0:0] icmp_ln315_fu_243_p2;
wire   [0:0] or_ln321_fu_270_p2;
wire   [7:0] decayed_pre_fu_260_p4;
wire   [7:0] decayed_pre_1_fu_275_p3;
wire   [8:0] zext_ln360_fu_283_p1;
wire   [8:0] new_trace_fu_287_p2;
wire   [0:0] tmp_56_fu_293_p3;
wire   [7:0] trunc_ln361_fu_301_p1;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire   [15:0] mul_ln325_fu_254_p00;
wire   [15:0] mul_ln325_fu_254_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg = 1'b0;
end

snn_top_hls_process_pre_spike_aer_Pipeline_LTD_LOOP grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start),
    .ap_done(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done),
    .ap_idle(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_idle),
    .ap_ready(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_ready),
    .current_time(current_time),
    .pre_id(pre_id),
    .post_traces_trace_1_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_address0),
    .post_traces_trace_1_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_ce0),
    .post_traces_trace_1_q0(post_traces_trace_1_q0),
    .post_traces_last_spike_time_1_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_address0),
    .post_traces_last_spike_time_1_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_ce0),
    .post_traces_last_spike_time_1_q0(post_traces_last_spike_time_1_q0),
    .post_traces_trace_0_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_address0),
    .post_traces_trace_0_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_ce0),
    .post_traces_trace_0_q0(post_traces_trace_0_q0),
    .post_traces_last_spike_time_0_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_address0),
    .post_traces_last_spike_time_0_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_ce0),
    .post_traces_last_spike_time_0_q0(post_traces_last_spike_time_0_q0),
    .p_ZL13weight_memory_0_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address0),
    .p_ZL13weight_memory_0_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce0),
    .p_ZL13weight_memory_0_q0(p_ZL13weight_memory_0_q0),
    .p_ZL13weight_memory_0_address1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address1),
    .p_ZL13weight_memory_0_ce1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce1),
    .p_ZL13weight_memory_0_we1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_we1),
    .p_ZL13weight_memory_0_d1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_d1),
    .p_ZL13weight_memory_1_address0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address0),
    .p_ZL13weight_memory_1_ce0(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce0),
    .p_ZL13weight_memory_1_q0(p_ZL13weight_memory_1_q0),
    .p_ZL13weight_memory_1_address1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address1),
    .p_ZL13weight_memory_1_ce1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce1),
    .p_ZL13weight_memory_1_we1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_we1),
    .p_ZL13weight_memory_1_d1(grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_d1)
);

snn_top_hls_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U102(
    .din0(mul_ln325_fu_254_p0),
    .din1(mul_ln325_fu_254_p1),
    .dout(mul_ln325_fu_254_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg <= 1'b1;
        end else if ((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_ready == 1'b1)) begin
            grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        EXP_DECAY_LUT_load_reg_376 <= EXP_DECAY_LUT_q0;
        old_pre_trace_reg_370 <= old_pre_trace_fu_236_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln321_reg_360 <= icmp_ln321_fu_225_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        old_pre_last_spike_time_reg_348 <= old_pre_last_spike_time_fu_203_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        pre_traces_last_spike_time_0_addr_reg_336 <= zext_ln356_fu_195_p1;
        pre_traces_last_spike_time_1_addr_reg_342 <= zext_ln356_fu_195_p1;
        pre_traces_trace_0_addr_reg_324 <= zext_ln356_fu_195_p1;
        pre_traces_trace_1_addr_reg_330 <= zext_ln356_fu_195_p1;
        trunc_ln356_reg_318 <= trunc_ln356_fu_181_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        select_ln361_reg_381 <= select_ln361_fu_305_p3;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        EXP_DECAY_LUT_ce0_local = 1'b1;
    end else begin
        EXP_DECAY_LUT_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((1'b1 == ap_CS_fsm_state8) & (grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pre_traces_last_spike_time_0_ce0_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        pre_traces_last_spike_time_0_ce1_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (trunc_ln356_reg_318 == 1'd0))) begin
        pre_traces_last_spike_time_0_we1_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        pre_traces_last_spike_time_1_ce0_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        pre_traces_last_spike_time_1_ce1_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (trunc_ln356_reg_318 == 1'd1))) begin
        pre_traces_last_spike_time_1_we1_local = 1'b1;
    end else begin
        pre_traces_last_spike_time_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pre_traces_trace_0_ce0_local = 1'b1;
    end else begin
        pre_traces_trace_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pre_traces_trace_0_ce1_local = 1'b1;
    end else begin
        pre_traces_trace_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln356_reg_318 == 1'd0))) begin
        pre_traces_trace_0_we1_local = 1'b1;
    end else begin
        pre_traces_trace_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pre_traces_trace_1_ce0_local = 1'b1;
    end else begin
        pre_traces_trace_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pre_traces_trace_1_ce1_local = 1'b1;
    end else begin
        pre_traces_trace_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln356_reg_318 == 1'd1))) begin
        pre_traces_trace_1_we1_local = 1'b1;
    end else begin
        pre_traces_trace_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign EXP_DECAY_LUT_address0 = zext_ln325_1_fu_231_p1;

assign EXP_DECAY_LUT_ce0 = EXP_DECAY_LUT_ce0_local;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign decayed_pre_1_fu_275_p3 = ((or_ln321_fu_270_p2[0:0] == 1'b1) ? 8'd0 : decayed_pre_fu_260_p4);

assign decayed_pre_fu_260_p4 = {{mul_ln325_fu_254_p2[15:8]}};

assign dt_fu_210_p2 = (current_time - old_pre_last_spike_time_reg_348);

assign grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_ap_start_reg;

assign icmp_ln315_fu_243_p2 = ((old_pre_trace_reg_370 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_225_p2 = ((tmp_fu_215_p4 != 12'd0) ? 1'b1 : 1'b0);

assign lshr_ln_fu_185_p4 = {{pre_id[7:1]}};

assign mul_ln325_fu_254_p0 = mul_ln325_fu_254_p00;

assign mul_ln325_fu_254_p00 = EXP_DECAY_LUT_load_reg_376;

assign mul_ln325_fu_254_p1 = mul_ln325_fu_254_p10;

assign mul_ln325_fu_254_p10 = old_pre_trace_reg_370;

assign new_trace_fu_287_p2 = (zext_ln360_fu_283_p1 + 9'd128);

assign old_pre_last_spike_time_fu_203_p3 = ((trunc_ln356_reg_318[0:0] == 1'b1) ? pre_traces_last_spike_time_1_q0 : pre_traces_last_spike_time_0_q0);

assign old_pre_trace_fu_236_p3 = ((trunc_ln356_reg_318[0:0] == 1'b1) ? pre_traces_trace_1_q0 : pre_traces_trace_0_q0);

assign or_ln321_fu_270_p2 = (icmp_ln321_reg_360 | icmp_ln315_fu_243_p2);

assign p_ZL13weight_memory_0_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address0;

assign p_ZL13weight_memory_0_address1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_address1;

assign p_ZL13weight_memory_0_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce0;

assign p_ZL13weight_memory_0_ce1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_ce1;

assign p_ZL13weight_memory_0_d1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_d1;

assign p_ZL13weight_memory_0_we1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_0_we1;

assign p_ZL13weight_memory_1_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address0;

assign p_ZL13weight_memory_1_address1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_address1;

assign p_ZL13weight_memory_1_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce0;

assign p_ZL13weight_memory_1_ce1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_ce1;

assign p_ZL13weight_memory_1_d1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_d1;

assign p_ZL13weight_memory_1_we1 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_p_ZL13weight_memory_1_we1;

assign post_traces_last_spike_time_0_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_address0;

assign post_traces_last_spike_time_0_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_0_ce0;

assign post_traces_last_spike_time_1_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_address0;

assign post_traces_last_spike_time_1_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_last_spike_time_1_ce0;

assign post_traces_trace_0_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_address0;

assign post_traces_trace_0_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_0_ce0;

assign post_traces_trace_1_address0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_address0;

assign post_traces_trace_1_ce0 = grp_process_pre_spike_aer_Pipeline_LTD_LOOP_fu_161_post_traces_trace_1_ce0;

assign pre_traces_last_spike_time_0_address0 = zext_ln356_fu_195_p1;

assign pre_traces_last_spike_time_0_address1 = pre_traces_last_spike_time_0_addr_reg_336;

assign pre_traces_last_spike_time_0_ce0 = pre_traces_last_spike_time_0_ce0_local;

assign pre_traces_last_spike_time_0_ce1 = pre_traces_last_spike_time_0_ce1_local;

assign pre_traces_last_spike_time_0_d1 = current_time;

assign pre_traces_last_spike_time_0_we1 = pre_traces_last_spike_time_0_we1_local;

assign pre_traces_last_spike_time_1_address0 = zext_ln356_fu_195_p1;

assign pre_traces_last_spike_time_1_address1 = pre_traces_last_spike_time_1_addr_reg_342;

assign pre_traces_last_spike_time_1_ce0 = pre_traces_last_spike_time_1_ce0_local;

assign pre_traces_last_spike_time_1_ce1 = pre_traces_last_spike_time_1_ce1_local;

assign pre_traces_last_spike_time_1_d1 = current_time;

assign pre_traces_last_spike_time_1_we1 = pre_traces_last_spike_time_1_we1_local;

assign pre_traces_trace_0_address0 = pre_traces_trace_0_addr_reg_324;

assign pre_traces_trace_0_address1 = pre_traces_trace_0_addr_reg_324;

assign pre_traces_trace_0_ce0 = pre_traces_trace_0_ce0_local;

assign pre_traces_trace_0_ce1 = pre_traces_trace_0_ce1_local;

assign pre_traces_trace_0_d1 = select_ln361_reg_381;

assign pre_traces_trace_0_we1 = pre_traces_trace_0_we1_local;

assign pre_traces_trace_1_address0 = pre_traces_trace_1_addr_reg_330;

assign pre_traces_trace_1_address1 = pre_traces_trace_1_addr_reg_330;

assign pre_traces_trace_1_ce0 = pre_traces_trace_1_ce0_local;

assign pre_traces_trace_1_ce1 = pre_traces_trace_1_ce1_local;

assign pre_traces_trace_1_d1 = select_ln361_reg_381;

assign pre_traces_trace_1_we1 = pre_traces_trace_1_we1_local;

assign select_ln361_fu_305_p3 = ((tmp_56_fu_293_p3[0:0] == 1'b1) ? 8'd255 : trunc_ln361_fu_301_p1);

assign tmp_56_fu_293_p3 = new_trace_fu_287_p2[32'd8];

assign tmp_fu_215_p4 = {{dt_fu_210_p2[15:4]}};

assign trunc_ln356_fu_181_p1 = pre_id[0:0];

assign trunc_ln361_fu_301_p1 = new_trace_fu_287_p2[7:0];

assign zext_ln325_1_fu_231_p1 = dt_fu_210_p2;

assign zext_ln356_fu_195_p1 = lshr_ln_fu_185_p4;

assign zext_ln360_fu_283_p1 = decayed_pre_1_fu_275_p3;

endmodule //snn_top_hls_process_pre_spike_aer
