[hls]
relative_roots=/mnt/workspace/Event-Driven-Spiking-Neural-Network-Accelerator-for-FPGA/hardware/hls
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=run_encoder_once/ENCODER_LOOP 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=snn_top_hls/INIT_WEIGHT_OUTER  
syn.directive.array_partition=snn_top_hls/encoder_frame dim=1 type=cyclic factor=2 variable=encoder_frame


