[hls]
relative_roots=/home/chipwisperer/Documents/SNN/Event-Driven-Spiking-Neural-Network-Accelerator-for-FPGA/hardware/hls
# Inferred from syn.array_partition.complete_threshold=4
syn.directive.array_partition=snn_top_hls/CONNECTION_TABLE (.src_size) dim=1 type=complete variable=CONNECTION_TABLE (.src_size)
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=snn_top_hls/VITIS_LOOP_70_1 
syn.directive.pipeline=snn_top_hls/VITIS_LOOP_76_3 
syn.directive.pipeline=snn_top_hls/VITIS_LOOP_89_9 
syn.directive.pipeline=snn_top_hls/VITIS_LOOP_84_7 
syn.directive.pipeline=snn_top_hls/VITIS_LOOP_148_5 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=snn_top_hls/VITIS_LOOP_83_6  
syn.directive.loop_flatten=snn_top_hls/VITIS_LOOP_88_8  
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=snn_top_hls/encoder_frame dim=1 type=cyclic factor=2 variable=encoder_frame


