[hls]
relative_roots=/home/chipwisperer/Documents/SNN/Event-Driven-Spiking-Neural-Network-Accelerator-for-FPGA/hardware/hls
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=snn_top_hls/encoder_frame dim=1 type=cyclic factor=2 variable=encoder_frame


