// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module snn_top_hls_snn_top_hls_Pipeline_WEIGHT_SUM (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        weight_sum_out,
        weight_sum_out_ap_vld,
        p_ZL13weight_memory_0_address0,
        p_ZL13weight_memory_0_ce0,
        p_ZL13weight_memory_0_q0,
        p_ZL13weight_memory_0_address1,
        p_ZL13weight_memory_0_ce1,
        p_ZL13weight_memory_0_q1,
        p_ZL13weight_memory_1_address0,
        p_ZL13weight_memory_1_ce0,
        p_ZL13weight_memory_1_q0,
        p_ZL13weight_memory_1_address1,
        p_ZL13weight_memory_1_ce1,
        p_ZL13weight_memory_1_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] weight_sum_out;
output   weight_sum_out_ap_vld;
output  [14:0] p_ZL13weight_memory_0_address0;
output   p_ZL13weight_memory_0_ce0;
input  [7:0] p_ZL13weight_memory_0_q0;
output  [14:0] p_ZL13weight_memory_0_address1;
output   p_ZL13weight_memory_0_ce1;
input  [7:0] p_ZL13weight_memory_0_q1;
output  [14:0] p_ZL13weight_memory_1_address0;
output   p_ZL13weight_memory_1_ce0;
input  [7:0] p_ZL13weight_memory_1_q0;
output  [14:0] p_ZL13weight_memory_1_address1;
output   p_ZL13weight_memory_1_ce1;
input  [7:0] p_ZL13weight_memory_1_q1;

reg ap_idle;
reg weight_sum_out_ap_vld;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln949_reg_374;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln949_fu_166_p2;
wire   [2:0] trunc_ln949_fu_178_p1;
reg   [2:0] trunc_ln949_reg_378;
wire    ap_block_pp0_stage1_11001;
wire   [9:0] add_ln952_2_fu_277_p2;
reg   [9:0] add_ln952_2_reg_424;
wire   [9:0] add_ln952_5_fu_319_p2;
reg   [9:0] add_ln952_5_reg_429;
wire   [63:0] zext_ln952_fu_190_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln952_1_fu_204_p1;
wire   [63:0] zext_ln952_2_fu_222_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln952_3_fu_235_p1;
reg   [13:0] weight_sum_fu_56;
wire   [13:0] weight_sum_1_fu_344_p2;
wire    ap_loop_init;
reg   [3:0] i_fu_60;
wire   [3:0] add_ln949_fu_172_p2;
reg   [3:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage1_01001;
reg    p_ZL13weight_memory_0_ce1_local;
reg   [14:0] p_ZL13weight_memory_0_address1_local;
reg    p_ZL13weight_memory_0_ce0_local;
reg   [14:0] p_ZL13weight_memory_0_address0_local;
reg    p_ZL13weight_memory_1_ce1_local;
reg   [14:0] p_ZL13weight_memory_1_address1_local;
reg    p_ZL13weight_memory_1_ce0_local;
reg   [14:0] p_ZL13weight_memory_1_address0_local;
wire   [9:0] tmp_s_fu_182_p3;
wire   [9:0] tmp_1_fu_196_p3;
wire   [9:0] tmp_2_fu_215_p3;
wire   [9:0] tmp_3_fu_228_p3;
wire  signed [8:0] sext_ln952_fu_241_p1;
wire  signed [8:0] sext_ln952_1_fu_245_p1;
wire   [8:0] add_ln952_fu_257_p2;
wire  signed [8:0] sext_ln952_2_fu_249_p1;
wire  signed [8:0] sext_ln952_3_fu_253_p1;
wire   [8:0] add_ln952_1_fu_267_p2;
wire  signed [9:0] sext_ln952_9_fu_273_p1;
wire  signed [9:0] sext_ln952_8_fu_263_p1;
wire  signed [8:0] sext_ln952_4_fu_283_p1;
wire  signed [8:0] sext_ln952_5_fu_287_p1;
wire   [8:0] add_ln952_3_fu_299_p2;
wire  signed [8:0] sext_ln952_6_fu_291_p1;
wire  signed [8:0] sext_ln952_7_fu_295_p1;
wire   [8:0] add_ln952_4_fu_309_p2;
wire  signed [9:0] sext_ln952_12_fu_315_p1;
wire  signed [9:0] sext_ln952_11_fu_305_p1;
wire  signed [10:0] sext_ln952_13_fu_331_p1;
wire  signed [10:0] sext_ln952_10_fu_328_p1;
wire   [10:0] add_ln952_6_fu_334_p2;
wire  signed [13:0] sext_ln952_14_fu_340_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 weight_sum_fu_56 = 14'd0;
#0 i_fu_60 = 4'd0;
#0 ap_done_reg = 1'b0;
end

snn_top_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln949_fu_166_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_60 <= add_ln949_fu_172_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_60 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        weight_sum_fu_56 <= 14'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_sum_fu_56 <= weight_sum_1_fu_344_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln952_2_reg_424 <= add_ln952_2_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln952_5_reg_429 <= add_ln952_5_fu_319_p2;
        icmp_ln949_reg_374 <= icmp_ln949_fu_166_p2;
        trunc_ln949_reg_378 <= trunc_ln949_fu_178_p1;
    end
end

always @ (*) begin
    if (((icmp_ln949_reg_374 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_60;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL13weight_memory_0_address0_local = zext_ln952_3_fu_235_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_0_address0_local = zext_ln952_1_fu_204_p1;
    end else begin
        p_ZL13weight_memory_0_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL13weight_memory_0_address1_local = zext_ln952_2_fu_222_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_0_address1_local = zext_ln952_fu_190_p1;
    end else begin
        p_ZL13weight_memory_0_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL13weight_memory_0_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL13weight_memory_0_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL13weight_memory_1_address0_local = zext_ln952_3_fu_235_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_1_address0_local = zext_ln952_1_fu_204_p1;
    end else begin
        p_ZL13weight_memory_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        p_ZL13weight_memory_1_address1_local = zext_ln952_2_fu_222_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL13weight_memory_1_address1_local = zext_ln952_fu_190_p1;
    end else begin
        p_ZL13weight_memory_1_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL13weight_memory_1_ce0_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        p_ZL13weight_memory_1_ce1_local = 1'b1;
    end else begin
        p_ZL13weight_memory_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln949_reg_374 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        weight_sum_out_ap_vld = 1'b1;
    end else begin
        weight_sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln949_fu_172_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign add_ln952_1_fu_267_p2 = ($signed(sext_ln952_2_fu_249_p1) + $signed(sext_ln952_3_fu_253_p1));

assign add_ln952_2_fu_277_p2 = ($signed(sext_ln952_9_fu_273_p1) + $signed(sext_ln952_8_fu_263_p1));

assign add_ln952_3_fu_299_p2 = ($signed(sext_ln952_4_fu_283_p1) + $signed(sext_ln952_5_fu_287_p1));

assign add_ln952_4_fu_309_p2 = ($signed(sext_ln952_6_fu_291_p1) + $signed(sext_ln952_7_fu_295_p1));

assign add_ln952_5_fu_319_p2 = ($signed(sext_ln952_12_fu_315_p1) + $signed(sext_ln952_11_fu_305_p1));

assign add_ln952_6_fu_334_p2 = ($signed(sext_ln952_13_fu_331_p1) + $signed(sext_ln952_10_fu_328_p1));

assign add_ln952_fu_257_p2 = ($signed(sext_ln952_fu_241_p1) + $signed(sext_ln952_1_fu_245_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln949_fu_166_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign p_ZL13weight_memory_0_address0 = p_ZL13weight_memory_0_address0_local;

assign p_ZL13weight_memory_0_address1 = p_ZL13weight_memory_0_address1_local;

assign p_ZL13weight_memory_0_ce0 = p_ZL13weight_memory_0_ce0_local;

assign p_ZL13weight_memory_0_ce1 = p_ZL13weight_memory_0_ce1_local;

assign p_ZL13weight_memory_1_address0 = p_ZL13weight_memory_1_address0_local;

assign p_ZL13weight_memory_1_address1 = p_ZL13weight_memory_1_address1_local;

assign p_ZL13weight_memory_1_ce0 = p_ZL13weight_memory_1_ce0_local;

assign p_ZL13weight_memory_1_ce1 = p_ZL13weight_memory_1_ce1_local;

assign sext_ln952_10_fu_328_p1 = $signed(add_ln952_2_reg_424);

assign sext_ln952_11_fu_305_p1 = $signed(add_ln952_3_fu_299_p2);

assign sext_ln952_12_fu_315_p1 = $signed(add_ln952_4_fu_309_p2);

assign sext_ln952_13_fu_331_p1 = $signed(add_ln952_5_reg_429);

assign sext_ln952_14_fu_340_p1 = $signed(add_ln952_6_fu_334_p2);

assign sext_ln952_1_fu_245_p1 = $signed(p_ZL13weight_memory_1_q1);

assign sext_ln952_2_fu_249_p1 = $signed(p_ZL13weight_memory_0_q0);

assign sext_ln952_3_fu_253_p1 = $signed(p_ZL13weight_memory_1_q0);

assign sext_ln952_4_fu_283_p1 = $signed(p_ZL13weight_memory_0_q1);

assign sext_ln952_5_fu_287_p1 = $signed(p_ZL13weight_memory_1_q1);

assign sext_ln952_6_fu_291_p1 = $signed(p_ZL13weight_memory_0_q0);

assign sext_ln952_7_fu_295_p1 = $signed(p_ZL13weight_memory_1_q0);

assign sext_ln952_8_fu_263_p1 = $signed(add_ln952_fu_257_p2);

assign sext_ln952_9_fu_273_p1 = $signed(add_ln952_1_fu_267_p2);

assign sext_ln952_fu_241_p1 = $signed(p_ZL13weight_memory_0_q1);

assign tmp_1_fu_196_p3 = {{trunc_ln949_fu_178_p1}, {7'd1}};

assign tmp_2_fu_215_p3 = {{trunc_ln949_reg_378}, {7'd2}};

assign tmp_3_fu_228_p3 = {{trunc_ln949_reg_378}, {7'd3}};

assign tmp_s_fu_182_p3 = {{trunc_ln949_fu_178_p1}, {7'd0}};

assign trunc_ln949_fu_178_p1 = ap_sig_allocacmp_i_1[2:0];

assign weight_sum_1_fu_344_p2 = ($signed(weight_sum_fu_56) + $signed(sext_ln952_14_fu_340_p1));

assign weight_sum_out = weight_sum_fu_56;

assign zext_ln952_1_fu_204_p1 = tmp_1_fu_196_p3;

assign zext_ln952_2_fu_222_p1 = tmp_2_fu_215_p3;

assign zext_ln952_3_fu_235_p1 = tmp_3_fu_228_p3;

assign zext_ln952_fu_190_p1 = tmp_s_fu_182_p3;

endmodule //snn_top_hls_snn_top_hls_Pipeline_WEIGHT_SUM
