-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (8 downto 0);
    sext_ln487 : IN STD_LOGIC_VECTOR (7 downto 0);
    icmp_ln491 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln491_1 : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln491_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_59 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    p_ZL16post_eligibility_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL16post_eligibility_3_ce0 : OUT STD_LOGIC;
    p_ZL16post_eligibility_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL16post_eligibility_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL16post_eligibility_2_ce0 : OUT STD_LOGIC;
    p_ZL16post_eligibility_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL16post_eligibility_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL16post_eligibility_1_ce0 : OUT STD_LOGIC;
    p_ZL16post_eligibility_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL16post_eligibility_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL16post_eligibility_0_ce0 : OUT STD_LOGIC;
    p_ZL16post_eligibility_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_0_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_0_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_0_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_0_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_0_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_0_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_0_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_1_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_1_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_1_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_1_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_1_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_1_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_2_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_2_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_2_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_2_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_2_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_2_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_2_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_2_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_3_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_0_3_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_0_3_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_3_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_0_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_3_ce0 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL13weight_memory_1_3_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    p_ZL13weight_memory_1_3_ce1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_3_we1 : OUT STD_LOGIC;
    p_ZL13weight_memory_1_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_apply_rstdp_reward_Pipeline_RSTDP_INNER is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv9_180 : STD_LOGIC_VECTOR (8 downto 0) := "110000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_72_fu_382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal tmp_reg_1186 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal sext_ln487_cast_fu_370_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln487_cast_reg_1231 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln_fu_390_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln_reg_1243 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln_reg_1243_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal post_elig_reg_1268 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_reg_1273 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_reg_1273_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_reg_1273_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal post_elig_1_reg_1277 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_1_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_1_reg_1282 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_1_reg_1282_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_1_reg_1282_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal post_elig_2_reg_1286 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_2_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_2_reg_1291 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_2_reg_1291_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_2_reg_1291_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal post_elig_3_reg_1295 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_3_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_3_reg_1300 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_3_reg_1300_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln484_3_reg_1300_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL13weight_memory_0_0_addr_reg_1304 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_0_addr_reg_1304_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_1_addr_reg_1310 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_1_addr_reg_1310_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_2_addr_reg_1316 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_2_addr_reg_1316_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_3_addr_reg_1322 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_0_3_addr_reg_1322_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_0_addr_reg_1328 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_0_addr_reg_1328_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_1_addr_reg_1334 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_1_addr_reg_1334_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_2_addr_reg_1340 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_2_addr_reg_1340_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_3_addr_reg_1346 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL13weight_memory_1_3_addr_reg_1346_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal scaled_4_fu_538_p11 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_reg_1352 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p11 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_reg_1357 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p11 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_reg_1362 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p11 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_reg_1367 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln503_fu_866_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln503_reg_1372 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_fu_872_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal w_reg_1377 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_74_reg_1382 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln503_2_fu_919_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln503_2_reg_1387 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_5_fu_925_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal w_5_reg_1392 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_75_reg_1397 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln503_4_fu_972_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln503_4_reg_1402 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_6_fu_978_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal w_6_reg_1407 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_76_reg_1412 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln503_6_fu_1025_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln503_6_reg_1417 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_7_fu_1031_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal w_7_reg_1422 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_77_reg_1427 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln479_fu_400_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln502_fu_459_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_136 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln479_fu_408_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL16post_eligibility_0_ce0_local : STD_LOGIC;
    signal p_ZL16post_eligibility_1_ce0_local : STD_LOGIC;
    signal p_ZL16post_eligibility_2_ce0_local : STD_LOGIC;
    signal p_ZL16post_eligibility_3_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_0_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_0_we1_local : STD_LOGIC;
    signal select_ln335_fu_1071_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_0_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_0_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_0_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_0_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_1_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_1_we1_local : STD_LOGIC;
    signal select_ln335_5_fu_1104_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_1_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_1_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_1_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_1_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_2_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_2_we1_local : STD_LOGIC;
    signal select_ln335_6_fu_1137_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_2_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_2_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_2_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_2_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_3_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_0_3_we1_local : STD_LOGIC;
    signal select_ln335_7_fu_1170_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL13weight_memory_0_3_ce1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_3_ce0_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_3_we1_local : STD_LOGIC;
    signal p_ZL13weight_memory_1_3_ce1_local : STD_LOGIC;
    signal icmp_ln484_fu_419_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_1_fu_425_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_2_fu_431_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln484_3_fu_437_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_73_fu_443_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_452_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal mul_ln487_fu_474_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln487_fu_474_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal scaled_fu_479_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal scaled_2_fu_503_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal scaled_3_fu_517_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal scaled_4_fu_538_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_fu_538_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_fu_538_p6 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_fu_538_p8 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_fu_538_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_4_fu_538_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln487_1_fu_565_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln487_1_fu_565_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal scaled_5_fu_570_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal scaled_7_fu_594_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal scaled_8_fu_608_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal scaled_9_fu_629_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p6 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p8 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_9_fu_629_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln487_2_fu_656_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln487_2_fu_656_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal scaled_10_fu_661_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal scaled_12_fu_685_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal scaled_13_fu_699_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal scaled_14_fu_720_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p6 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p8 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_14_fu_720_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln487_3_fu_747_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln487_3_fu_747_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal scaled_15_fu_752_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal scaled_17_fu_776_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal scaled_18_fu_790_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal scaled_19_fu_811_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p6 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p8 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p9 : STD_LOGIC_VECTOR (6 downto 0);
    signal scaled_19_fu_811_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal sext_ln490_3_fu_835_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_fu_838_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_1_fu_844_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_fu_855_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln499_fu_851_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln503_fu_862_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln490_7_fu_888_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_2_fu_891_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_3_fu_897_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_5_fu_908_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln499_1_fu_904_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln503_1_fu_915_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln490_11_fu_941_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_4_fu_944_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_5_fu_950_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_6_fu_961_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln499_2_fu_957_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln503_2_fu_968_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln490_15_fu_994_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_6_fu_997_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal delta_7_fu_1003_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal current_w_7_fu_1014_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln499_3_fu_1010_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln503_3_fu_1021_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln335_fu_1047_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln336_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln335_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln335_8_fu_1057_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln335_2_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln336_4_fu_1085_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln335_1_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln335_9_fu_1090_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln335_3_fu_1113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln336_5_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln335_2_fu_1131_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln335_10_fu_1123_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln335_4_fu_1146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln336_6_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln335_3_fu_1164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln335_11_fu_1156_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal scaled_4_fu_538_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_4_fu_538_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_4_fu_538_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_4_fu_538_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_9_fu_629_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_9_fu_629_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_9_fu_629_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_9_fu_629_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_14_fu_720_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_14_fu_720_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_14_fu_720_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_14_fu_720_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_19_fu_811_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_19_fu_811_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_19_fu_811_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal scaled_19_fu_811_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_mul_8s_8s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component snn_top_hls_sparsemux_9_3_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        din3 : IN STD_LOGIC_VECTOR (6 downto 0);
        def : IN STD_LOGIC_VECTOR (6 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8s_8s_16_1_1_U228 : component snn_top_hls_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => post_elig_reg_1268,
        din1 => mul_ln487_fu_474_p1,
        dout => mul_ln487_fu_474_p2);

    sparsemux_9_3_7_1_1_U229 : component snn_top_hls_sparsemux_9_3_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 7,
        CASE1 => "010",
        din1_WIDTH => 7,
        CASE2 => "001",
        din2_WIDTH => 7,
        CASE3 => "000",
        din3_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 3,
        dout_WIDTH => 7)
    port map (
        din0 => scaled_4_fu_538_p2,
        din1 => scaled_4_fu_538_p4,
        din2 => scaled_4_fu_538_p6,
        din3 => scaled_4_fu_538_p8,
        def => scaled_4_fu_538_p9,
        sel => scaled_4_fu_538_p10,
        dout => scaled_4_fu_538_p11);

    mul_8s_8s_16_1_1_U230 : component snn_top_hls_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => post_elig_1_reg_1277,
        din1 => mul_ln487_1_fu_565_p1,
        dout => mul_ln487_1_fu_565_p2);

    sparsemux_9_3_7_1_1_U231 : component snn_top_hls_sparsemux_9_3_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 7,
        CASE1 => "010",
        din1_WIDTH => 7,
        CASE2 => "001",
        din2_WIDTH => 7,
        CASE3 => "000",
        din3_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 3,
        dout_WIDTH => 7)
    port map (
        din0 => scaled_9_fu_629_p2,
        din1 => scaled_9_fu_629_p4,
        din2 => scaled_9_fu_629_p6,
        din3 => scaled_9_fu_629_p8,
        def => scaled_9_fu_629_p9,
        sel => scaled_9_fu_629_p10,
        dout => scaled_9_fu_629_p11);

    mul_8s_8s_16_1_1_U232 : component snn_top_hls_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => post_elig_2_reg_1286,
        din1 => mul_ln487_2_fu_656_p1,
        dout => mul_ln487_2_fu_656_p2);

    sparsemux_9_3_7_1_1_U233 : component snn_top_hls_sparsemux_9_3_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 7,
        CASE1 => "010",
        din1_WIDTH => 7,
        CASE2 => "001",
        din2_WIDTH => 7,
        CASE3 => "000",
        din3_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 3,
        dout_WIDTH => 7)
    port map (
        din0 => scaled_14_fu_720_p2,
        din1 => scaled_14_fu_720_p4,
        din2 => scaled_14_fu_720_p6,
        din3 => scaled_14_fu_720_p8,
        def => scaled_14_fu_720_p9,
        sel => scaled_14_fu_720_p10,
        dout => scaled_14_fu_720_p11);

    mul_8s_8s_16_1_1_U234 : component snn_top_hls_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => post_elig_3_reg_1295,
        din1 => mul_ln487_3_fu_747_p1,
        dout => mul_ln487_3_fu_747_p2);

    sparsemux_9_3_7_1_1_U235 : component snn_top_hls_sparsemux_9_3_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 7,
        CASE1 => "010",
        din1_WIDTH => 7,
        CASE2 => "001",
        din2_WIDTH => 7,
        CASE3 => "000",
        din3_WIDTH => 7,
        def_WIDTH => 7,
        sel_WIDTH => 3,
        dout_WIDTH => 7)
    port map (
        din0 => scaled_19_fu_811_p2,
        din1 => scaled_19_fu_811_p4,
        din2 => scaled_19_fu_811_p6,
        din3 => scaled_19_fu_811_p8,
        def => scaled_19_fu_811_p9,
        sel => scaled_19_fu_811_p10,
        dout => scaled_19_fu_811_p11);

    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    j_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((tmp_72_fu_382_p3 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_136 <= add_ln479_fu_408_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_136 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln503_2_reg_1387 <= add_ln503_2_fu_919_p2;
                add_ln503_4_reg_1402 <= add_ln503_4_fu_972_p2;
                add_ln503_6_reg_1417 <= add_ln503_6_fu_1025_p2;
                add_ln503_reg_1372 <= add_ln503_fu_866_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln484_1_reg_1282_pp0_iter2_reg <= icmp_ln484_1_reg_1282;
                icmp_ln484_1_reg_1282_pp0_iter3_reg <= icmp_ln484_1_reg_1282_pp0_iter2_reg;
                icmp_ln484_2_reg_1291_pp0_iter2_reg <= icmp_ln484_2_reg_1291;
                icmp_ln484_2_reg_1291_pp0_iter3_reg <= icmp_ln484_2_reg_1291_pp0_iter2_reg;
                icmp_ln484_3_reg_1300_pp0_iter2_reg <= icmp_ln484_3_reg_1300;
                icmp_ln484_3_reg_1300_pp0_iter3_reg <= icmp_ln484_3_reg_1300_pp0_iter2_reg;
                icmp_ln484_reg_1273_pp0_iter2_reg <= icmp_ln484_reg_1273;
                icmp_ln484_reg_1273_pp0_iter3_reg <= icmp_ln484_reg_1273_pp0_iter2_reg;
                p_ZL13weight_memory_0_0_addr_reg_1304 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_0_0_addr_reg_1304_pp0_iter3_reg <= p_ZL13weight_memory_0_0_addr_reg_1304;
                p_ZL13weight_memory_0_1_addr_reg_1310 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_0_1_addr_reg_1310_pp0_iter3_reg <= p_ZL13weight_memory_0_1_addr_reg_1310;
                p_ZL13weight_memory_0_2_addr_reg_1316 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_0_2_addr_reg_1316_pp0_iter3_reg <= p_ZL13weight_memory_0_2_addr_reg_1316;
                p_ZL13weight_memory_0_3_addr_reg_1322 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_0_3_addr_reg_1322_pp0_iter3_reg <= p_ZL13weight_memory_0_3_addr_reg_1322;
                p_ZL13weight_memory_1_0_addr_reg_1328 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_1_0_addr_reg_1328_pp0_iter3_reg <= p_ZL13weight_memory_1_0_addr_reg_1328;
                p_ZL13weight_memory_1_1_addr_reg_1334 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_1_1_addr_reg_1334_pp0_iter3_reg <= p_ZL13weight_memory_1_1_addr_reg_1334;
                p_ZL13weight_memory_1_2_addr_reg_1340 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_1_2_addr_reg_1340_pp0_iter3_reg <= p_ZL13weight_memory_1_2_addr_reg_1340;
                p_ZL13weight_memory_1_3_addr_reg_1346 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
                p_ZL13weight_memory_1_3_addr_reg_1346_pp0_iter3_reg <= p_ZL13weight_memory_1_3_addr_reg_1346;
                scaled_14_reg_1362 <= scaled_14_fu_720_p11;
                scaled_19_reg_1367 <= scaled_19_fu_811_p11;
                scaled_4_reg_1352 <= scaled_4_fu_538_p11;
                scaled_9_reg_1357 <= scaled_9_fu_629_p11;
                tmp_74_reg_1382 <= w_fu_872_p2(8 downto 7);
                tmp_75_reg_1397 <= w_5_fu_925_p2(8 downto 7);
                tmp_76_reg_1412 <= w_6_fu_978_p2(8 downto 7);
                tmp_77_reg_1427 <= w_7_fu_1031_p2(8 downto 7);
                w_5_reg_1392 <= w_5_fu_925_p2;
                w_6_reg_1407 <= w_6_fu_978_p2;
                w_7_reg_1422 <= w_7_fu_1031_p2;
                w_reg_1377 <= w_fu_872_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln484_1_reg_1282 <= icmp_ln484_1_fu_425_p2;
                icmp_ln484_2_reg_1291 <= icmp_ln484_2_fu_431_p2;
                icmp_ln484_3_reg_1300 <= icmp_ln484_3_fu_437_p2;
                icmp_ln484_reg_1273 <= icmp_ln484_fu_419_p2;
                lshr_ln_reg_1243 <= ap_sig_allocacmp_j_3(8 downto 2);
                lshr_ln_reg_1243_pp0_iter1_reg <= lshr_ln_reg_1243;
                post_elig_1_reg_1277 <= p_ZL16post_eligibility_1_q0;
                post_elig_2_reg_1286 <= p_ZL16post_eligibility_2_q0;
                post_elig_3_reg_1295 <= p_ZL16post_eligibility_3_q0;
                post_elig_reg_1268 <= p_ZL16post_eligibility_0_q0;
                sext_ln487_cast_reg_1231 <= sext_ln487_cast_fu_370_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln479_fu_408_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_3) + unsigned(ap_const_lv10_4));
    add_ln503_2_fu_919_p2 <= std_logic_vector(signed(delta_3_fu_897_p3) + signed(current_w_5_fu_908_p3));
    add_ln503_4_fu_972_p2 <= std_logic_vector(signed(delta_5_fu_950_p3) + signed(current_w_6_fu_961_p3));
    add_ln503_6_fu_1025_p2 <= std_logic_vector(signed(delta_7_fu_1003_p3) + signed(current_w_7_fu_1014_p3));
    add_ln503_fu_866_p2 <= std_logic_vector(signed(delta_1_fu_844_p3) + signed(current_w_fu_855_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_72_fu_382_p3)
    begin
        if (((tmp_72_fu_382_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_136, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_3 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_j_3 <= j_fu_136;
        end if; 
    end process;

    current_w_5_fu_908_p3 <= 
        p_ZL13weight_memory_1_1_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_1_q0;
    current_w_6_fu_961_p3 <= 
        p_ZL13weight_memory_1_2_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_2_q0;
    current_w_7_fu_1014_p3 <= 
        p_ZL13weight_memory_1_3_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_3_q0;
    current_w_fu_855_p3 <= 
        p_ZL13weight_memory_1_0_q0 when (empty(0) = '1') else 
        p_ZL13weight_memory_0_0_q0;
    delta_1_fu_844_p3 <= 
        delta_fu_838_p2 when (empty_59(0) = '1') else 
        sext_ln490_3_fu_835_p1;
    delta_2_fu_891_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(sext_ln490_7_fu_888_p1));
    delta_3_fu_897_p3 <= 
        delta_2_fu_891_p2 when (empty_59(0) = '1') else 
        sext_ln490_7_fu_888_p1;
    delta_4_fu_944_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(sext_ln490_11_fu_941_p1));
    delta_5_fu_950_p3 <= 
        delta_4_fu_944_p2 when (empty_59(0) = '1') else 
        sext_ln490_11_fu_941_p1;
    delta_6_fu_997_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(sext_ln490_15_fu_994_p1));
    delta_7_fu_1003_p3 <= 
        delta_6_fu_997_p2 when (empty_59(0) = '1') else 
        sext_ln490_15_fu_994_p1;
    delta_fu_838_p2 <= std_logic_vector(unsigned(ap_const_lv8_0) - unsigned(sext_ln490_3_fu_835_p1));
    icmp_ln335_2_fu_1080_p2 <= "1" when (tmp_75_reg_1397 = ap_const_lv2_1) else "0";
    icmp_ln335_3_fu_1113_p2 <= "1" when (tmp_76_reg_1412 = ap_const_lv2_1) else "0";
    icmp_ln335_4_fu_1146_p2 <= "1" when (tmp_77_reg_1427 = ap_const_lv2_1) else "0";
    icmp_ln335_fu_1047_p2 <= "1" when (tmp_74_reg_1382 = ap_const_lv2_1) else "0";
    icmp_ln336_4_fu_1085_p2 <= "1" when (signed(w_5_reg_1392) < signed(ap_const_lv9_180)) else "0";
    icmp_ln336_5_fu_1118_p2 <= "1" when (signed(w_6_reg_1407) < signed(ap_const_lv9_180)) else "0";
    icmp_ln336_6_fu_1151_p2 <= "1" when (signed(w_7_reg_1422) < signed(ap_const_lv9_180)) else "0";
    icmp_ln336_fu_1052_p2 <= "1" when (signed(w_reg_1377) < signed(ap_const_lv9_180)) else "0";
    icmp_ln484_1_fu_425_p0 <= p_ZL16post_eligibility_1_q0;
    icmp_ln484_1_fu_425_p2 <= "1" when (icmp_ln484_1_fu_425_p0 = ap_const_lv8_0) else "0";
    icmp_ln484_2_fu_431_p0 <= p_ZL16post_eligibility_2_q0;
    icmp_ln484_2_fu_431_p2 <= "1" when (icmp_ln484_2_fu_431_p0 = ap_const_lv8_0) else "0";
    icmp_ln484_3_fu_437_p0 <= p_ZL16post_eligibility_3_q0;
    icmp_ln484_3_fu_437_p2 <= "1" when (icmp_ln484_3_fu_437_p0 = ap_const_lv8_0) else "0";
    icmp_ln484_fu_419_p0 <= p_ZL16post_eligibility_0_q0;
    icmp_ln484_fu_419_p2 <= "1" when (icmp_ln484_fu_419_p0 = ap_const_lv8_0) else "0";
    lshr_ln_fu_390_p4 <= ap_sig_allocacmp_j_3(8 downto 2);
    mul_ln487_1_fu_565_p1 <= sext_ln487_cast_reg_1231(8 - 1 downto 0);
    mul_ln487_2_fu_656_p1 <= sext_ln487_cast_reg_1231(8 - 1 downto 0);
    mul_ln487_3_fu_747_p1 <= sext_ln487_cast_reg_1231(8 - 1 downto 0);
    mul_ln487_fu_474_p1 <= sext_ln487_cast_reg_1231(8 - 1 downto 0);
    or_ln335_1_fu_1098_p2 <= (icmp_ln336_4_fu_1085_p2 or icmp_ln335_2_fu_1080_p2);
    or_ln335_2_fu_1131_p2 <= (icmp_ln336_5_fu_1118_p2 or icmp_ln335_3_fu_1113_p2);
    or_ln335_3_fu_1164_p2 <= (icmp_ln336_6_fu_1151_p2 or icmp_ln335_4_fu_1146_p2);
    or_ln335_fu_1065_p2 <= (icmp_ln336_fu_1052_p2 or icmp_ln335_fu_1047_p2);
    p_ZL13weight_memory_0_0_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_0_0_address1 <= p_ZL13weight_memory_0_0_addr_reg_1304_pp0_iter3_reg;
    p_ZL13weight_memory_0_0_ce0 <= p_ZL13weight_memory_0_0_ce0_local;

    p_ZL13weight_memory_0_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_0_ce1 <= p_ZL13weight_memory_0_0_ce1_local;

    p_ZL13weight_memory_0_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_0_d1 <= select_ln335_fu_1071_p3;
    p_ZL13weight_memory_0_0_we1 <= p_ZL13weight_memory_0_0_we1_local;

    p_ZL13weight_memory_0_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_reg_1273_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_reg_1273_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_0))) then 
            p_ZL13weight_memory_0_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_1_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_0_1_address1 <= p_ZL13weight_memory_0_1_addr_reg_1310_pp0_iter3_reg;
    p_ZL13weight_memory_0_1_ce0 <= p_ZL13weight_memory_0_1_ce0_local;

    p_ZL13weight_memory_0_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_1_ce1 <= p_ZL13weight_memory_0_1_ce1_local;

    p_ZL13weight_memory_0_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_1_d1 <= select_ln335_5_fu_1104_p3;
    p_ZL13weight_memory_0_1_we1 <= p_ZL13weight_memory_0_1_we1_local;

    p_ZL13weight_memory_0_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_1_reg_1282_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_1_reg_1282_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_0))) then 
            p_ZL13weight_memory_0_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_2_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_0_2_address1 <= p_ZL13weight_memory_0_2_addr_reg_1316_pp0_iter3_reg;
    p_ZL13weight_memory_0_2_ce0 <= p_ZL13weight_memory_0_2_ce0_local;

    p_ZL13weight_memory_0_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_2_ce1 <= p_ZL13weight_memory_0_2_ce1_local;

    p_ZL13weight_memory_0_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_2_d1 <= select_ln335_6_fu_1137_p3;
    p_ZL13weight_memory_0_2_we1 <= p_ZL13weight_memory_0_2_we1_local;

    p_ZL13weight_memory_0_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_2_reg_1291_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_2_reg_1291_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_0))) then 
            p_ZL13weight_memory_0_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_3_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_0_3_address1 <= p_ZL13weight_memory_0_3_addr_reg_1322_pp0_iter3_reg;
    p_ZL13weight_memory_0_3_ce0 <= p_ZL13weight_memory_0_3_ce0_local;

    p_ZL13weight_memory_0_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_3_ce1 <= p_ZL13weight_memory_0_3_ce1_local;

    p_ZL13weight_memory_0_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_0_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_0_3_d1 <= select_ln335_7_fu_1170_p3;
    p_ZL13weight_memory_0_3_we1 <= p_ZL13weight_memory_0_3_we1_local;

    p_ZL13weight_memory_0_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_3_reg_1300_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_3_reg_1300_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_0))) then 
            p_ZL13weight_memory_0_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_0_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_0_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_1_0_address1 <= p_ZL13weight_memory_1_0_addr_reg_1328_pp0_iter3_reg;
    p_ZL13weight_memory_1_0_ce0 <= p_ZL13weight_memory_1_0_ce0_local;

    p_ZL13weight_memory_1_0_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_0_ce1 <= p_ZL13weight_memory_1_0_ce1_local;

    p_ZL13weight_memory_1_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_0_d1 <= select_ln335_fu_1071_p3;
    p_ZL13weight_memory_1_0_we1 <= p_ZL13weight_memory_1_0_we1_local;

    p_ZL13weight_memory_1_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_reg_1273_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_reg_1273_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_1))) then 
            p_ZL13weight_memory_1_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_1_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_1_1_address1 <= p_ZL13weight_memory_1_1_addr_reg_1334_pp0_iter3_reg;
    p_ZL13weight_memory_1_1_ce0 <= p_ZL13weight_memory_1_1_ce0_local;

    p_ZL13weight_memory_1_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_1_ce1 <= p_ZL13weight_memory_1_1_ce1_local;

    p_ZL13weight_memory_1_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_1_d1 <= select_ln335_5_fu_1104_p3;
    p_ZL13weight_memory_1_1_we1 <= p_ZL13weight_memory_1_1_we1_local;

    p_ZL13weight_memory_1_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_1_reg_1282_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_1_reg_1282_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_1))) then 
            p_ZL13weight_memory_1_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_2_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_1_2_address1 <= p_ZL13weight_memory_1_2_addr_reg_1340_pp0_iter3_reg;
    p_ZL13weight_memory_1_2_ce0 <= p_ZL13weight_memory_1_2_ce0_local;

    p_ZL13weight_memory_1_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_2_ce1 <= p_ZL13weight_memory_1_2_ce1_local;

    p_ZL13weight_memory_1_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_2_d1 <= select_ln335_6_fu_1137_p3;
    p_ZL13weight_memory_1_2_we1 <= p_ZL13weight_memory_1_2_we1_local;

    p_ZL13weight_memory_1_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_2_reg_1291_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_2_reg_1291_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_1))) then 
            p_ZL13weight_memory_1_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_3_address0 <= zext_ln502_fu_459_p1(15 - 1 downto 0);
    p_ZL13weight_memory_1_3_address1 <= p_ZL13weight_memory_1_3_addr_reg_1346_pp0_iter3_reg;
    p_ZL13weight_memory_1_3_ce0 <= p_ZL13weight_memory_1_3_ce0_local;

    p_ZL13weight_memory_1_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_3_ce1 <= p_ZL13weight_memory_1_3_ce1_local;

    p_ZL13weight_memory_1_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_ZL13weight_memory_1_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL13weight_memory_1_3_d1 <= select_ln335_7_fu_1170_p3;
    p_ZL13weight_memory_1_3_we1 <= p_ZL13weight_memory_1_3_we1_local;

    p_ZL13weight_memory_1_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter4, tmp_reg_1186, ap_block_pp0_stage0_11001, icmp_ln484_3_reg_1300_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (icmp_ln484_3_reg_1300_pp0_iter3_reg = ap_const_lv1_0) and (tmp_reg_1186 = ap_const_lv1_1))) then 
            p_ZL13weight_memory_1_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL13weight_memory_1_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_eligibility_0_address0 <= zext_ln479_fu_400_p1(7 - 1 downto 0);
    p_ZL16post_eligibility_0_ce0 <= p_ZL16post_eligibility_0_ce0_local;

    p_ZL16post_eligibility_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL16post_eligibility_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_eligibility_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_eligibility_1_address0 <= zext_ln479_fu_400_p1(7 - 1 downto 0);
    p_ZL16post_eligibility_1_ce0 <= p_ZL16post_eligibility_1_ce0_local;

    p_ZL16post_eligibility_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL16post_eligibility_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_eligibility_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_eligibility_2_address0 <= zext_ln479_fu_400_p1(7 - 1 downto 0);
    p_ZL16post_eligibility_2_ce0 <= p_ZL16post_eligibility_2_ce0_local;

    p_ZL16post_eligibility_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL16post_eligibility_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_eligibility_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL16post_eligibility_3_address0 <= zext_ln479_fu_400_p1(7 - 1 downto 0);
    p_ZL16post_eligibility_3_ce0 <= p_ZL16post_eligibility_3_ce0_local;

    p_ZL16post_eligibility_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL16post_eligibility_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL16post_eligibility_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    scaled_10_fu_661_p4 <= mul_ln487_2_fu_656_p2(15 downto 12);
    scaled_12_fu_685_p4 <= mul_ln487_2_fu_656_p2(15 downto 10);
    scaled_13_fu_699_p4 <= mul_ln487_2_fu_656_p2(15 downto 11);
    scaled_14_fu_720_p10 <= ((icmp_ln491 & icmp_ln491_1) & icmp_ln491_2);
        scaled_14_fu_720_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_13_fu_699_p4),7));

        scaled_14_fu_720_p4 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_12_fu_685_p4),7));

    scaled_14_fu_720_p6 <= mul_ln487_2_fu_656_p2(15 downto 9);
        scaled_14_fu_720_p8 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_10_fu_661_p4),7));

    scaled_14_fu_720_p9 <= "XXXXXXX";
    scaled_15_fu_752_p4 <= mul_ln487_3_fu_747_p2(15 downto 12);
    scaled_17_fu_776_p4 <= mul_ln487_3_fu_747_p2(15 downto 10);
    scaled_18_fu_790_p4 <= mul_ln487_3_fu_747_p2(15 downto 11);
    scaled_19_fu_811_p10 <= ((icmp_ln491 & icmp_ln491_1) & icmp_ln491_2);
        scaled_19_fu_811_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_18_fu_790_p4),7));

        scaled_19_fu_811_p4 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_17_fu_776_p4),7));

    scaled_19_fu_811_p6 <= mul_ln487_3_fu_747_p2(15 downto 9);
        scaled_19_fu_811_p8 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_15_fu_752_p4),7));

    scaled_19_fu_811_p9 <= "XXXXXXX";
    scaled_2_fu_503_p4 <= mul_ln487_fu_474_p2(15 downto 10);
    scaled_3_fu_517_p4 <= mul_ln487_fu_474_p2(15 downto 11);
    scaled_4_fu_538_p10 <= ((icmp_ln491 & icmp_ln491_1) & icmp_ln491_2);
        scaled_4_fu_538_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_3_fu_517_p4),7));

        scaled_4_fu_538_p4 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_2_fu_503_p4),7));

    scaled_4_fu_538_p6 <= mul_ln487_fu_474_p2(15 downto 9);
        scaled_4_fu_538_p8 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_fu_479_p4),7));

    scaled_4_fu_538_p9 <= "XXXXXXX";
    scaled_5_fu_570_p4 <= mul_ln487_1_fu_565_p2(15 downto 12);
    scaled_7_fu_594_p4 <= mul_ln487_1_fu_565_p2(15 downto 10);
    scaled_8_fu_608_p4 <= mul_ln487_1_fu_565_p2(15 downto 11);
    scaled_9_fu_629_p10 <= ((icmp_ln491 & icmp_ln491_1) & icmp_ln491_2);
        scaled_9_fu_629_p2 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_8_fu_608_p4),7));

        scaled_9_fu_629_p4 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_7_fu_594_p4),7));

    scaled_9_fu_629_p6 <= mul_ln487_1_fu_565_p2(15 downto 9);
        scaled_9_fu_629_p8 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_5_fu_570_p4),7));

    scaled_9_fu_629_p9 <= "XXXXXXX";
    scaled_fu_479_p4 <= mul_ln487_fu_474_p2(15 downto 12);
    select_ln335_10_fu_1123_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_3_fu_1113_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln335_11_fu_1156_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_4_fu_1146_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln335_5_fu_1104_p3 <= 
        select_ln335_9_fu_1090_p3 when (or_ln335_1_fu_1098_p2(0) = '1') else 
        add_ln503_2_reg_1387;
    select_ln335_6_fu_1137_p3 <= 
        select_ln335_10_fu_1123_p3 when (or_ln335_2_fu_1131_p2(0) = '1') else 
        add_ln503_4_reg_1402;
    select_ln335_7_fu_1170_p3 <= 
        select_ln335_11_fu_1156_p3 when (or_ln335_3_fu_1164_p2(0) = '1') else 
        add_ln503_6_reg_1417;
    select_ln335_8_fu_1057_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_fu_1047_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln335_9_fu_1090_p3 <= 
        ap_const_lv8_7F when (icmp_ln335_2_fu_1080_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln335_fu_1071_p3 <= 
        select_ln335_8_fu_1057_p3 when (or_ln335_fu_1065_p2(0) = '1') else 
        add_ln503_reg_1372;
        sext_ln487_cast_fu_370_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln487),16));

        sext_ln490_11_fu_941_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_14_reg_1362),8));

        sext_ln490_15_fu_994_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_19_reg_1367),8));

        sext_ln490_3_fu_835_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_4_reg_1352),8));

        sext_ln490_7_fu_888_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(scaled_9_reg_1357),8));

        sext_ln499_1_fu_904_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_3_fu_897_p3),9));

        sext_ln499_2_fu_957_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_5_fu_950_p3),9));

        sext_ln499_3_fu_1010_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_7_fu_1003_p3),9));

        sext_ln499_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(delta_1_fu_844_p3),9));

        sext_ln503_1_fu_915_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_5_fu_908_p3),9));

        sext_ln503_2_fu_968_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_6_fu_961_p3),9));

        sext_ln503_3_fu_1021_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_7_fu_1014_p3),9));

        sext_ln503_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(current_w_fu_855_p3),9));

    tmp_72_fu_382_p3 <= ap_sig_allocacmp_j_3(9 downto 9);
    tmp_73_fu_443_p4 <= i(8 downto 1);
    tmp_reg_1186 <= empty;
    tmp_s_fu_452_p3 <= (tmp_73_fu_443_p4 & lshr_ln_reg_1243_pp0_iter1_reg);
    w_5_fu_925_p2 <= std_logic_vector(signed(sext_ln499_1_fu_904_p1) + signed(sext_ln503_1_fu_915_p1));
    w_6_fu_978_p2 <= std_logic_vector(signed(sext_ln499_2_fu_957_p1) + signed(sext_ln503_2_fu_968_p1));
    w_7_fu_1031_p2 <= std_logic_vector(signed(sext_ln499_3_fu_1010_p1) + signed(sext_ln503_3_fu_1021_p1));
    w_fu_872_p2 <= std_logic_vector(signed(sext_ln499_fu_851_p1) + signed(sext_ln503_fu_862_p1));
    zext_ln479_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_390_p4),64));
    zext_ln502_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_452_p3),64));
end behav;
