-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity snn_top_hls_decay_eligibility_traces_Pipeline_DECAY_PRE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_ZL15pre_eligibility_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_0_ce0 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_0_ce1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_0_we1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_1_ce0 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_1_ce1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_1_we1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_2_ce0 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_2_ce1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_2_we1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_2_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_3_ce0 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_ZL15pre_eligibility_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    p_ZL15pre_eligibility_3_ce1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_3_we1 : OUT STD_LOGIC;
    p_ZL15pre_eligibility_3_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of snn_top_hls_decay_eligibility_traces_Pipeline_DECAY_PRE is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv10_4 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_138_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal p_ZL15pre_eligibility_0_addr_reg_266 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_0_addr_reg_266_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_1_addr_reg_272 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_1_addr_reg_272_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_2_addr_reg_278 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_2_addr_reg_278_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_3_addr_reg_284 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_ZL15pre_eligibility_3_addr_reg_284_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln522_fu_189_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_reg_290 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_1_fu_209_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_1_reg_295 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_2_fu_229_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_2_reg_300 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_3_fu_249_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln522_3_reg_305 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln516_fu_156_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_fu_58 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln516_fu_164_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_7 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_ZL15pre_eligibility_0_ce0_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_0_we1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_0_ce1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_1_ce0_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_1_we1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_1_ce1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_2_ce0_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_2_we1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_2_ce1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_3_ce0_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_3_we1_local : STD_LOGIC;
    signal p_ZL15pre_eligibility_3_ce1_local : STD_LOGIC;
    signal lshr_ln_fu_146_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln_fu_175_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln522_fu_185_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln522_1_fu_195_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln522_1_fu_205_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln522_2_fu_215_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln522_2_fu_225_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln522_3_fu_235_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln522_3_fu_245_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component snn_top_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component snn_top_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((tmp_fu_138_p3 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_58 <= add_ln516_fu_164_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_58 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                p_ZL15pre_eligibility_0_addr_reg_266 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
                p_ZL15pre_eligibility_0_addr_reg_266_pp0_iter1_reg <= p_ZL15pre_eligibility_0_addr_reg_266;
                p_ZL15pre_eligibility_1_addr_reg_272 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
                p_ZL15pre_eligibility_1_addr_reg_272_pp0_iter1_reg <= p_ZL15pre_eligibility_1_addr_reg_272;
                p_ZL15pre_eligibility_2_addr_reg_278 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
                p_ZL15pre_eligibility_2_addr_reg_278_pp0_iter1_reg <= p_ZL15pre_eligibility_2_addr_reg_278;
                p_ZL15pre_eligibility_3_addr_reg_284 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
                p_ZL15pre_eligibility_3_addr_reg_284_pp0_iter1_reg <= p_ZL15pre_eligibility_3_addr_reg_284;
                sub_ln522_1_reg_295 <= sub_ln522_1_fu_209_p2;
                sub_ln522_2_reg_300 <= sub_ln522_2_fu_229_p2;
                sub_ln522_3_reg_305 <= sub_ln522_3_fu_249_p2;
                sub_ln522_reg_290 <= sub_ln522_fu_189_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln516_fu_164_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_7) + unsigned(ap_const_lv10_4));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_138_p3)
    begin
        if (((tmp_fu_138_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_58, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_7 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_7 <= i_fu_58;
        end if; 
    end process;

    lshr_ln_fu_146_p4 <= ap_sig_allocacmp_i_7(8 downto 2);
    p_ZL15pre_eligibility_0_address0 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
    p_ZL15pre_eligibility_0_address1 <= p_ZL15pre_eligibility_0_addr_reg_266_pp0_iter1_reg;
    p_ZL15pre_eligibility_0_ce0 <= p_ZL15pre_eligibility_0_ce0_local;

    p_ZL15pre_eligibility_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL15pre_eligibility_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_0_ce1 <= p_ZL15pre_eligibility_0_ce1_local;

    p_ZL15pre_eligibility_0_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_0_d1 <= sub_ln522_reg_290;
    p_ZL15pre_eligibility_0_we1 <= p_ZL15pre_eligibility_0_we1_local;

    p_ZL15pre_eligibility_0_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_0_we1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_0_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_1_address0 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
    p_ZL15pre_eligibility_1_address1 <= p_ZL15pre_eligibility_1_addr_reg_272_pp0_iter1_reg;
    p_ZL15pre_eligibility_1_ce0 <= p_ZL15pre_eligibility_1_ce0_local;

    p_ZL15pre_eligibility_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL15pre_eligibility_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_1_ce1 <= p_ZL15pre_eligibility_1_ce1_local;

    p_ZL15pre_eligibility_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_1_d1 <= sub_ln522_1_reg_295;
    p_ZL15pre_eligibility_1_we1 <= p_ZL15pre_eligibility_1_we1_local;

    p_ZL15pre_eligibility_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_1_we1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_2_address0 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
    p_ZL15pre_eligibility_2_address1 <= p_ZL15pre_eligibility_2_addr_reg_278_pp0_iter1_reg;
    p_ZL15pre_eligibility_2_ce0 <= p_ZL15pre_eligibility_2_ce0_local;

    p_ZL15pre_eligibility_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL15pre_eligibility_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_2_ce1 <= p_ZL15pre_eligibility_2_ce1_local;

    p_ZL15pre_eligibility_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_2_d1 <= sub_ln522_2_reg_300;
    p_ZL15pre_eligibility_2_we1 <= p_ZL15pre_eligibility_2_we1_local;

    p_ZL15pre_eligibility_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_2_we1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_3_address0 <= zext_ln516_fu_156_p1(7 - 1 downto 0);
    p_ZL15pre_eligibility_3_address1 <= p_ZL15pre_eligibility_3_addr_reg_284_pp0_iter1_reg;
    p_ZL15pre_eligibility_3_ce0 <= p_ZL15pre_eligibility_3_ce0_local;

    p_ZL15pre_eligibility_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL15pre_eligibility_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_3_ce1 <= p_ZL15pre_eligibility_3_ce1_local;

    p_ZL15pre_eligibility_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL15pre_eligibility_3_d1 <= sub_ln522_3_reg_305;
    p_ZL15pre_eligibility_3_we1 <= p_ZL15pre_eligibility_3_we1_local;

    p_ZL15pre_eligibility_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p_ZL15pre_eligibility_3_we1_local <= ap_const_logic_1;
        else 
            p_ZL15pre_eligibility_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln522_1_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln522_1_fu_195_p4),8));

        sext_ln522_2_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln522_2_fu_215_p4),8));

        sext_ln522_3_fu_245_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln522_3_fu_235_p4),8));

        sext_ln522_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_175_p4),8));

    sub_ln522_1_fu_209_p2 <= std_logic_vector(unsigned(p_ZL15pre_eligibility_1_q0) - unsigned(sext_ln522_1_fu_205_p1));
    sub_ln522_2_fu_229_p2 <= std_logic_vector(unsigned(p_ZL15pre_eligibility_2_q0) - unsigned(sext_ln522_2_fu_225_p1));
    sub_ln522_3_fu_249_p2 <= std_logic_vector(unsigned(p_ZL15pre_eligibility_3_q0) - unsigned(sext_ln522_3_fu_245_p1));
    sub_ln522_fu_189_p2 <= std_logic_vector(unsigned(p_ZL15pre_eligibility_0_q0) - unsigned(sext_ln522_fu_185_p1));
    tmp_fu_138_p3 <= ap_sig_allocacmp_i_7(9 downto 9);
    trunc_ln522_1_fu_195_p4 <= p_ZL15pre_eligibility_1_q0(7 downto 3);
    trunc_ln522_2_fu_215_p4 <= p_ZL15pre_eligibility_2_q0(7 downto 3);
    trunc_ln522_3_fu_235_p4 <= p_ZL15pre_eligibility_3_q0(7 downto 3);
    trunc_ln_fu_175_p4 <= p_ZL15pre_eligibility_0_q0(7 downto 3);
    zext_ln516_fu_156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_146_p4),64));
end behav;
